apache/bigtop

bigtop-ci/jenkins/jobsCreator.groovy
bigtop-tests/test-execution/common/pom.xml
pom.xml
src/site/resources/bigtop.rdf
src/site/site.xml
test/site/pom.xml
test/site/src/site/apt/downloads.apt

Do all the monkey changes to align the repository

BIGTOP-3128: Switch to new gitbox repository

---

bigtop-tests/smoke-tests/flink/TestFlink.groovy
bigtop-tests/smoke-tests/flink/build.gradle
bigtop-tests/smoke-tests/flink/test.data
build.gradle
provisioner/utils/smoke-tests.sh

Add flink to smoke tests.
Change-Id: Ib6a538a97347ec0e77b51c81b09a9d23a1a25a1a
Signed-off-by: Jun He <jun.he@linaro.org>

BIGTOP-3151: Add flink smoke test

---

bigtop-packages/src/common/spark/do-component-build
bigtop-packages/src/deb/spark/spark-core.install
bigtop-packages/src/rpm/spark/SPECS/spark.spec
bigtop.bom

Revert "BIGTOP-3165. Bump Spark to 2.4.0"

---

bigtop-packages/src/common/phoenix/phoenix-queryserver.svc

[BIGTOP-3194](https://issues.apache.org/jira/browse/BIGTOP-3194)

BIGTOP-3194. Fix Phoenix QueryServer PID file name

---

kubernetes/kubectl/plugin/README.md
kubernetes/kubectl/plugin/kubectl-bigtop

Skeleton plugin and simle doc for Bigtop plugin

BIGTOP-3245: Add kubectl plugin for Bigtop

---

bigtop-deploy/puppet/modules/tez/templates/environment
bigtop-tests/smoke-tests/tez/TestTezSmoke.groovy
bigtop-tests/smoke-tests/tez/build.gradle
provisioner/utils/smoke-tests.sh

Add smoke tests for Bigtop Tez.

BIGTOP-3234: TEZ smoke tests implementation

---

bigtop-deploy/puppet/modules/ignite_hadoop/templates/default-config.xml
bigtop-packages/src/common/ignite-hadoop/do-component-build
bigtop.bom

Bump Ignite to 2.7.6 for release-1.5.0.

BIGTOP-3286: Bump Ignite to 2.7.6

---

bigtop-tests/test-artifacts/hadoop/src/main/groovy/org/apache/bigtop/itest/hadoop/mapreduce/TestHadoopExamples.groovy

Tested with both mapreduce and qfs on Ubuntu 18.04.

BIGTOP-3413. QFS doesn't work with Hadoop's TeraGen.

---

bigtop-deploy/puppet/modules/ambari/manifests/init.pp
bigtop_toolchain/bin/puppetize.sh

Tested on Debian 10 and Fedora 31.

BIGTOP-3418. Fix Ambari deployment on CentOS 8, Fedora 31 and Debian 10.

---

bigtop-packages/src/common/hadoop/patch0-revert-HADOOP-16598.diff

[BIGTOP-3449](https://issues.apache.org/jira/browse/BIGTOP-3449)

BIGTOP-3449. Failed to build Haddop-2.10.1 on Arm64.

---

bigtop-packages/src/deb/spark/control
bigtop-packages/src/rpm/spark/SPECS/spark.spec

Tested on CentOS 7 and Ubuntu 18.04.

BIGTOP-3451. Fix smoke test for SparkR.

---

bigtop-deploy/puppet/modules/gpdb/manifests/init.pp
bigtop-packages/src/common/gpdb/patch1-specify-python-version.diff
bigtop-packages/src/deb/gpdb/control
bigtop-packages/src/rpm/gpdb/SPECS/gpdb.spec
bigtop.bom

https://issues.apache.org/jira/browse/BIGTOP-3514

BIGTOP-3514. Bump GPDB to 5.28.5.

---

bigtop-packages/src/deb/hadoop/control
bigtop-packages/src/deb/hadoop/rules

https://issues.apache.org/jira/browse/BIGTOP-3513

BIGTOP-3513. Update deb resources for hadoop-yarn-router and hadoop-hdfs-dfsrouter.

---

bigtop_toolchain/bin/puppetize.sh
bigtop_toolchain/manifests/packages.pp
provisioner/docker/config_fedora-33.yaml

https://issues.apache.org/jira/browse/BIGTOP-3522

BIGTOP-3522. Drop Fedora 31 and add Fedora 33 support.

---

bigtop-packages/src/common/hadoop/patch10-HADOOP-14922.diff

https://issues.apache.org/jira/browse/BIGTOP-3542

BIGTOP-3542. Fix build failure of Hadoop on ppc64le.

---

bigtop_toolchain/manifests/renv.pp

https://issues.apache.org/jira/browse/BIGTOP-3544

BIGTOP-3544. Fix Spark build on Debian 9.

---

bigtop-packages/src/common/phoenix/do-component-build

Change-Id: I7b153ae0c32b2d863488d3075c518e955d7cd9b2

BIGTOP-3554: Phoenix build failure caused by protoc-2.5.0

---

bigtop-deploy/puppet/modules/gpdb/manifests/init.pp
bigtop-packages/src/deb/gpdb/control
bigtop-packages/src/rpm/gpdb/SPECS/gpdb.spec

https://issues.apache.org/jira/browse/BIGTOP-3569

BIGTOP-3569. Applying GPDB Puppet manifest fails on arm64.

---

bigtop-deploy/puppet/hieradata/bigtop/cluster.yaml
bigtop-deploy/puppet/modules/elasticsearch/manifests/init.pp
bigtop-deploy/puppet/modules/elasticsearch/templates/elasticsearch.yml
bigtop-tests/smoke-tests/kibana/TestKibanaSmoke.groovy
provisioner/docker/docker-hadoop.sh

https://issues.apache.org/jira/browse/BIGTOP-3574

BIGTOP-3574. Starting Elasticsearch fails on ppc64le.

---

bigtop-deploy/puppet/modules/spark/manifests/init.pp

https://issues.apache.org/jira/browse/BIGTOP-3579

BIGTOP-3579. Spark smoke test fails on Debian 9 and Ubuntu 18.04.

---

bigtop-deploy/puppet/manifests/bigtop_repo.pp

https://issues.apache.org/jira/browse/BIGTOP-3580

BIGTOP-3580. Fix deployment failure on Debian 10 caused by the Debian 11 release.

---

.github/pull_request_template.md

Add a pull request template for GitHub 
None

BIGTOP-3638: Add pull request template for GitHub

---

build.gradle
packages.gradle

Upgrade the usage example on the task description, from ubuntu 16.04 to 18.04.
Bigtop 3 does not support ubuntu 16.04 so this PR would help users to avoid misunderstanding.
Check by hand,
```sh
./gradlew tasks|grep ubuntu-16.04
./gradlew tasks|grep ubuntu-18.04
```

BIGTOP-3643: Upgrade gradle task description from ubuntu 16.04 to 18.04

---

build.gradle

Fix RAT issues in Bigtop source tree
gradlew RAT

BIGTOP-3684: Fix RAT issues in Bigtop source tree

---

bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SQOOP/configuration/sqoop-atlas-application.properties.xml
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SQOOP/configuration/sqoop-env.xml
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SQOOP/configuration/sqoop-site.xml
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SQOOP/kerberos.json
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SQOOP/metainfo.xml
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SQOOP/package/scripts/__init__.py
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SQOOP/package/scripts/params.py
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SQOOP/package/scripts/params_linux.py
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SQOOP/package/scripts/params_windows.py
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SQOOP/package/scripts/service_check.py
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SQOOP/package/scripts/sqoop.py
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SQOOP/package/scripts/sqoop_client.py
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SQOOP/role_command_order.json
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SQOOP/service_advisor.py

BIGTOP-3734: Add Sqoop support for Bigtop 3.1.0 Mpack
Tested in CentOS7
This PR has one problem, refer to https://issues.apache.org/jira/browse/BIGTOP-3735
And the compoment was only tested on Mysql/HDFS, because Hive and Hbase are not integrated yet.

BIGTOP-3734: Add Sqoop support for Bigtop 3.1.0 Mpack

---

bigtop-packages/src/common/tez/install_tez.sh

BIGTOP-3742: Add tez.tar.gz to tez lib dir

---

bigtop-packages/src/common/sqoop/patch3-hadoop333-denpendency-changes.diff
bigtop.bom

BIGTOP-3737: Fix sqoop build fails

---

bigtop-packages/src/common/hbase/patch1-relocate-okhttp.diff
bigtop.bom

https://issues.apache.org/jira/browse/BIGTOP-3760
Hadoop 3.3.4 RC0 is under vote.
https://lists.apache.org/thread/r41ftyrs4b6g67sf8nz8xypfwohov7qb

[WIP]BIGTOP-3760. Bump Hadoop to 3.3.4.

---

bigtop-packages/src/common/ambari/patch10-webhdfs-encode-space.diff

BIGTOP-3752: WebHDFS api path encode space character

---

bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/ZEPPELIN/alerts.json
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/ZEPPELIN/configuration/zeppelin-env.xml
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/ZEPPELIN/configuration/zeppelin-log4j-properties.xml
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/ZEPPELIN/configuration/zeppelin-shiro-ini.xml
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/ZEPPELIN/configuration/zeppelin-site.xml
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/ZEPPELIN/kerberos.json
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/ZEPPELIN/metainfo.xml
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/ZEPPELIN/package/scripts/alerts/alert_check_zeppelin.py
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/ZEPPELIN/package/scripts/interpreter_json_template.py
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/ZEPPELIN/package/scripts/master.py
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/ZEPPELIN/package/scripts/params.py
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/ZEPPELIN/package/scripts/service_check.py
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/ZEPPELIN/package/scripts/status_params.py
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/ZEPPELIN/package/templates/input.config-zeppelin.json.j2
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/ZEPPELIN/quicklinks/quicklinks.json
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/ZEPPELIN/role_command_order.json
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/ZEPPELIN/service_advisor.py
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/ZEPPELIN/themes/directories.json
bigtop-packages/src/common/bigtop-ambari-mpack/dev-support/docker/centos7/build-containers.sh

Add Zeppelin support for Bigtop 3.1.0 Mpack
Need to test with #953 
Visit localhost:9995 to access zeppelin web ui(if you are using docker env, remember to expose the port to your local machine).

BIGTOP-3740: Add Zeppelin support for Bigtop 3.1.0 Mpack

---

bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SOLR/configuration/solr-env.xml
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SOLR/configuration/solr-log4j.xml
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SOLR/configuration/solr-security-json.xml
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SOLR/configuration/solr-xml.xml
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SOLR/metainfo.xml
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SOLR/package/scripts/params.py
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SOLR/package/scripts/service_check.py
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SOLR/package/scripts/setup_solr.py
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SOLR/package/scripts/solr.py
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SOLR/package/scripts/status_params.py
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SOLR/package/templates/solr-security.json.j2
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SOLR/package/templates/solr.conf.j2
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SOLR/package/templates/solr_jaas.conf.j2
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SOLR/properties/solr-env.sh.j2
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SOLR/properties/solr-log4j2.xml.j2
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SOLR/properties/solr.xml.j2
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SOLR/quicklinks/quicklinks.json
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SOLR/role_command_order.json
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SOLR/service_advisor.py
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SOLR/themes/directories.json
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SOLR/themes/theme.json
bigtop-packages/src/common/bigtop-ambari-mpack/dev-support/docker/centos7/sync-scripts.sh

BIGTOP-3772: Add Solr support for Bigtop 3.1.0 Mpack

---

bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KERBEROS/configuration/kerberos-env.xml
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KERBEROS/configuration/krb5-conf.xml
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KERBEROS/kerberos.json
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KERBEROS/metainfo.xml
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KERBEROS/package/scripts/kerberos_client.py
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KERBEROS/package/scripts/params.py
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KERBEROS/package/scripts/service_check.py
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KERBEROS/package/scripts/status_params.py
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KERBEROS/properties/krb5_conf.j2

https://issues.apache.org/jira/browse/BIGTOP-3789
Upgrade Kerberos service from 1.10.3-10 to 1.10.3-30.
And fix deployment issues:
https://github.com/apache/bigtop/pull/989#issuecomment-1229959105
Deploy HDFS by mpack based on https://github.com/apache/bigtop/pull/989

BIGTOP-3789: Decouple Kerberos services from Ambari Core

---

bigtop-packages/src/common/hive/install_hive.sh

BIGTOP-3791: Replace log4j with log4j2 for Hive package

---

bigtop-packages/src/common/kafka/install_kafka.sh
bigtop-packages/src/rpm/kafka/SPECS/kafka.spec

Tested with #994 
diff result:
```
145374 blocks
145374 blocks
1a2
> ./etc/kafka
11 blocks
11 blocks
```

BIGTOP-3797: Support parent directory configuration for Kafka rpm build script

---

bigtop-packages/src/common/tez/install_tez.sh
bigtop-packages/src/rpm/tez/SPECS/tez.spec

BIGTOP-3790: Add symlink for Tez conf dir

---

bigtop-packages/src/common/flink/install_flink.sh
bigtop-packages/src/rpm/flink/SPECS/flink.spec

diff result:
```
414098 blocks
414098 blocks
10 blocks
10 blocks
10 blocks
10 blocks
```

BIGTOP-3806: Support parent directory configuration for Flink rpm build script

---

bigtop-packages/src/common/zeppelin/install_zeppelin.sh
bigtop-packages/src/rpm/zeppelin/SPECS/zeppelin.spec

Tested with #994 
diff result:
```
1804877 blocks
1804877 blocks
```

BIGTOP-3798: Support parent directory configuration for Zeppelin rpm build script

---

bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SOLR/kerberos.json
bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SOLR/package/templates/solr-security.json.j2

BIGTOP-3792: Mpack solr fail to start when kerberos enabled

---

bigtop-deploy/puppet/manifests/cluster.pp
bigtop-deploy/puppet/modules/phoenix/manifests/init.pp

Adding Puppet Recipes for Apache Phoenix
```shell
$ ./docker-hadoop.sh -d \
--create 3 \
--image bigtop/puppet:trunk-centos-7 \
--memory 8g \
--repo http://repos.bigtop.apache.org/releases/3.1.0/centos/7/\$basearch \
--disable-gpg-check \
--stack hdfs,yarn,mapreduce,hbase,phoenix
```

BIGTOP-3819. Adding Puppet Recipes for Apache Phoenix

---

provisioner/docker/docker-hadoop.sh

Make docker-hadoop.sh support docker compose v2
1. install docker
```shell
yum install -y git yum-utils ruby
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum install docker-ce docker-ce-cli containerd.io docker-compose-plugin -y
systemctl start docker
```
2. test docker-hadoop.sh
```shell
./docker-hadoop.sh \
-d \
-dc2 \
--create 2 \
--image bigtop/puppet:trunk-centos-7 \
--memory 8g \
--repo http://repos.bigtop.apache.org/releases/3.1.0/centos/7/\$basearch \
--disable-gpg-check \
--stack hdfs,yarn,mapreduce,spark,hive
./docker-hadoop.sh \
-d \
--docker-compose-v2 \
--create 2 \
--image bigtop/puppet:trunk-centos-7 \
--memory 8g \
--repo http://repos.bigtop.apache.org/releases/3.1.0/centos/7/\$basearch \
--disable-gpg-check \
--stack …
```

BIGTOP-3693. Support Docker Compose V2

---

bigtop-packages/src/common/solr/install_solr.sh
bigtop-packages/src/rpm/solr/SPECS/solr.spec

diff result:
```
463279 blocks
463278 blocks
3d2
< ./etc/solr
17354 blocks
17354 blocks
11 blocks
11 blocks
```

BIGTOP-3825: Support parent directory configuration for Solr rpm build script

---

bigtop-packages/src/common/hbase/install_hbase.sh
bigtop-packages/src/deb/hbase/rules
bigtop-packages/src/rpm/hbase/SPECS/hbase.spec

diff result:
```
753496 blocks
753496 blocks
2d1
< ./etc/hbase
10 blocks
10 blocks
27 blocks
27 blocks
10 blocks
10 blocks
10 blocks
10 blocks
10 blocks
10 blocks
```

BIGTOP-3823: Support parent directory configuration for HBase rpm build script

---

bigtop-packages/src/common/hadoop/install_hadoop.sh
bigtop-packages/src/deb/hadoop/rules
bigtop-packages/src/rpm/hadoop/SPECS/hadoop.spec

diff result:
```
738393 blocks
738393 blocks
3d2
< ./etc/hadoop
79 blocks
79 blocks
229 blocks
229 blocks
92632 blocks
92632 blocks
236439 blocks
236439 blocks
131076 blocks
131076 blocks
13 blocks
13 blocks
12 blocks
12 blocks
103 blocks
103 blocks
12 blocks
12 blocks
13 blocks
13 blocks
12 blocks
12 blocks
12 blocks
12 blocks
21 blocks
21 blocks
28 blocks
28 blocks
146 blocks
146 blocks
79 blocks
79 blocks
11571 blocks
11571 blocks
141 blocks
141 blocks
10575 blocks
10575 blocks
12 blocks
12 blocks
97899 blocks
97899 blocks
12 blocks
12 blocks
12 blocks
12 blocks
12 blocks
12 blocks
12 blocks
12 blocks
12 blocks
12 blocks
```

BIGTOP-3821: Support parent directory configuration for Hadoop rpm build script

---

bigtop-packages/src/common/solr/install_solr.sh

BIGTOP-3825: remove debug messages on Solr build script

---

bigtop-packages/src/common/tez/install_tez.sh
bigtop-packages/src/rpm/tez/SPECS/tez.spec

diff result:
```
180682 blocks
180682 blocks
1d0
< ./etc/tez
```

BIGTOP-3826: Support parent directory configuration for Tez rpm build script

---

bigtop-packages/src/common/bigtop-select/conf-select
bigtop-packages/src/common/bigtop-select/distro-select
bigtop-packages/src/common/bigtop-select/install_select.sh
bigtop-packages/src/rpm/bigtop-select/SPECS/bigtop-select.spec
packages.gradle

BIGTOP-3847: Set bigtop-select to be consistent with -PparentDir

---

bigtop-packages/src/common/ranger/install_ranger.sh
bigtop-packages/src/rpm/ranger/SPECS/ranger.spec

Diff result:
```
1179544 blocks
1179544 blocks
151678 blocks
151678 blocks
139977 blocks
139977 blocks
189246 blocks
189246 blocks
132619 blocks
132619 blocks
215457 blocks
215457 blocks
432150 blocks
432150 blocks
186736 blocks
186736 blocks
203477 blocks
203477 blocks
65270 blocks
65270 blocks
39751 blocks
39751 blocks
187496 blocks
187496 blocks
```

BIGTOP-3849: Support parent directory configuration for Ranger rpm build script

---

bigtop.bom

BIGTOP-3874: Bump Flink to 1.15.3

---

bigtop-packages/src/common/ambari/patch12-extend-grafana-service-timeout.diff
bigtop-packages/src/common/ambari/patch5-refine-AMBARI-25599-for-Hadoop-3.4.diff

Adjust Ambari metrics dependency for Ambari-2.7.5 in Mpack deployment
Also extend the timeout of grafana service check.
1. Successfully Build Bigtop Ambari on centos7/rocky8/Debian-11 and smoke tests were passed:
```
./docker-hadoop.sh --create 3 \
--image bigtop/puppet:trunk-rockylinux-8 --memory 16g \
--repo  file:///bigtop-home/output --disable-gpg-check --enable-local-repo \
--stack ambari,bigtop-utils  \
--smoke-tests ambari
```
```
Successfully started process 'Gradle Test Executor 2'
Gradle Test Executor 2 started executing tests.
> Task :bigtop-tests:smoke-tests:ambari:test
org.apache.bigtop.itest.ambari.TestAmbariSmoke > testBlueprints STANDARD_OUT
[href:http://localhost:8080/api/v1/blueprints, items:[]]
org.apache.bigtop.itest.ambari.TestAmbariSmoke > testStackNameVersion …
```

BIGTOP-3872: Adjust Ambari metrics dependency for Ambari-2.7.5

---

bigtop.bom

BIGTOP-3888: Bump Spark to 3.2.3

---

bigtop.bom
packages.gradle

This PR enables us to define that some components only support either deb or rpm packaging.
Ran `./gradlew pkgs -Dbuildwithdeps=true` on all distros we support and ensured it worked as expected.
The output of `./gradlew all-components` is also changed a bit, as follows:
```
> Task :all-components
bigtop 3.2.0-SNAPSHOT stack includes the following components
alluxio                        2.8.0
ambari                         2.7.5
bigtop-ambari-mpack            2.7.5
bigtop-groovy                  2.5.4
bigtop-jsvc                    1.2.4
bigtop-select         3.2.0-SNAPSHOT (RPM only)
bigtop-utils          3.2.0-SNAPSHOT
flink                         1.15.3
gpdb                          5.28.5
hadoop                         3.3.4
hbase                         2.4.13
hive …
```

BIGTOP-3892. Fix build scripts so that we can define components which only supports deb or rpm.

---

bigtop-packages/src/common/ambari/patch5-refine-AMBARI-25599-for-Hadoop-3.4.diff

BIGTOP-3895: Use OSS version of Grafana for Ambari Metrics

---

bigtop-deploy/puppet/hieradata/bigtop/cluster.yaml
bigtop-deploy/puppet/manifests/cluster.pp
bigtop-deploy/puppet/modules/ranger/manifests/init.pp
bigtop-deploy/puppet/modules/ranger/templates/ranger-admin/install.properties

This PR adds a minimal Puppet manifest for Ranger. It only deploys ranger-admin and doesn't any other plugins, and only supports RPM, but it's better than nothing ;)
Ran docker provisioner locally on the following distros:
CentOS 7:
```
$ ./docker-hadoop.sh -d -C config_centos-7.yaml -G -L -k ranger -c 1
...
Notice: /Stage[main]/Ranger::Admin/Service[ranger-admin]/ensure: ensure changed 'stopped' to 'running'
Notice: Finished catalog run in 161.79 seconds
```
Rocky Linux 8:
```
$ ./docker-hadoop.sh -d -C config_rockylinux-8.yaml -F docker-compose-cgroupv2.yml -G -L -k ranger -c 1                                               
...
Notice: /Stage[main]/Ranger::Admin/Service[ranger-admin]/ensure: ensure changed 'stopped' to 'running'
Notice: Applied catalog in 159.69 seconds
```
Fedora 35: …

BIGTOP-3702. Add puppet manifests for Ranger.

---

bigtop-packages/src/deb/hbase/rules
bigtop-packages/src/rpm/hbase/SPECS/hbase.spec
bigtop.bom

Solve soft link error ,
Details see: [BIGTOP-3915](https://issues.apache.org/jira/browse/BIGTOP-3915)
building hbase rpm,
installing hbase,
check soft link about hadoop  in {hbase_home}/lib
rpm: hbase.spec
deb: hbase/rules
Please review @iwasakims thanks

BIGTOP-3915:soft link error about jar of hadoop in {hbase_home}/lib

---

README.md

BIGTOP-3784: Add "Customize build packages" section on README.md

---

bigtop-packages/src/common/bigtop-select/conf-select
bigtop-packages/src/common/bigtop-select/distro-select

Bigtop-select support Ranger
Tested in local cluster

BIGTOP-3910: Bigtop-select support Ranger

---

bigtop.bom

Update base version to 3.3.0 in bigtop.bom file
Tested locally

BIGTOP-3953. Update base version to 3.3.0 in bigtop.bom file

---

.asf.yaml

BIGTOP-3944: Enable squash and merge

---

bigtop-deploy/puppet/hieradata/bigtop/cluster.yaml
bigtop-deploy/puppet/hieradata/site.yaml
bigtop-deploy/puppet/manifests/cluster.pp
bigtop-tests/smoke-tests/solr/build.gradle

BIGTOP-3942: Rename solrcloud to solr for puppet role map

---

bigtop-packages/src/common/spark/LICENSE-binary
bigtop-packages/src/common/spark/do-component-build
bigtop-packages/src/common/spark/licenses-binary/LICENSE-blas.txt
bigtop-packages/src/common/spark/licenses-binary/LICENSE-datatables.txt
bigtop.bom

This PR upgrades Spark version to 3.3.3.
Ran the following commands on CentOS 7 (x86_64).
```
$ ./gradlew allclean spark-pkg repo -Dbuildwithdeps=true
$ ./docker-hadoop.sh -d -dcp -C config_centos-7.yaml -L -k hdfs,yarn,spark -s spark -c 3
...
> Task :bigtop-tests:smoke-tests:spark:test
Finished generating test XML results (0.019 secs) into: /bigtop-home/bigtop-tests/smoke-tests/spark/build/test-results/test
Finished generating test html results (0.028 secs) into: /bigtop-home/bigtop-tests/smoke-tests/spark/build/reports/tests/test
Now testing...
:bigtop-tests:smoke-tests:spark:test (Thread[Daemon worker,5,main]) completed. Took 1 mins 31.911 secs.
BUILD SUCCESSFUL in 1m 59s
31 actionable tasks: 6 executed, 25 up-to-date
```

BIGTOP-4016. Upgrade Spark to 3.3.3.

---

README.md
bigtop.bom

Add Documentation for Parallel Maven Compilation in Bigtop

BIGTOP-4059: Add Documentation for Parallel Maven Compilation in Bigtop

---

bigtop-packages/src/deb/hive/control

**Remove Python 2 dependencies from Ranger Debian packages to align deb dependencies with spec.**

BIGTOP-4049: Remove python dependency from Hive deb

---

bigtop-packages/src/deb/ranger/control

Remove Python 2 dependencies from Ranger Debian packages to align deb dependencies with spec.

BIGTOP-4050: Remove python dependency from Ranger deb

---

bigtop-deploy/puppet/manifests/jdk.pp
bigtop-deploy/puppet/manifests/python.pp
bigtop-deploy/puppet/manifests/yumrepo.pp
bigtop_toolchain/bin/puppetize.sh
bigtop_toolchain/manifests/packages.pp

https://issues.apache.org/jira/browse/BIGTOP-4148
Run the commands below on both Rocky 8/Rocky 9:
```
$ sudo dnf install git -y
$ sudo yum install java-1.8.0-openjdk-devel -y
$ git clone -b BIGTOP-4148 https://github.com/masatana/bigtop.git
$ cd bigtop
$ sudo bigtop_toolchain/bin/puppetize.sh
$ ./gradlew toolchain
```
And confirmed the Debug log like below:
Rocky8
```
(...snip...)
Debug: /Stage[main]/Bigtop_toolchain::Packages/Yumrepo[powertools]/before: before to Package[pandoc]
Debug: /Stage[main]/Bigtop_toolchain::Packages/Yumrepo[devel]/before: before to Package[java-11-openjdk-devel]
(...snip...)
Notice: /Stage[main]/Bigtop_toolchain::Packages/Yumrepo[powertools]/enabled: enabled changed '0' to '1'                     Debug: …
```

BIGTOP-4148. Replace adding repo in puppetize.sh with puppet manifest

---

bigtop-packages/src/common/zeppelin/do-component-build
bigtop.bom

```
./docker-hadoop.sh -d -dcp -C config_centos-7.yaml -G -L -k hdfs,flink -s flink -c 1
./docker-hadoop.sh -d -dcp -C config_centos-7.yaml -F docker-compose-cgroupv2.yml -G -L -k bigtop-utils,zeppelin -s zeppelin -c 1
```

BIGTOP-4099: Upgrade Flink to 1.17.2

---

bigtop-packages/src/common/hadoop/hadoop-hdfs-datanode.service
bigtop-packages/src/common/hadoop/hadoop-hdfs-dfsrouter.service
bigtop-packages/src/common/hadoop/hadoop-hdfs-journalnode.service
bigtop-packages/src/common/hadoop/hadoop-hdfs-namenode.service
bigtop-packages/src/common/hadoop/hadoop-hdfs-secondarynamenode.service
bigtop-packages/src/common/hadoop/hadoop-hdfs-zkfc.service
bigtop-packages/src/common/hadoop/hadoop-hdfs.tmpfile
bigtop-packages/src/common/hadoop/install_hadoop.sh
bigtop-packages/src/deb/hadoop/hadoop-hdfs.install
bigtop-packages/src/deb/hadoop/rules
bigtop-packages/src/rpm/hadoop/SPECS/hadoop.spec

https://issues.apache.org/jira/browse/BIGTOP-4271
Will check the perspectives below:
* Check if it works with RockyLinux ( to test RPM packaging)
* Check if it works with Ubuntu ( to test DEB packaging)
* Check if it passes smoke-tests (hdfs, yarn, mapreduce)

BIGTOP-4271. Provide systemd service unit files: Hadoop(HDFS)

---

bigtop-bigpetstore/bigpetstore-spark/README.md
bigtop-bigpetstore/bigpetstore-spark/build.gradle
bigtop-bigpetstore/bigpetstore-spark/src/main/scala/org/apache/bigpetstore/spark/analytics/PetStoreStatistics.scala
bigtop-bigpetstore/bigpetstore-spark/src/main/scala/org/apache/bigpetstore/spark/analytics/RecommendProducts.scala
bigtop-bigpetstore/bigpetstore-spark/src/main/scala/org/apache/bigpetstore/spark/datamodel/DataModel.scala
bigtop-bigpetstore/bigpetstore-spark/src/main/scala/org/apache/bigpetstore/spark/datamodel/IOUtils.scala
bigtop-bigpetstore/bigpetstore-spark/src/main/scala/org/apache/bigpetstore/spark/etl/ETL.scala
bigtop-bigpetstore/bigpetstore-spark/src/main/scala/org/apache/bigpetstore/spark/generator/SparkDriver.scala
bigtop-bigpetstore/bigpetstore-spark/src/test/scala/org/apache/bigpetstore/spark/TestFullPipeline.scala
bigtop-bigpetstore/bigpetstore-spark/src/test/scala/org/apache/bigpetstore/spark/analytics/AnalyticsSuite.scala
bigtop-bigpetstore/bigpetstore-spark/src/test/scala/org/apache/bigpetstore/spark/datamodel/IOUtilsSuite.scala
bigtop-bigpetstore/bigpetstore-spark/src/test/scala/org/apache/bigpetstore/spark/etl/ETLSuite.scala
bigtop-bigpetstore/bigpetstore-spark/src/test/scala/org/apache/bigpetstore/spark/generator/SparkDriverSuite.scala

This PR fixes bigpetstore-spark to use Spark 3.5.4 and Scala 2.12, instead of 1.3.0 and 2.10 respectively.
Note that it is intentional to built against Spark 3.5.4 while our stack currently has Spark 3.5.3. I came across some dependency problem when building it with Spark 3.5.3.
Before building bigpetstore-spark itself, we have to build the com.github.rnowling.bigpetstore package and install it locally due to the Jcenter and Bintray shutdown (BIGTOP-1961 will resolve it).
```
$ git clone --branch=v0.2.1 --depth=1 https://github.com/rnowling/bigpetstore-data-generator.git
$ cd bigpetstore-data-generator
$ vi build.gradle  # add the following lines
$ git diff
diff --git a/build.gradle b/build.gradle
index 23cae6b..ee35e00 100644
--- a/build.gradle
+++ b/build.gradle
@@ -1,6 +1,15 @@
apply …
```

BIGTOP-4368. Fix bigpetstore-spark to be built with the recent version of Spark and related libraries.

---

bigtop_toolchain/manifests/renv.pp

This PR fixes bigtop_toolchain to install required packages and upgrade R version for building Spark on openEuler 22.03. It also includes code cleanup for obsolete distro versions.
Ran the following commands and made sure they succeeded.
```
$ cd docker/bigtop-puppet
$ ./build.sh trunk-openeuler-22.03
$ cd ../bigtop-slaves
$ ./build.sh trunk-openeuler-22.03
$ cd ../..
$ ./gradlew allclean spark-pkg-ind -POS=openeuler-22.03 -Pdocker-run-option="--privileged"
```

BIGTOP-4393. Fix build failure of Spark on openeuler-22.03.

---

provisioner/docker/config_fedora-40.yaml

This is the same PR as #1353 for branch-3.4.
Same as #1353.

BIGTOP-4431. Upgrade Fedora's version in the docker provisioner config to 40.

---

bigtop-bigpetstore/bigpetstore-spark/README.md
bigtop-bigpetstore/bigpetstore-spark/build.gradle
bigtop-bigpetstore/bigpetstore-spark/src/main/scala/org/apache/bigpetstore/spark/analytics/PetStoreStatistics.scala
bigtop-bigpetstore/bigpetstore-spark/src/main/scala/org/apache/bigpetstore/spark/analytics/RecommendProducts.scala
bigtop-bigpetstore/bigpetstore-spark/src/main/scala/org/apache/bigpetstore/spark/datamodel/DataModel.scala
bigtop-bigpetstore/bigpetstore-spark/src/main/scala/org/apache/bigpetstore/spark/datamodel/IOUtils.scala
bigtop-bigpetstore/bigpetstore-spark/src/main/scala/org/apache/bigpetstore/spark/etl/ETL.scala
bigtop-bigpetstore/bigpetstore-spark/src/main/scala/org/apache/bigpetstore/spark/generator/SparkDriver.scala
bigtop-bigpetstore/bigpetstore-spark/src/test/scala/org/apache/bigpetstore/spark/TestFullPipeline.scala
bigtop-bigpetstore/bigpetstore-spark/src/test/scala/org/apache/bigpetstore/spark/datamodel/IOUtilsSuite.scala
bigtop-bigpetstore/bigpetstore-spark/src/test/scala/org/apache/bigpetstore/spark/etl/ETLSuite.scala
bigtop-bigpetstore/bigpetstore-spark/src/test/scala/org/apache/bigpetstore/spark/generator/SparkDriverSuite.scala
bigtop-bigpetstore/bigpetstore-transaction-queue/build.gradle
bigtop-bigpetstore/bigpetstore-transaction-queue/src/main/java/org/apache/bigtop/bigpetstore/qstream/FileLoadGen.java
bigtop-bigpetstore/bigpetstore-transaction-queue/src/main/java/org/apache/bigtop/bigpetstore/qstream/HttpLoadGen.java
bigtop-bigpetstore/bigpetstore-transaction-queue/src/main/java/org/apache/bigtop/bigpetstore/qstream/LoadGen.java
bigtop-bigpetstore/bigpetstore-transaction-queue/src/main/java/org/apache/bigtop/bigpetstore/qstream/Utils.java
bigtop-data-generators/bigpetstore-data-generator/src/main/java/org/apache/bigtop/datagenerators/bigpetstore/DataLoader.java
bigtop-data-generators/bigpetstore-data-generator/src/main/java/org/apache/bigtop/datagenerators/bigpetstore/datamodels/inputs/InputData.java
bigtop-data-generators/build.gradle

This PR improves maintainability and readability by introducing the DataFrame API and the spark.ml library instead of RDD and spark.mllib.
* Replace most of the RDD-based logic with the equivalent DataFrame-based one
* Replace the usage of spark.mllib.recommendation.ALS with spark.ml.recommendation.ALS
* Adopt Parquet for intermediate file format instead of SequenceFile
* Fix indents and spaces by applying formatter
This PR supersedes #1343.
Build bigtop-data-generator and install it into the local maven repository:
```
$ cd bigtop-data-generators
$ ../gradlew clean publishToMavenLocal
$ cd -
```
Build bps-spark:
```
$ cd bigtop-bigpetstore/bigpetstore-spark
$ ../../gradlew clean shadowJar
```
Run steps in accordance with bigtop-bigpetstore/bigpetstore-spark/README.md. Generate test data …

 BIGTOP-4424. Rewrite BPS Spark with the DataFrame API and spark.ml.

---

bigtop.bom

This PR upgrades Spark to 3.5.6.
Tested with Rocky 9 on x86_64, as follows:
```
$ ./gradlew allclean spark-pkg repo -Dbuildwithdeps=true
$ ./docker-hadoop.sh -d -dcp -C config_rockylinux-9.yaml -F docker-compose-cgroupv2.yml -G -L -r file:///bigtop-home/output -k hdfs,yarn,spark -s spark -c 1
...
> Task :bigtop-tests:smoke-tests:spark:test
Finished generating test XML results (0.026 secs) into: /bigtop-home/bigtop-tests/smoke-tests/spark/build/test-results/test
Finished generating test html results (0.026 secs) into: /bigtop-home/bigtop-tests/smoke-tests/spark/build/reports/tests/test
Now testing...
:bigtop-tests:smoke-tests:spark:test (Thread[Execution worker for ':',5,main]) completed. Took 55.498 secs.
BUILD SUCCESSFUL in 1m 12s
28 …
```

BIGTOP-4463. Upgrade Spark to 3.5.6.
