apache/bigtop

- provisioner/utils/smoke-tests.sh
Install mvn via bigtop_toolchain when apex smoke test specified.
> BIGTOP-3131. Apex smoke test requires mvn to compile test jar

- bigtop-tests/test-artifacts/hadoop/src/main/groovy/org/apache/bigtop/itest/hadoop/mapreduce/TestHadoopExamples.groovy
Since $USER may not be set when running in docker. Left it blank will result in running as current user.
> BIGTOP-3140. [Test] TestHadoopExamples.groovy can have $USER = null when running in Docker

- bigtop-deploy/puppet/manifests/cluster.pp
- bigtop-deploy/puppet/modules/qfs/manifests/init.pp
* Deploy qfs-client on worker
* remove notify on yarn resource manager
> BIGTOP-3144. [Test] QFS smoke test failed on multi-node cluster

- bigtop-deploy/puppet/modules/giraph/templates/giraph-site.xml
For workaround for GIRAPH-198 originally, giraph activated netty rpc by setting giraph.useNetty from command line.
In GIRAPH-200 later, giraph removed hadoop RPC and keep just netty by default.
So we can remove the Netty configuration accordingly.
> BIGTOP-3152: No need to Force the use of Netty over Hadoop RPC in Giraph

- bigtop-deploy/puppet/modules/flink/templates/flink-conf.yaml
- bigtop-packages/src/common/flink/install_flink.sh
- bigtop.bom
Bump Flink version from 1.4.2 to 1.6.4. There are three changes involved:
1. obviously, version number
2. in Flink 1.6.4, there is no 'resources' folder any more. Removed it.
3. set mode to 'legacy'
Starting from Flink v1.5, there is a rewrite of Flink’s deployment and process
model (internally known as FLIP-6). A new option 'mode' was introduced to
indicate which executions to use. However, the way Bigtop puppet deploys
'flink-jobmanager' and 'flink-taskmanager', ie. calling 'flink-daemon.sh
jobmanager' and 'flink-daemon.sh taskmanager', is legacy. Without setting
mode to 'legacy', flink's built-in exmaples fail with error
"JobSubmissionException: Failed to submit JobGraph"
> BIGTOP-3204. Bump Flink to 1.6.4

- bigtop-tests/smoke-tests/flink/TestFlink.groovy
Flink cannot get hdfs's defaultFS info on debian. Fix this by explicitly use
defaultFS uri retrieved from command
Change-Id: I648e10da3fd39d6daa9ae0079a47b075260c67ea
Signed-off-by: Jun He <jun.he@linaro.org>
> BIGTOP-3216: Flink smoke test failed on Debian-9

- bigtop_toolchain/manifests/packages.pp
To add Livy package, we need to install some additinal Python packages. (https://github.com/apache/bigtop/pull/527/)
setuptools .. Need to install newer setuptools. setuptools is installed in the some of distributions, but the package version is old. We'll need to install using pip.
flake8 .. install this package using pip
> BIGTOP-3214. Install python libraries for Livy

- bigtop-deploy/puppet/hieradata/bigtop/cluster.yaml
- bigtop-deploy/puppet/modules/kafka/manifests/init.pp
- bigtop-deploy/puppet/modules/kafka/templates/server.properties
- bigtop-packages/src/common/flume/patch0-FLUME-2662.diff
- bigtop-packages/src/common/flume/patch1-FLUME-3026_rebased.diff
- bigtop-packages/src/common/flume/patch2-scala-symbol.diff
- bigtop.bom
* Revert "BIGTOP-3185. Bump Kafka to 2.1.1 (#493)"
This reverts commit ca52568591010884687ac7616d09d97c63a89ebf.
* Revert "BIGTOP-3187. Bump Flume to 1.9.0"
This reverts commit 173d80e381cf8b527812e321f1908d90aeba9823.
* Revert "BIGTOP-3171. Update Kafka Puppet module for version 1.1.1 (#477)"
This reverts commit 6d5705e3e023caae39410888713f7bbf77578e09.
* Revert "BIGTOP-3164. Bump Kafka to 1.1.1 (#476)"
This reverts commit 12cb0ad24edb29e8cdac8d571a0472814629a40f.
> BIGTOP-3208. Exception in master branch (and branch-1.4): kafka-server failed to launch due to missing zookeeper AsyncCallback.MultiCallback

- bigtop-deploy/puppet/manifests/cluster.pp
- bigtop-deploy/puppet/modules/livy/manifests/init.pp
- bigtop-packages/src/common/hadoop/init-hcfs.json
- bigtop-tests/smoke-tests/livy/TestLivy.groovy
- bigtop-tests/smoke-tests/livy/build.gradle
- bigtop.bom
- provisioner/utils/smoke-tests.sh
Added smoke tests for Livy. Tested the test on my local env.
Related JIRA: [BIGTOP-296: Add Apache Livy (incubating) to Bigtop stack](https://issues.apache.org/jira/browse/BIGTOP-2961)
```
$ ../../gradlew livy:test -Psmoke.tests
> Task :bigtop-tests:smoke-tests:livy:test
Now testing...
BUILD SUCCESSFUL in 45s
6 actionable tasks: 6 executed
```
> BIGTOP-3217. Added smoke tests for Livy

- bigtop-tests/smoke-tests/kafka/TestKafkaSmoke.groovy
- bigtop-tests/smoke-tests/kafka/build.gradle
- provisioner/utils/smoke-tests.sh
Add Kafka smoke tests. Kafka depends on ZooKeeper.
Smoke test yaml:
```
components: [zookeeper, kafka]
enable_local_repo: true
smoke_test_components: [kafka]
```
> BIGTOP-3168: Kafka smoke tests implementation

- bigtop_toolchain/bin/puppetize.sh
- docker/bigtop-slaves/Dockerfile.template
- docker/bigtop-slaves/build.sh
* Add CentOS 8, Debian 10, Fedora 31, and Ubuntu 18.04 to the build scripts for bigtop-puppet and bigtop-slaves.
* Fix some issues in puppetize.sh.
I confirmed the bigtop-puppet and bigtop-slaves images for all supported distros in v1.5.0 were successfully created, as follows:
```
$ cd docker/bigtop-puppet
$ for i in centos-7 centos-8 debian-9 debian-10 fedora-31 ubuntu-16.04 ubuntu-18.04; do ./build.sh trunk-$i; done
$ echo $?
0
$ cd ../bigtop-slaves
$ for i in centos-7 centos-8 debian-9 debian-10 fedora-31 ubuntu-16.04 ubuntu-18.04; do ./build.sh trunk-$i; done
$ echo $?
0
$ docker images
REPOSITORY                                                            TAG                        IMAGE ID            CREATED             SIZE
bigtop/slaves …
```
> BIGTOP-3288. Update support distros in the Docker build scripts for v1.5.0

- bigtop-packages/src/common/solr/do-component-build
- bigtop.bom
Bump solr to latest version of 6.x branch.
Also updated maven repo to https access
Change-Id: I7f09d72d51d6c89b172e796189261590b37444c4
> BIGTOP-3313: Bump solor to 6.6.6

- bigtop.bom
I confirmed Kafka's latest stable version 2.4.0. 
I confirmed this patch worked on CentOS 8 at least.
The following log is smoke test running log.
```
[root@ip-172-31-16-186 bigtop]# cd bigtop-tests/smoke-tests/kafka
[root@ip-172-31-16-186 kafka]# ../../../gradlew test -Psmoke.tests --stacktrace
<============-> 93% EXECUTING [5s]
> :bigtop-tests:smoke-tests:kafka:test > 0 tests completed
> :bigtop-tests:smoke-tests:kafka:test > Executing test org.apache.bigtop.itest.kafka.TestKafkaSmoke
<============-> 93% EXECUTING [5s]cessed session termination for sessionid: 0x1000054bf270002 (org.apache.zookeeper.server.PrepRequestProcessor)
> :bigtop-tests:smoke-tests:kafka:test > 0 tests completedr client /172.31.16.186:53550 which had sessionid 0x1000054bf270002 (org.apache.zookeep> …
```
> BIGTOP-3285. Bump Kafka to 2.4.0

- bigtop-packages/src/common/alluxio/do-component-build
- bigtop-packages/src/common/alluxio/patch1-fix-hadoop-version-check.diff
- bigtop-packages/src/rpm/alluxio/SPECS/alluxio.spec
Alluxio build failed after hadoop is bumpped to 2.10.0. The reason is
the version check regex in integration/yarn/pom.xml doesn't cover
version higher than 2.9.x.
Spring release repo is upgraded to https access.
Change-Id: I83e38af640881e8d61213d58a636af7d50393cdb
> BIGTOP-3311: Fix Alluxio build failure with upgraded hadoop version

- bigtop_toolchain/lib/puppet/parser/functions/latest_ant_binary.rb
- bigtop_toolchain/lib/puppet/parser/functions/latest_maven_binary.rb
bigtop_toolchain uses packages list page hosted on
https://www.apache.org/dist/ to detect latest version of maven and ant.
This url has been moved to https://downloads.apache.org/ and latest_*_binary
functions need to be updated to reflect this.
To adapt to future URL change,'-L' option is added too.
Change-Id: Ia732be3c79f5d54b3db0eaa010adbfc8ff0d7395
> BIGTOP-3310: URL of maven and ant package list page is changed

- bigtop-packages/src/common/flink/patch0-fix-ApplicationReport-api.diff
Flink 1.6.4 failed to build with new hadoop 2.10.0. The root cause
is ApplicationReport newInstance API is changed.
Add a patch to upgrade API call in flink.
Change-Id: I5ae0f0e786a92f805feace67d5fe2facea0d9314
> BIGTOP-3314: Fix flink build failure with upgraded hadoop version

- bigtop-packages/src/common/hadoop/patch3-HADOOP-15062.diff
In BIGTOP-2932 a patch was backported from Hadoop upstream to better
support openssl 1.1.x. Some time later a new commit was filed to address
some corner cases, but it was never backported to BigTop.
On Debian 9 openssl 1.1.0 is the default, and BigTop builds against it.
When executing the command "hadoop checknative -a" though an error shows up:
openssl: false EVP_CIPHER_CTX_cleanup
The issue is that EVP_CIPHER_CTX_cleanup was removed from openssl 1.1.0, but
OpensslCipher.c kept using it until a proper if guard was added by the
patch provided by this pull request.
In my case this issue caused Spark 2.4's RPC encryption, based on Openssl native
lib, to fail when establishing new connections between workers and AM on Yarn.
I rebuilt the hadoop deb package with the patch and tested in the …
> BIGTOP-3308: add support for openssl 1.1.0 on Debian

- bigtop-packages/src/common/hbase/do-component-build
After HBase is bumped to 1.5.0, jruby patch command in build
script doesn't apply due to regex not match.
This patch refines sed command to make it more versatile to
various asciidoctorj-pdf versions.
Change-Id: Ib414ba3e7b66cf08e2080c75e1c83c563fa88224
> BIGTOP-3316: Fix HBase build failure on Arm platform

- bigtop-packages/src/common/oozie/install_oozie.sh
Add a workaround to the install_oozie.sh script to avoid duplicate
jars between oozie and oozie-client. This issue leads to override
errors when installing the oozie package on Debian (oozie-client
is among its dependencies).
Credis to Olaf Flebbe for the solution.
Tested the packages on a Debian system and it seems working fine.
> BIGTOP-3330: avoid duplicate jars between oozie and oozie-client

- provisioner/utils/setup-env-centos.sh
'yum.conf' doesn't exist in Fedora-29/31 environment.
It causes format error when echo "gpgcheck=0" >> /etc/yum.conf
So the provisioner deployment failed in Fedora-29/31.
> BIGTOP-3331: Provisioner Deployment failed on Fedora

- bigtop_toolchain/manifests/packages.pp
> BIGTOP-3351: Fix sqoop build error on Ubuntu 18.04

- bigtop_toolchain/manifests/packages.pp
> BIGTOP-3352: Fix qfs build error on Ubuntu 18.04

- bigtop-deploy/puppet/modules/hadoop_hive/templates/hive-site.xml
- bigtop-packages/src/common/hive/hive-site.xml
I confirmed that `hive.hwi.war.file` property exists in:
```
$ git log --oneline -n 1
399a210d (HEAD -> master, origin/master, origin/HEAD) BIGTOP-3347. Fix test failures of Hive ProxyFileSystem against Hadoop 2.10.0. (#633)
$ git grep hive.hwi.war.file
bigtop-deploy/puppet/modules/hadoop_hive/templates/hive-site.xml:  <name>hive.hwi.war.file</name>
bigtop-packages/src/common/hive/hive-site.xml:  <name>hive.hwi.war.file</name>
```
With this PR, I confirmed there is no `hive.hwi.war.file` property anymore.
(Prerequisite: built hive and dependent packages and created local repositoy)
* rpm
```
$ sudo yum install hive*
(snip)
$ grep hive.hwi.war.file /etc/hive/conf/hive-site.xml
$ (no output)
```
<details>
<summary>hive-site.xml</summary>
<pre>
<code>
$ cat /etc/hive/conf/hive-site.xml
<?xml …
> BIGTOP-3353: hive.hwi.war.file configuration is no longer needed

- bigtop-deploy/puppet/manifests/cluster.pp
- bigtop-deploy/puppet/modules/bigtop-util/lib/puppet/parser/functions/get_roles.rb
This PR updates `get_roles.rb` to be faild if there is no such component which is specified in user config.
Before:
```
$ cat config.yaml
docker:
memory_limit: "4g"
image: "bigtop/puppet:trunk-centos-7"
repo: "http://repos.bigtop.apache.org/releases/1.4.0/centos/7/$basearch"
distro: centos
components: [foobar]
enable_local_repo: false
smoke_test_components: []
$ ./docker-hadoop.sh -c 1
(snip)
(not failed)
```
After:
```
$ ./docker-hadoop.sh -c 1
(snip)
Error: get_roles(): No such component in roles_map. foobar on node 7541662d9555.bigtop.apache.org
Error: get_roles(): No such component in roles_map. foobar on node 7541662d9555.bigtop.apache.org
[LOG] Failed to provision container 7541662d95558968b99a07be71813b030a0f827243ca7a3d0f6c25c9d6cc784c with exit code 1
```
Also I updated existed …
> BIGTOP-3358: get_roles() function should fail if a component is not in roles_map

- bigtop_toolchain/bin/puppetize.sh
libcrypt.so.1 is not available in Fedora-31 for Arm64 (both in bigtop/puppet and bigtop/slaves) and x86( just in bigtop/puppet).
It would cause some dependency issues when some pacakges need to link it such as jffi.
Add libxcrypt-compat in Bigtop_toolchain to fix it.
> BIGTOP-3361: No libcrypt.so.1 in Fedora-31

- bigtop_toolchain/bin/puppetize.sh
Update puppetize.sh to use CodeReady repo when the environment is RHEL8.
I tested this change w/ RHEL8 on AWS EC2.
Note that if you want to run puppetize.sh, you may have to add /opt/puppetlabs/bin in secure_path as noted in [README.md](https://github.com/apache/bigtop/blob/master/README.md#for-developers-building-the-entire-distribution-from-scratch) and re-login.
(Though this is out-of-scope of this PR, should we automate this process?)
> BIGTOP-3369: RHEL8 does not have PowerTools repo but CodeReady Builder

- bigtop-packages/src/common/zeppelin/do-component-build
- bigtop-packages/src/common/zeppelin/zeppelin.svc
- bigtop-tests/smoke-tests/zeppelin/TestZeppelinSmoke.groovy
- bigtop-tests/smoke-tests/zeppelin/build.gradle
- provisioner/utils/setup-env-debian.sh
- provisioner/utils/smoke-tests.sh
The Smoke tests deployment by provisioner would be broken due to [BIGTOP-2742](https://issues.apache.org/jira/browse/BIGTOP-2742), but actually zeppelin server has been started.
> BIGTOP-3236: Zeppelin smoke tests implementation

- bigtop_toolchain/manifests/packages.pp
setuptools could not be installed by pip/pip2 on Ubuntu-16.04/18.04 and centos-7.
From https://packaging.python.org/tutorials/installing-packages/#requirements-for-installing-packages,  it suggests to leverage python3/pip3 to install setuptools package.
> BIGTOP-3364: Leverage pip3/python3 to install setuptools

- bigtop-deploy/puppet/hiera.yaml
- bigtop-deploy/puppet/hieradata/bigtop/repo.yaml
- bigtop-deploy/puppet/manifests/bigtop_repo.pp
- provisioner/docker/docker-hadoop.sh
- provisioner/utils/setup-env-debian.sh
I added a little modification (only replaced a package name "gpg" with "gnupg") to the PR @evans-ye submitted in #639 so that it works with Debian 9.
I tested this on Debian 9 and Ubuntu 16.04 as follows:
* Disable local repo (= enable GPG check) on Debian 9:
```
~/repos/bigtop/provisioner/docker$ cat config_debian-9.yaml 
(snip)
docker:
memory_limit: "4g"
image: "bigtop/puppet:trunk-debian-9"
repo: "http://repos.bigtop.apache.org/releases/1.4.0/debian/9/$(ARCH)"
distro: debian
components: [hdfs, yarn, mapreduce]
enable_local_repo: false
smoke_test_components: [hdfs, yarn, mapreduce]
~/repos/bigtop/provisioner/docker$ ./docker-hadoop.sh -d -C config_debian-9.yaml -c 1
(snip)
Notice: /Stage[main]/Bigtop_repo/Apt::Key[add_key]/Apt_key[add_key]/ensure: created
(snip)
Notice: Applied catalog …
```
> BIGTOP-3355. [Puppet] Make GPG check for repos a configuration and default to true

- bigtop.bom
Please refer to [BIGTOP-3380](https://issues.apache.org/jira/browse/BIGTOP-3380) for the background.
> BIGTOP-3380. Bump Tomcat to 8.5.57.

- bigtop-packages/src/common/ambari/patch4-AMBARI-CentOS8.diff
- bigtop-packages/src/rpm/ambari/SPECS/ambari.spec
- bigtop_toolchain/manifests/packages.pp
@guyuqi @mattAndruff @masatana Would you review if possible? In this PR, I intended:
* Specify python package name explicitly as 'python2' in spec files so that they work with CentOS 8 and Fedora 31
* Replace Ambari functions that depend on the rpm-python package, which is not provided on CentOS 8, with an implementation using the `rpm` command
* Define the `python` command as an alias of `python2` on CentOS 8 and Fedora 31, which don't provide unversioned python command by default
I confirmed that Ambari, Livy and Zeppelin (the latter of two use Python3, in contrast to Ambari) are successfully built on CentOS 7, 8 and Fedora 31 with this PR.
> BIGTOP-3371. Unable to build Apache Ambari on RHEL8.

- bigtop_toolchain/manifests/renv.pp
> BIGTOP-3389 (addendum). Extend timeout for installing R packages again.

- bigtop-ci/build.sh
- packages.gradle
With this PR, we can pass some options from Jenkins to the `docker run` command for avoiding the problem reported as BIGTOP-3392.
I confirmed that the specified options were passed to the `docker run` command, as follows:
```
$ ./gradlew -Pprefix=trunk -POS=debian-9 -Pdocker-run-option="-v $HOME/.m2:/root/.m2" bigtop-utils-pkg-ind
(snip)
++ docker run -d -v /home/sekikn/.m2:/root/.m2 bigtop/slaves:trunk-debian-9 /sbin/init
(snip)
BUILD SUCCESSFUL in 6m 15s
1 actionable task: 1 executed
```
```
$ ./gradlew -Pprefix=trunk -POS=debian-9 -Pdocker-run-option="-v $HOME/.m2:/root/.m2" repo-ind
(snip)
++ docker run -d -v /home/sekikn/.m2:/root/.m2 bigtop/slaves:trunk-debian-9 /sbin/init
(snip)
BUILD SUCCESSFUL in 5m 14s
1 actionable task: 1 executed
```
> BIGTOP-3392. All packaging jobs are failing on Fedora 31 for aarch64 and ppc64le.

- bigtop-packages/src/common/gpdb/patch2-fix-deprecated-first-element-index-in-perl.diff
GPDB is using a special variable $[ in its Perl script,
but it was deprecated from v5.30. So it can't be built
on some distros, e.g., Fedora 31 and Ubuntu 20.04.
This patch fixes indexs used in array and substr functions.
Change-Id: I92c793243c37ce57ffe146b71a5f732488f5e4a9
> BIGTOP-3391: Support GPDB on Perl 5.30+ environment

- bigtop-tests/smoke-tests/build.gradle
- bigtop.bom
- bigtop_toolchain/manifests/gradle.pp
- bigtop_toolchain/manifests/groovy.pp
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- packages.gradle
- pom.xml
This PR upgrades Groovy and Gradle to v2.5.4 and v5.6.4 respectively so that building Kafka on fedora-31-aarch64 succeeds.
I confirmed `./gradlew kafka-pkg` after `./gradlew toolchain` succeeded inside the fedora-31-aarch64 container with this PR.
> BIGTOP-3395. Building Kafka is failing on Fedora 31 for ARM64.

- bigtop-deploy/puppet/modules/gpdb/manifests/init.pp
> BIGTOP-3398. Fix GPDB puppet manifest to work.

- bigtop-packages/src/common/bigtop-groovy/install_groovy.sh
In my understanding, bigtop-packages/src/common/hadoop/init-hdfs.sh (and its callee init-hcfs.groovy) are the only users of bigtop-groovy for now. They requires groovy's core and json features, so I fixed install_groovy.sh to just install groovy.jar and groovy-json.jar instead of the former groovy-all.jar, which is no longer provided as a uber-jar.
With this PR, I made sure init-hdfs succeeded on my local ubuntu 18.04, as follows:
```
$ ./gradlew realclean hadoop-pkg repo -Dbuildwithdeps=true
$ cat /etc/puppet/hieradata/site.yaml
(snip)
hadoop_cluster_node::cluster_components:
- hdfs
- yarn
- mapreduce
bigtop::bigtop_repo_uri: file:///home/sekikn/repos/bigtop/output/apt
bigtop::jdk_preinstalled: true
bigtop::bigtop_repo_gpg_check: false
$ sudo puppet apply …
```
> BIGTOP-3399. Fix bigtop-groovy build failure.

- bigtop_toolchain/bin/puppetize.sh
- build.gradle
- docker/bigtop-slaves/build.sh
- provisioner/docker/docker-hadoop.sh
1. Enable Centos-8 docker image on Arm64.
2. Modify Puppet modulepath for puppetlabs-4.12 to fix issue :`'Unknown function: 'any2array'`
3. Fix docker provisioner on Arm64 Centos-8.
4. Fix `shellcheck `warning in `bash `scripts.
> BIGTOP-3401: Failed to build Centos-8 docker images for Arm64

- provisioner/docker/docker-hadoop.sh
[Link to BIGTOP-3408](https://issues.apache.org/jira/browse/BIGTOP-3408)
> BIGTOP-3408. hadoop-docker.sh generates broken site.yaml from config.yaml containing multiple components.

- bigtop_toolchain/bin/puppetize.sh
I confirmed that newly built bigtop/puppet image with this PR has the ps command, as follows:
```
$ docker run -it debian:10 ps  # The original Debian 10 image doesn't have the ps command
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"ps\": executable file not found in $PATH": unknown.
ERRO[0000] error waiting for container: context canceled 
$ cd docker/bigtop-puppet
$ ./build.sh trunk-debian-10
(snip)
Successfully built ad86d3a95f32
Successfully tagged bigtop/puppet:trunk-debian-10
++ rm -f Dockerfile puppetize.sh
$ docker run -it bigtop/puppet:trunk-debian-10 ps  # Confirm successful installation
PID TTY          TIME CMD
1 pts/0    00:00:00 ps
```
> BIGTOP-3407. Ensure the procps package is installed in Debian 10.

- bigtop-packages/src/common/logstash/do-component-build
when rvm install ruby-2.4.0 under user: jenkins,
it fails to "try_sudo" to install autolibs dependencies.
Disable unnecessary autolibs installation.
> BIGTOP-3394: Building Logstash is failing on CentOS 8, Debian 10 and Ubuntu 18.04

- bigtop-packages/src/common/ycsb/patch0-python-executable-version.diff
- bigtop-packages/src/rpm/ycsb/SPECS/ycsb.spec
Tested on CentOS 7/8 and Fedora 31.
> BIGTOP-3416. Fix YCSB to work with CentOS 8 and Fedora 31.

- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/pom.xml
- build.gradle
Make it possible to use Buildnumber-maven-plugin to generate build number
without unnecessary scm check. And fix 'rat' issues.
Confirmed that build:  `./gradlew bigtop-ambari-mpack-pkg ` was passed on:
Ubuntu18.04/16.04, Centos-7/8, Debian-10 and Fedora-31 (x86/Arm64).
> BIGTOP-3411: Disable unnecessary scm check in Buildnumber-maven-plugin for Mpack

- bigtop-packages/src/common/spark/patch2-snappy-java-1.1.8.diff
snappy-java must be upgraded to 1.1.8 to fix build issue on aarm64 and ppc64le.
https://issues.apache.org/jira/browse/BIGTOP-3397
> BIGTOP-3397. Building Spark is failing on CentOS 7 for ARM64 and PPC64.

- bigtop-packages/src/common/oozie/catalina.properties
- bigtop-packages/src/common/oozie/install_oozie.sh
- bigtop-packages/src/rpm/oozie/SPECS/oozie.spec
- bigtop-tests/smoke-tests/oozie/build.gradle
- bigtop-tests/test-artifacts/oozie/src/main/groovy/org/apache/bigtop/itest/ooziesmoke/TestOozieSmoke.groovy
- provisioner/docker/docker-hadoop.sh
- provisioner/utils/smoke-tests.sh
This PR contains the following changes.
* Change class loading order defined in catalina.properties so as to start Oozie webapp without jar signing error.
* Add environment variables to smoke-tests.sh, which are required to run Oozie smoke test. Also reorder them in alphabetical order for maintainability.
* Disable unit tests which depend on Pig functionality.
* Replace the hive test with hive2 since the former doesn't seem to work with the default hive setup.
> BIGTOP-3406. Fix Oozie smoke test to work.

- bigtop-packages/src/common/oozie/install_oozie.sh
jars are removed by install_oozie.sh on building RPM due to the fix of [BIGTOP-3330](https://issues.apache.org/jira/browse/BIGTOP-3330). The cause is that bigtop-packages/src/common/oozie/install_oozie.sh is written in deb centric way. I prefer quick-fix rather than overhaul here.
> BIGTOP-3439. Oozie's smoke test fails on CentOS and Fedora.

- bigtop-deploy/puppet/modules/gpdb/manifests/init.pp
Tested with Debian 9, Ubuntu 16.04 and 18.04 on AWS m6g (ARM64) instances.
> BIGTOP-3427. Deploying GPDB fails due to the paramiko installation on some distros (addendum).

- bigtop-packages/src/common/flume/patch5-BIGTOP-3440.diff
The solr sink currently depends on kite, that it is a library not
developed anymore. There are currently build failures due to
the ua_parser library, that was available in a Twitter maven repository
not maintained anymore (since it throws HTTP 503s consistently).
Flume upstream moved the dependency to another repository,
https://github.com/apache/flume/commit/9e0bc5bf4865673e6989ba887d27f468991c1e27
that fixes the Twitter problem but that brings in another build failure
for the 'rome' dependency.
This commit removes the solr sink from the build list, resolving the
overall build problem for Flume.
> BIGTOP-3440: disable flume solr sink to avoid build failures

- bigtop-deploy/puppet/modules/qfs/manifests/init.pp
This PR ensures that symlinks to qfs shared libraries are created after target directory creation. Tested with Ubuntu 16.04 and 18.04 on x86_64.
> BIGTOP-3429. QFS smoke test fails on Ubuntu 16.04.

- bigtop_toolchain/manifests/renv.pp
R version in Ubuntu16.04 is 3.2.3.
The packages 'digest' and 'htmltools' are not available (for R version 3.2.3).
There are some other dependency issues in R-3.2 which seems to be deprecated.
Upgrade the R version to 3.4 for ubuntu-16.04.
> BIGTOP-3443: Building Spark fails on Ubuntu 16.04

- bigtop_toolchain/manifests/renv.pp
This if follow-up of  [BIGTOP-3443](https://issues.apache.org/jira/browse/BIGTOP-3443) / #697 .
> BIGTOP-3446. Fix toolchain task failure due to undefined variable in renv.pp.

- bigtop-packages/src/common/alluxio/patch2-fix-jnr-fuse-repo.diff
> BIGTOP-3448. Building Alluxio fails on all distros.

- bigtop-packages/src/common/hive/patch5-HIVE-17368.diff
In Kerberos-enabled environments, Hive < 2.4.x (still not released) suffers
the problem outlined in HIVE-17368. This patch is related to the following commit:
https://github.com/apache/hive/commit/b3a6e524a6cb17893cbbeb26a877b0196ba16e21
The commit is related to the backport of the patch for the Hive 2.x branch.
Tested on top of Bigtop 1.4 (the issue that I was experiencing with Oozie
got fixed) but I haven't tested it with Bigtop 1.5 (but I am reasonably sure
that it works fine).
Built the hive-pkg target on slave-debian10, no issue reported.
> BIGTOP-3455: add hive patch to fix HIVE-17368

- bigtop-packages/src/common/zookeeper/do-component-build
- bigtop-packages/src/common/zookeeper/install_zookeeper.sh
- bigtop-packages/src/common/zookeeper/patch0-ZOOKEEPER-3079.diff
- bigtop-packages/src/common/zookeeper/patch1-ZOOKEEPER-3302.diff
- bigtop-packages/src/common/zookeeper/patch2-ZOOKEEPER-2654.diff
- bigtop.bom
https://issues.apache.org/jira/browse/BIGTOP-3475
* addressed changes made by [ZOOKEEPER-3021](https://issues.apache.org/jira/browse/ZOOKEEPER-3021).
> BIGTOP-3475. Bump ZooKeeper to 3.4.14.

- bigtop-packages/src/common/hbase/do-component-build
https://issues.apache.org/jira/browse/BIGTOP-3478
There was unexpected guava-11.0.2.jar in the hbase classpath.
```
$ rpm -qlp output/hbase/x86_64/hbase-2.2.6-1.el8.x86_64.rpm | grep guava
/usr/lib/hbase/lib/guava-11.0.2.jar
/usr/lib/hbase/lib/jersey-guava-2.25.1.jar
```
The cause was
* missing `-Dhadoop.guava.version=27.0-jre` on hbase build.
* missing `-Phadoop-3.0` due to bug in do-component-build.
> BIGTOP-3478. Fix version mismatch of Guava between Hadoop and HBase.

- bigtop-deploy/puppet/modules/hadoop/templates/yarn-site.xml
https://issues.apache.org/jira/browse/BIGTOP-3494
MapReduce job does not work without adding HADOOP_MAPRED_HOME to the value of yarn.nodemanager.env-whitelist. testDistcpIntra and testDistcpIntra_MultipleSources reproducibly fails after upgrading hadoop to 3.2 due to this.
> BIGTOP-3494. Add MapReduce settings to yarn.nodemanager.env-whitelist in yarn-site.xml.

- bigtop-packages/src/deb/hadoop/control
- bigtop-packages/src/rpm/hadoop/SPECS/hadoop.spec
https://issues.apache.org/jira/browse/BIGTOP-3497
libcrypto.so is required by OpensslCipher and OpensslSecureRandom of Hadoop.
> BIGTOP-3497. libcrypto.so should be provided for libhadoop.so.

- bigtop-deploy/puppet/hieradata/bigtop/cluster.yaml
- bigtop-deploy/puppet/modules/hadoop/manifests/init.pp
- bigtop-deploy/puppet/modules/hadoop/templates/kms-env.sh
https://issues.apache.org/jira/browse/BIGTOP-3505
Current Puppet manifests of hadoop-kms assumes hadoop-2. It does not work for hadoop-3 without fix.
> BIGTOP-3505. Update hadoop-kms puppet manifests based on hadoop-3.

- bigtop-deploy/puppet/modules/hadoop/manifests/init.pp
- bigtop-deploy/puppet/modules/hadoop/templates/httpfs-env.sh
- bigtop-packages/src/common/hadoop/hadoop-httpfs.svc
- bigtop-packages/src/common/hadoop/httpfs.default
- bigtop-packages/src/common/hadoop/install_hadoop.sh
- bigtop-packages/src/common/hadoop/patch6-fix-httpfs-sh.diff
- bigtop-packages/src/deb/hadoop/hadoop-httpfs.dirs
- bigtop-packages/src/deb/hadoop/hadoop-httpfs.install
- bigtop-packages/src/deb/hadoop/hadoop-httpfs.postinst
- bigtop-packages/src/deb/hadoop/rules
- bigtop-packages/src/rpm/hadoop/SPECS/hadoop.spec
https://issues.apache.org/jira/browse/BIGTOP-3506
Resrouces for hadoop-httpfs such as init scripts, service configuration and puppet manifests should be updated based on hadoop-3 same as done for hadoop-kms in [BIGTOP-3501](https://issues.apache.org/jira/browse/BIGTOP-3501) and [BIGTOP-3505](https://issues.apache.org/jira/browse/BIGTOP-3505).
> BIGTOP-3506. Update hadoop-httpfs resources based on hadoop-3.

- bigtop-packages/src/common/solr/patch0-SOLR-14663-backport.diff
- bigtop-packages/src/rpm/solr/SPECS/solr.spec
Fix unauthenticated configset uploads security risk. Patch in SOLR-14663
is backported to v6.6.6
Change-Id: I40c6f7d0edae057acd2182174dbf5fea84c0b825
> BIGTOP-3507: CVE-2020-13957 mitigation backport

- bigtop-packages/src/common/sqoop/install_sqoop.sh
On Debian 10 the package libslf4j-java deploys various jars to the
system, including log4j-over-slf4j.jar or slf4j-log4j12.jar that cannot
be added to the classpath together (see http://www.slf4j.org/codes.html#log4jDelegationLoop).
From my tests it seems that dropping /usr/share/java from the sqoop's
classpath is safe, I didn't notice any regression.
Co-authored-by: Kengo Seki <sekikn@apache.org>
> BIGTOP-3508: drop /usr/share/java from sqoop's bin classpath

- bigtop-packages/src/common/hadoop/do-component-build
- bigtop-packages/src/common/hadoop/hadoop-hdfs-dfsrouter.svc
- bigtop-packages/src/common/hadoop/hadoop-yarn-router.svc
- bigtop-packages/src/common/hadoop/install_hadoop.sh
- bigtop-packages/src/rpm/hadoop/SPECS/hadoop.spec
I have used bigtop to release our production cluster based hadoop 3.2.1(with some 3.3.0 patchs fixed), and some hadoop env related not fixed in default.
1.  Fix  start/stop error service pid
2. Fix historyserver/timelineserver/proxyserver PIDFILE (affect start failed).
3. Add yarn federation router server support.
4. Support YARN new web ui.
5. Support for hdfs router.
> BIGTOP-3456: Add hadoop-yarn-router and hadoop-hdfs-dfsrouter to hadoop services

- bigtop-packages/src/common/hive/patch6-HIVE-19231.diff
- bigtop.bom
This patch is contained in Hive 3.x, but not in the Hive 2.x branch. It
leads to subtle errors when executing Hive via Python or systemd, and
having it fixed in the 1.5 branch would allow people to rebuild their
packages if needed (we could update the docs about it).
> BIGTOP-3515 - Backport HIVE-19231

- bigtop-packages/src/deb/hive/rules
- bigtop-packages/src/rpm/hive/SPECS/hive.spec
https://issues.apache.org/jira/browse/BIGTOP-3516
> BIGTOP-3516. Remove dead HBase jar link for Hive.

- bigtop-packages/src/common/livy/patch1-LIVY-756.diff
- bigtop.bom
https://issues.apache.org/jira/browse/BIGTOP-3517
> BIGTOP-3517. Bump Livy to 0.7.1.

- provisioner/docker/config_ubuntu-20.04.yaml
https://issues.apache.org/jira/browse/BIGTOP-3492
I added a config yaml for Ubuntu 20.04 for testing purpose.
The repo URL in that file is not valid until v3.0.0 is released and its repo is published on S3, so users have to override it with some existent (dummy) URL for now. For example, if you want to test locally built packages, try the following command:
```
$ ./docker-hadoop.sh -d -k zookeeper -s zookeeper -r 'http://repos.bigtop.apache.org/releases/1.5.0/ubuntu/18.04/$(ARCH)' -L -C config_ubuntu-20.04.yaml -c 1
```
> BIGTOP-3492. Add Ubuntu 20.04 support to the Docker provisioner.

- bigtop-packages/src/common/hadoop/patch7-remove-phantomjs-in-yarn-ui.diff
Haoop Yarn-UI depends on phantomjs (optional) while there is
not prebuilt binary other than x86 platform. And this will
cause hadoop build failure as yarn-ui has been enabled by BIGTOP-3456.
Change-Id: I10d034d3172787f9667d53d44b1663a04c9fdf93
> BIGTOP-3526: Remove phantomjs dependency from yarn-ui

- bigtop-packages/src/deb/gpdb/rules
- bigtop-packages/src/deb/hadoop/rules
- bigtop-packages/src/deb/phoenix/rules
According to
https://lintian.debian.org/tags/debian-rules-calls-pwd.html,
CURDIR is the preferred way in a makefile (like rules) to refer to the
current directory. For some reason I got building failures when running
a Debian 10 bigtop docker imagei and trying to build the hadoop pkg,
that got solved only applying this fix.
Applied the same fix to all the debian rules files with ${PWD}.
> BIGTOP-3527: replace ${PWD} with ${CURDIR} in debian rules files

- bigtop-packages/src/common/hive/do-component-build
- bigtop-packages/src/common/oozie/install_oozie.sh
- bigtop-packages/src/common/oozie/oozie-env.sh
- bigtop-packages/src/common/oozie/oozie.init
- bigtop-packages/src/common/oozie/patch0-hadoop322-hive312.diff
- bigtop-packages/src/deb/oozie/rules
- bigtop-packages/src/rpm/oozie/SPECS/oozie.spec
https://issues.apache.org/jira/browse/BIGTOP-3531
I needed lots of fix than I expected just make oozie-server run.
* fixed layout based on the expectation of scripts under /usr/lib/oozie/bin.
* made /usr/lib/oozie/lib symlink to embedded-oozie-server/webapp/WEB-INF/lib.
* set guava version to 27.0-jre.
* set JETTY_PID_FILE  to /var/run/oozie/oozie.pid.
* fixed /etc/init.d/oozie.
* excluded log4j2 from transitive dependencies of hive3 artifacts.
Let me address smoke-tests issue on [BIGTOP-3532](https://issues.apache.org/jira/browse/BIGTOP-3532) after this is merged.
> BIGTOP-3531. Fix packaging of Oozie 5.2.1.

- bigtop-packages/src/common/hadoop/patch8-HADOOP-17569.diff
https://issues.apache.org/jira/browse/BIGTOP-3536
We need apply the patch of (HADOOP-17569)[https://issues.apache.org/jira/browse/HADOOP-17569] to fix build failure of Hadoop on Fedora 33.
> BIGTOP-3536. Fix build failure of Hadoop on Fedora 33.

- bigtop-tests/test-artifacts/oozie/src/main/groovy/org/apache/bigtop/itest/ooziesmoke/TestOozieSmoke.groovy
https://issues.apache.org/jira/browse/BIGTOP-3532 
This patch depends on #763.
> BIGTOP-3532. Fix smoke-tests for Oozie 5.2.1.

- bigtop_toolchain/manifests/packages.pp
https://issues.apache.org/jira/browse/BIGTOP-3535
Current Bigtop 1.5.0 build env does not have [zstd compression](https://github.com/facebook/zstd) headers so the Hadoop Native Library that's built does not support `zstd`:
```
$ hadoop checknative -a
21/04/13 23:18:20 INFO bzip2.Bzip2Factory: Successfully loaded & initialized native-bzip2 library system-native
21/04/13 23:18:20 INFO zlib.ZlibFactory: Successfully loaded & initialized native-zlib library
Native library checking:
hadoop:  true /usr/lib/hadoop/lib/native/libhadoop.so.1.0.0
zlib:    true /lib/x86_64-linux-gnu/libz.so.1
snappy:  true /usr/lib/hadoop/lib/native/libsnappy.so.1
zstd  :  false
lz4:     true revision:10301
bzip2:   true /lib/x86_64-linux-gnu/libbz2.so.1
openssl: true /usr/lib/x86_64-linux-gnu/libcrypto.so
21/04/13 …
```
> BIGTOP-3535: Add zstd compression headers to add native lib support

- bigtop_toolchain/bin/puppetize.sh
https://issues.apache.org/jira/browse/BIGTOP-3537
> BIGTOP-3537. Fix puppetize.sh to work with the latest CentOS 8 Docker image.

- bigtop_toolchain/manifests/packages.pp
https://issues.apache.org/jira/browse/BIGTOP-3537
> BIGTOP-3537. Fix puppetize.sh to work with the latest CentOS 8 Docker image (addendum).

- bigtop.bom
https://issues.apache.org/jira/browse/BIGTOP-3539
> BIGTOP-3539. Building bigtop-groovy fails on all distros and platforms.

- bigtop-packages/src/common/gpdb/do-component-configure
https://issues.apache.org/jira/browse/BIGTOP-3538
This PR contains the following fixes so as to satisfy recent stricter compiler:
* Backport https://github.com/greenplum-db/gpdb/pull/10663
* Remove duplicate variable declarations
Tested on all distros we support using an x86_64 machine.
> BIGTOP-3538. Building GPDB fails on Fedora 33.

- bigtop-tests/smoke-tests/odpi-runtime/build.gradle
https://issues.apache.org/jira/browse/BIGTOP-3541
This was probably because https://conjars.org/repo/ stopped providing jars.
To avoid the issue, change the maven repository url from https://conjars.org/repo/ to https://public.nexus.pentaho.org/repository/proxy-public-3rd-party-release
Apache Beam had the same kinds of issue, and they switched to the pentaho's own repository.
https://issues.apache.org/jira/browse/BEAM-11689
> BIGTOP-3541: Smoke test on odpi-runtime failed

- bigtop-packages/src/common/ambari/patch2-AMBARI-phantomjs.diff
After ambari is bumped to 2.7.5, it cannot build on non-x86
platforms as phantomjs prebuilt is required.
This patch disables phantomjs reference as it is only used
for testing.
Change-Id: Ie23eae41441b201b31d6ed652ac203211b9482a7
> BIGTOP-3551: Phantomjs caused Ambari build failure on non-x86

- bigtop-packages/src/rpm/ambari/SPECS/ambari.spec
https://issues.apache.org/jira/browse/BIGTOP-3552
smoke-tests of ambari succeeded on CentOS 7:
```
$ ./docker-hadoop.sh \
--create 1 \
--image bigtop/puppet:trunk-centos-7 \
--memory 16g \
--repo file:///bigtop-home/output \
--disable-gpg-check \
--stack bigtop-utils,ambari \
--smoke-tests ambari
...
Now testing...
:bigtop-tests:smoke-tests:ambari:test (Thread[Execution worker for ':' Thread 2,5,main]) completed. Took 1.745 secs.
BUILD SUCCESSFUL in 52s
35 actionable tasks: 7 executed, 28 up-to-date
Stopped 1 worker daemon(s).
+ rm -rf buildSrc/build/test-results/binary
+ rm -rf /bigtop-home/.gradle
```
It seems not to work on CentOS 8. I filed [BIGTOP-3553](https://issues.apache.org/jira/browse/BIGTOP-3553) for that.
> BIGTOP-3552. Add missing files to ambari-agent RPM.

- bigtop_toolchain/manifests/renv.pp
https://issues.apache.org/jira/browse/BIGTOP-3540
Currently, `./gradlew toolchain` succeeds silently even if it fails to install R libraries.
With this PR, users can get aware of that failure from the message as follows (manually edited renv.pp for testing purpose, to specify non-existent package):
```
Debug: Exec[install_r_packages](provider=posix): Executing '/usr/bin/R -e 'pkgs <- c("foo"); install.packages(pkgs, repo="http://cran.r-project.org/"); for (pkg in pkgs[pkgs != "devtools"]) if (!library(pkg, character.only=TRUE, logical.return=TRUE)) q(save="no", status=1)''
Debug: Executing '/usr/bin/R -e 'pkgs <- c("foo"); install.packages(pkgs, repo="http://cran.r-project.org/"); for (pkg in pkgs[pkgs != "devtools"]) if (!library(pkg, character.only=TRUE, logical.return=TRUE)) …
```
> BIGTOP-3540. Fix toolchain to abort if R installation failed.

- bigtop-deploy/puppet/modules/gpdb/manifests/init.pp
https://issues.apache.org/jira/browse/BIGTOP-3559
> BIGTOP-3559. Fix the download URL for pip2 in the GPDB deployment manifest.

- bigtop-packages/src/common/hbase/do-component-build
- bigtop_toolchain/files/protoc-3.5.1-add-support-for-ppc64le.patch
- bigtop_toolchain/manifests/protobuf.pp
https://issues.apache.org/jira/browse/BIGTOP-3558
ppc64le binary of protoc 3.5.1-1 is not available in maven repositories. Creating artifact from locally installed protobuf-3.5.1.1 should be fix. same as done on #785 and #786 .
**I did not test this on my local since I don't have ppc64le environment now.**
The same fix with replacement of `s/ppc64le/aarch64/g` worked on CentOS 7 aarch64.
> BIGTOP-3558. Fix build failure of HBase on ppc64le.

- bigtop-packages/src/common/logstash/do-component-build
https://issues.apache.org/jira/browse/BIGTOP-3562
> BIGTOP-3562. Building Logstash is failing due to the unavailability of keyserver.

- bigtop_toolchain/manifests/packages.pp
https://issues.apache.org/jira/browse/BIGTOP-3563
The latest cmake does not work without latest libarchive.
```
$ rpm -q cmake
cmake-3.18.2-9.el8.x86_64
$ cmake --version
cmake: symbol lookup error: cmake: undefined symbol: archive_write_add_filter_zstd
Updating libarhcive fixed the issue.
$ rpm -q libarchive
libarchive-3.3.2-8.el8_1.x86_64
$ sudo dnf update -y libarchive
$ rpm -q libarchive
libarchive-3.3.3-1.el8.x86_64
$ cmake --version
cmake version 3.18.2
CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
> BIGTOP-3563. Building Hadoop for CentOS 8 fails due to cmake error.

- bigtop-packages/src/common/flink/do-component-build
https://issues.apache.org/jira/browse/BIGTOP-3564
Build fails due to error related to node.js.
```
Running 'npm ci --cache-max=0 --no-save' in /bigtop/build/flink/rpm/BUILD/flink-1.11.3/flink-runtime-web/web-dashboard
/bigtop/build/flink/rpm/BUILD/flink-1.11.3/flink-runtime-web/web-dashboard/node/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /bigtop/build/flink/rpm/BUILD/flink-1.11.3/flink-runtime-web/web-dashboard/node/node)
```
https://github.com/eirslett/frontend-maven-plugin/issues/852 reported that using v.12 node.js fixed similar issue.
**I did not test this on ppc64le.**
> BIGTOP-3564. Fix build failure of Flink on Cent OS 7 ppc64le.

- bigtop-packages/src/common/alluxio/do-component-build
https://issues.apache.org/jira/browse/BIGTOP-3565
```
[INFO] Running 'npm install --production --no-save --no-package-lock --no-shrinkwrap' in /bigtop/build/alluxio/rpm/BUILD/alluxio-2.4.1/webui
[ERROR] /bigtop/build/alluxio/rpm/BUILD/alluxio-2.4.1/webui/node/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /bigtop/build/alluxio/rpm/BUILD/alluxio-2.4.1/webui/node/node)
```
Upgrading node.js to 12 same as done for https://github.com/apache/bigtop/pull/793 should be the fix. We need to upgrade npm too to the version supporting node 12 here.
> BIGTOP-3565. Fix build failure of Alluxio on Cent OS 7 ppc64le.

- bigtop-packages/src/common/zeppelin/patch0-ZEPPELIN-5451.diff
https://issues.apache.org/jira/browse/BIGTOP-3567
> BIGTOP-3567. Building Zeppelin fails due to the dependency downloading problem.

- bigtop-packages/src/rpm/ambari/SPECS/ambari.spec
Find correct python version path to create soft links for
resource_management and jinja.
> BIGTOP-3568: Fix Ambari-2.7.5 RPM installation issues

- bigtop-deploy/puppet/modules/gpdb/manifests/init.pp
Addendum PR for https://issues.apache.org/jira/browse/BIGTOP-3569. See https://github.com/apache/bigtop/pull/797#issuecomment-877890859 for details.
> BIGTOP-3569. Applying GPDB Puppet manifest fails on arm64 (addendum).

- bigtop-deploy/puppet/modules/flink/manifests/init.pp
https://issues.apache.org/jira/browse/BIGTOP-3571
> BIGTOP-3571. Ensure Hadoop and Flink are deployed in the correct order.

- bigtop-packages/src/common/tez/patch1-snappy-java-dependency.diff
https://issues.apache.org/jira/browse/BIGTOP-3573
Tez implicitly depends on snappy-java-1.0.5 which does not support aarch64. The dependency on snappy-java seems to be pulled from Avro. Adding explicit dependency on upstream snappy-java should address issues on aarch64.
https://github.com/apache/tez/blob/rel/release-0.10.0/tez-api/src/main/java/org/apache/tez/common/TezUtils.java#L44-L45
```
$ mvn dependency:tree -Dhadoop.version=3.2.2
...
[INFO] org.apache.tez:tez-api:jar:0.10.0
...
[INFO] +- org.apache.hadoop:hadoop-common:jar:3.2.2:compile
...
[INFO] |  +- org.apache.avro:avro:jar:1.7.7:compile
[INFO] |  |  +- com.thoughtworks.paranamer:paranamer:jar:2.3:compile
[INFO] |  |  \- org.xerial.snappy:snappy-java:jar:1.0.5:compile
...
```
> BIGTOP-3573. Tez smoke test fails on the ARM platform.

- bigtop-packages/src/common/hive/patch6-HIVE-21777.diff
https://issues.apache.org/jira/browse/BIGTOP-3575
> BIGTOP-3575. Fix Hive rpm build warning due to missing dependency.

- bigtop-packages/src/common/ambari/patch6-support-fedora-ppc.diff
https://issues.apache.org/jira/browse/BIGTOP-3576
> BIGTOP-3576. Deploying Ambari to Fedora 33 fails on ppc64le.

- bigtop-packages/src/common/logstash/patch2-pin-logstash-output-elasticsearch.diff
https://issues.apache.org/jira/browse/BIGTOP-3582
I found that logstash package successfully built on my local (Ubuntu) environment contains logstash-output-elasticsearch-11.0.2-java. Pinning the version to 11.0.2 could be quick fix.
```
$ dpkg -c output/logstash/logstash_5.4.1-1_all.deb | grep logstash-output-elasticsearch | head -n 1
drwxr-xr-x root/root         0 2021-06-27 01:28 ./usr/lib/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-11.0.2-java/
```
> BIGTOP-3582. Logstash RPM Build Fails.

- bigtop-packages/src/common/ambari/patch7-exclude-glassfish-javax.diff
https://issues.apache.org/jira/browse/BIGTOP-3584
```
[ERROR] Failed to execute goal on project ambari-metrics-timelineservice: Could not resolve dependencies for project org.apache.ambari:ambari-metrics-timelineservice:jar:2.7.5.0.0: Failed to collect dependencies at org.apache.phoenix:phoenix-core:jar:5.0.0-HBase-2.0 -> org.apache.hbase:hbase-mapreduce:jar:2.0.0 -> org.apache.hbase:hbase-server:jar:2.0.0 -> org.glassfish.web:javax.servlet.jsp:jar:2.3.2 -> org.glassfish:javax.el:jar:3.0.1-b06-SNAPSHOT: Failed to read artifact descriptor for org.glassfish:javax.el:jar:3.0.1-b06-SNAPSHOT: Could not transfer artifact org.glassfish:javax.el:pom:3.0.1-b06-SNAPSHOT from/to apache-hadoop (https://repo.hortonworks.com/content/groups/public/): Transfer failed for …
```
> BIGTOP-3584. Fix build failure of Ambari due to missing dependency on javax.el.

- bigtop-packages/src/common/ambari/patch8-stack-hooks.diff
The patch is related to PR #824.
It removed Ambari stack-select tool dependency from stack hooks when deploying mpack services.
> BIGTOP-3592: Remove Ambari stack-select tool dependency from stack hooks

- bigtop_toolchain/bin/puppetize.sh
- bigtop_toolchain/manifests/packages.pp
Built locally:
```
bigtop/slaves   trunk-debian-11     16fa6cdec6a7   7 minutes ago       3.89GB
bigtop/puppet  trunk-debian-11     f2fb226b4e3c   2 hours ago         330MB
```
> BIGTOP-3600 - Add Debian 11 support to the Docker provisioner

- bigtop-packages/src/common/hadoop/patch11-YARN-9783.diff
https://issues.apache.org/jira/browse/BIGTOP-3597
Backporting [YARN-9783](https://issues.apache.org/jira/browse/YARN-9783) fixes the issue.
While this is a follow-up of https://github.com/apache/bigtop/pull/827, merging this first should be harmless.
> BIGTOP-3597. Fix build failure of Hadoop 3.2 against ZooKeeper 3.5.

- bigtop_toolchain/manifests/packages.pp
In https://github.com/apache/bigtop/pull/829 I caused some
failures in gpdb package builds, since python2.7-dev
dependencies are needed.
On Debian 9/10/11 python3-dev and python2.7-dev are available,
so better to be explicit and install both at the same time.
> BIGTOP-3600 - Deploy python*-dev deps on Debian images

- bigtop_toolchain/manifests/ant.pp
- bigtop_toolchain/manifests/groovy.pp
- bigtop_toolchain/manifests/maven.pp
- bigtop_toolchain/manifests/packages.pp
Due to https://access.redhat.com/articles/6338021 ant and  maven classes
fail to download due to TLS certificate expiration check issues.
Since the issue is related to CentOS 7 and earlier, it seems sensible
to force the upgrade of the ca-certificates package (that in its latest
versions contain a fix).
While at it:
1) Add a specific dependency to 'ca-certificates' for CentOS 7.
2) Require bigtop_toolchain::packages in the varios ant/maven/groovy
classes, so that we'll be able to rely on packages being
installed when running the Execs. It may not be strictly required
now but it seems good for future code.
3) Refactor a bit the Execs to be more readable when puppet runs
(easier to track what's happening).
Tested rebuilding the puppet image and the slave image.
> BIGTOP-3309 - Update ca-certificates for CentOS 7

- bigtop-packages/src/deb/hadoop/rules
- bigtop-packages/src/rpm/hadoop/SPECS/hadoop.spec
The new Zookeeper 3.5.x dependency seems to have brought a new
zookeeper jar under the lib directory, namely zookeeper-jute-3.5.9.jar.
In our rpm/deb packaging code we create a symlink to
the zookeeper-x.x.x.jar assuming (afaics) that no other zookeeper-*
library is around, and this currently breaks our builds.
This change adds a stricter match for the jar to link, and it works
with debian-10/centos-8 x86 builds (from my tests).
> BIGTOP-3610 - Use a stricter match for the zookeeper jar in hadoop packaging

- bigtop-packages/src/common/hive/patch7-HIVE-22278-branch-3.1.diff
- bigtop-packages/src/common/hive/patch8-HIVE-25795-branch-3.1.diff
- bigtop-packages/src/common/hive/patch9-log4j2-2.16.0.diff
- bigtop.bom
https://issues.apache.org/jira/browse/BIGTOP-3615
HIVE-25795 upgraded log4j2 to 2.15.0 for CVE-2021-44228. We need the patch of HIVE-22278 too for Hive 3.1.2.
> BIGTOP-3615. Upgrade log4j2 of Hive 3.1.2 to 2.16.0.

- bigtop.bom
https://issues.apache.org/jira/browse/BIGTOP-3616
Bump Flink to 1.11.6 addressing CVE-2021-44228.
> BIGTOP-3616. Bump Flink to 1.11.6.

- bigtop-packages/src/common/hive/patch7-log4j2-2.16.0.diff
- bigtop.bom
This commit is based on the work done in BIGTOP-3615
for Hive 3.x. In HIVE-25795 there seem to be no
indication that upstream wants to fix branch-2.3 too,
so this change should be enough for the moment to secure
Hive users of Bigtop 1.5.
Caveats:
- The Hive branch-2.3 is now at version 2.3.10 (in development),
that is far from our 2.3.6. I don't think it is needed to bump
Hive to 2.3.9/10 at the moment, but it can be discussed.
> BIGTOP-3619 - Upgrade hive 2.3.6 to log4j 2.17.0

- bigtop.bom
https://issues.apache.org/jira/browse/BIGTOP-3599
Phoenix 5.1.0 has compilation error against HBase 2.4.8. Upgrading to Phoenix 5.1.2 should fix this.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project phoenix-core: Compilation failure: Compilation failure:
[ERROR] /home/fedora/srcs/bigtop/build/phoenix/rpm/BUILD/phoenix-5.1.0/phoenix-core/src/main/java/org/apache/phoenix/mapreduce/MultiHfileOutputFormat.java:[262,69] cannot find symbol
[ERROR]   symbol:   method getBytesPerChecksum(org.apache.hadoop.conf.Configuration)
[ERROR]   location: class org.apache.hadoop.hbase.regionserver.HStore
[ERROR] /home/fedora/srcs/bigtop/build/phoenix/rpm/BUILD/phoenix-5.1.0/phoenix-core/src/main/java/org/apache/phoenix/mapreduce/Mul …
```
> BIGTOP-3599. Bump Phoenix to 5.1.2.

- bigtop-packages/src/common/solr/do-component-build
- bigtop.bom
https://issues.apache.org/jira/browse/BIGTOP-3618
* Bump Solr 8.11.1 addressing CVE-2021-44228 was released.
* [SOLR-14981](https://issues.apache.org/jira/browse/SOLR-14981) removed contrib/clustering. We need to fix do-component-build for this.
> BIGTOP-3618. Bump Solr to 8.11.1.

- bigtop-packages/src/deb/oozie/rules
The only remaining one is the Oozie's rules file.
> BIGTOP-3622: replace $(PWD) with $(CURDIR) in Debian rule files

- bigtop-packages/src/deb/oozie/rules
- bigtop.bom
This pull request bumps the bigtop.bom's release number for
the Oozie package. In order to pull the right log4j dependencies,
the package needs to be built after the Hive one, reusing
the maven cache (like `./gradlew hive-pkg oozie-pkg`).
Also include a fix for the Oozie's Debian rules file, to fix BIGTOP-3622.
> BIGTOP-3621: Bump Oozie's log4j dependencies to 2.17.0

- bigtop-packages/src/common/alluxio/do-component-build
https://issues.apache.org/jira/browse/BIGTOP-3589
`./gradlew alluxio-pkg` fails on non-Git source tree since buildnumber-maven-plugin invokes git command to get scm revision number. 
```
[INFO] --- buildnumber-maven-plugin:1.4:create-metadata (default) @ alluxio-core-common ---
[INFO] Executing: /bin/sh -c cd '/home/centos/srcs/bigtop-3.0.0/build/alluxio/rpm/BUILD/alluxio-2.4.1/core/common' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /home/centos/srcs/bigtop-3.0.0/build/alluxio/rpm/BUILD/alluxio-2.4.1/core/common
...
[INFO] Alluxio Core - Common Utilities 2.4.1 .............. FAILURE [01:00 min]
...
[ERROR] Failed to execute goal org.codehaus.mojo:buildnumber-maven-plugin:1.4:create-metadata (default) on project alluxio-core-common: Execution default of goal …
```
> BIGTOP-3589. Fix build failure of Alluxio caused by buildnumber-maven-plugin.

- bigtop-packages/src/common/ycsb/patch1-log4j.diff
- bigtop.bom
At the time of writing upstream didn't release any official fix,
but https://github.com/brianfrankcooper/YCSB/pull/1583 seems
taking care of it.
Credits for the upstream fix: Filipe Oliveira \<filipecosta.90@gmail.com\>
> BIGTOP-3626: Upgrade log4j dependencies for ycsb

- bigtop_toolchain/manifests/puppet_modules.pp
When I deploy components according to the Readme doc, I find an error occur
Then, I find such a issue to discribe it
https://issues.apache.org/jira/browse/BIGTOP-3088
The issue has been fixed, but the doc haven't updated, so I make this commit to fix the gap.
> BIGTOP-3627. Pinning the version of puppetlabs-stdlib

- bigtop-packages/src/common/ycsb/patch1-log4j.diff
- bigtop.bom
At the time of writing upstream didn't release any official fix
for the lo4j CVEs, but brianfrankcooper/YCSB#1583 seems taking care of it.
Credits for the upstream fix: Filipe Oliveira <filipecosta.90@gmail.com>
This change also bumps ycsb to its latest upstream, to allow the log4j
patch to be applied cleanly.
> BIGTOP-3626: Upgrade ycsb and its log4j dependencies

- provisioner/docker/README.md
- provisioner/docker/docker-compose-cgroupv2.yml
- provisioner/docker/docker-hadoop.sh
This is a simple change to allow docker-compose to use a different
config file when creating instances. This is useful when testing
new settings and also to keep multiple versions of docker-compose.yml
(if the same version cannot be re-used across multiple OS etc..).
For example, from my recent tests the actual docker-compose.yml
config seems not to work with cgroup v2 and systemd on Debian 10/11.
> BIGTOP-3614: allow to change the docker-compose cfg in the provisioner

- bigtop-packages/src/common/elasticsearch/patch0-log4j2-2.17.0.diff
- bigtop-packages/src/rpm/elasticsearch/SPECS/elasticsearch.spec
- bigtop.bom
Update log4j2 version to 2.17.0 to keep up the issue https://issues.apache.org/jira/browse/BIGTOP-3613.
Tested by 
- `./gradlew elasticsearch-pkg` for bigtop
- `./gradlew precommit` on patched elasticsearch's source (cf. [TESTING.asciidoc](https://github.com/elastic/elasticsearch/blob/5.6/TESTING.asciidoc#running-verification-tasks))
> BIGTOP-3632: Bump elasticsearch's log4j dependencies to 2.17.0

- bigtop-packages/src/common/logstash/patch3-log4j2-2.17.0.diff
- bigtop.bom
Update log4j2 version to 2.17.0 to keep up the issue https://issues.apache.org/jira/browse/BIGTOP-3613.
This PR omits default plugins
- logstash-input-http
- logstash-input-log4j
- logstash-input-kafka
- logstash-input-beats
- logstash-output-kafka
that includes older versions of log4j.
Those plugins do not seem to be maintained now so I would rather remove them than make efforts to path those plugins.
> BIGTOP-3635: Bump logstash's log4j dependencies to 2.17.0

- bigtop-deploy/puppet/manifests/jdk.pp
- bigtop_toolchain/bin/puppetize.sh
- docker/bigtop-slaves/build.sh
- provisioner/docker/docker-hadoop.sh
https://issues.apache.org/jira/browse/BIGTOP-3637
CentOS 8 reached End Of Life (EOL) on December 31st, 2021.
We need to update bigtop_toolchain first based on rocky facts.
```
$ sudo bigtop_toolchain/bin/puppetize.sh 
Unsupported OS rocky-8.5.
```
```
$ cat /etc/os-release 
NAME="Rocky Linux"
VERSION="8.5 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.5 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8.5:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
```
```
$ facter --show-legacy | grep operatingsystem
operatingsystem => RedHat
operatingsystemmajrelease => 8
operatingsystemrelease => …
```
> BIGTOP-3637. Add Rocky Linux 8 support.

- bigtop-packages/src/common/hive/patch9-log4j2-2.17.1.diff
- bigtop.bom
Upgrade hive's log4j2 version to 2.17.1 for Bigtop 3.0.x.
cf. Bigtop 1.5 has already been patched by
https://issues.apache.org/jira/browse/BIGTOP-3619 / https://github.com/apache/bigtop/pull/844 
```
./gradlew hive-pkg-ind
./gradlew docker-provisioner -Pstack="hive" -Psmoke_tests="hive"
```
> BIGTOP-3640: Upgrade hive's log4j2 version to 2.17.1 for Bigtop 3.0.x

- bigtop-packages/src/common/alluxio/patch1-BIGTOP-3634-log4j.diff
- bigtop-packages/src/common/elasticsearch/patch0-log4j2-2.17.1.diff
- bigtop-packages/src/common/flink/patch0-FLINK-25472.diff
- bigtop-packages/src/common/hive/patch9-log4j2-2.17.1.diff
- bigtop-packages/src/common/logstash/patch3-log4j2-2.17.1.diff
- bigtop-packages/src/common/solr/patch0-SOLR-15871.diff
- bigtop-packages/src/common/ycsb/patch1-log4j.diff
This PR upgrades log4j to 2.17.1 for Alluxio, Elasticsearch, Flink, Hive, Logstash, Solr, and YCSB.
Built the components above with this patch and ensured they succeeded.
> BIGTOP-3642. Upgrade log4j to 2.17.1 on all components.

- build.gradle
- packages.gradle
This change bumps up the version of the de.undercouch.download
Gradle download plugin to add the `retries` parameter to the
download function used to retrieve upstream artifacts.
The bump from 3.x to 4.x should be supported, afaics, from our
current setup:
https://github.com/michel-kraemer/gradle-download-task#migrating-from-version-3x-to-4x
>  BIGTOP-3644: Improve Gradle download resiliency

- build.gradle
- packages.gradle
Upgrade the usage example on the task description, from fedora 26, 31 to 33, the version which Bigtop 3.0 supports.
Check by 
```
./gradlew tasks|grep fedora-26  
./gradlew tasks|grep fedora-31
./gradlew tasks|grep fedora-33
```
> [BIGTOP-3645] upgrade fedora version to 33 in gradle files

- bigtop-packages/src/common/ycsb/patch1-log4j.diff
This PR upgrades the version of Geode and TableStore SDK so that YCSB doesn't have the jar files which have the Log4Shell vulnerabilities.
I built YCSB with this PR on CentOS 7 and confirmed that there was no log4j2 jar file before 2.17.1 in the generated package.
> BIGTOP-3646. Upgrade Geode and TableStore SDK version for YCSB.

- bigtop_toolchain/bin/puppetize.sh
Creating the bigtop-puppet image of CentOS 8 fails for now because it's already EOL'd.
This PR changes the RPM repository for CentOS 8 to fix it.
I locally confirmed that running `./build.sh 3.0.1-centos-8` with this PR in docker/bigtop-puppet succeeded.
> BIGTOP-3647. Change RPM repository for CentOS 8 to Vault Mirror.

- bigtop-deploy/puppet/hieradata/bigtop/repo.yaml
- bigtop-packages/src/common/ambari/patch5-AMBARI-25599.diff
- bigtop_toolchain/lib/puppet/parser/functions/latest_ant_binary.rb
- bigtop_toolchain/lib/puppet/parser/functions/latest_maven_binary.rb
- bigtop_toolchain/manifests/ant.pp
- bigtop_toolchain/manifests/maven.pp
During installing toolchain, Ant and Maven is downloaded from downloads.apache.org.
But requesting to that site too many times causes IP ban, so this PR replaces it with dlcdn.apache.org,
which isn't supposed to have such a limitation.
I confirmed that `./gradlew toolchain` succeeded with this PR on the node in question, which was still banned from the ASF site.
Also, building and testing Ambari with this PR succeeded as before on another node, which was not blacklisted.
> BIGTOP-3648. Change download site to dlcdn.apache.org for installing Ant and Maven.

- bigtop_toolchain/manifests/packages.pp
This PR adds the python-is-python2 package to the Docker image for Ubuntu 20.04 so that building Ambari succeeds.
Tested on Ubuntu 20.04 and 18.04 (for regression).
> BIGTOP-3652. Add the python-is-python2 package to the toolchain for Ubuntu 20.04.

- bigtop-packages/src/common/kibana/do-component-build
This PR fixes Kibana's build error caused by the following change of GitHub.
https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git
Ran `./gradlew allclean kibana-pkg-ind` locally and confirmed it succeeded.
> BIGTOP-3653. Building Kibana fails due to the npm error.

- bigtop-packages/src/common/hadoop/do-component-build
This PR fixes Hadoop build failure on ppc64le caused by accessing GitHub via prohibited protocol.
Not tested, since it's a slight and obvious fix. We can test it on the CI environment after merging.
> BIGTOP-3654. Building Hadoop fails on ppc64le.

- bigtop-packages/src/rpm/ambari/SPECS/ambari.spec
Currently, Ambari fails to deploy a cluster on CentOS due to the lack of execute permission on the bootstrap script. This PR adds the required permission to it.
I deployed a single node cluster on CentOS 7 via Ambari which was built with this PR.
> BIGTOP-3655. Cluster deployment via Ambari fails on CentOS due to the lack of execute permission.

- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/repos/repoinfo.xml
- bigtop-packages/src/deb/bigtop-ambari-mpack/source/include-binaries
Hi,
with these commits i got the .deb for bigtop-ambari-mpack to build and i could install the mpack components in ambari
> Ambari Mpack fixes for debian/ubuntu

- bigtop-packages/src/common/alluxio/do-component-build
This is a follow-up for #861. Building Alluxio for Debian or Ubuntu fails on a ppc64le machine because fakeroot tries to use the root user's home directory instead of jenkins' to create local maven repository for some reason. This PR avoids this problem by leveraging the maven.repo.local property passed from bigtop-packages/src/deb/alluxio/rules.
Ran `./gradlew allclean alluxio-pkg` in a ubuntu-18.04 container on a ppc64le machine and confirmed it succeeced.
> BIGTOP-3639. Alluxio build fails on ppc64le (addendum).

- bigtop-packages/src/common/ambari/patch5-AMBARI-25599.diff
We change the ASF download site to dlcdn.apache.org in BIGTOP-3648 for avoiding IP ban,
but the old version of Phoenix seems to be removed from that site and it causes build failures.
This PR fixes the problem above.
I confirmed the replaced link was alive via browser.
> BIGTOP-3657. Revert the download site to archive.apache.org partially

- bigtop-deploy/puppet/modules/ambari/manifests/init.pp
This PR fixes the Ambari deployment failure caused by the version mismatch of ODPi Mpack.
I confirmed that the following commands succeeded with this PR on x86_64 platform.
```
./docker-hadoop.sh -d -i bigtop/puppet:3.0.1-fedora-33 -r 'http://repos.bigtop.apache.org/releases/3.0.1/fedora/33/$basearch' -k bigtop-utils,ambari -s ambari -F docker-compose-cgroupv2.yml -c 1
```
```
./docker-hadoop.sh -d -i bigtop/puppet:3.0.1-ubuntu-20.04 -r 'http://repos.bigtop.apache.org/releases/3.0.1/ubuntu/20.04/$(ARCH)' -k bigtop-utils,ambari -s ambari -F docker-compose-cgroupv2.yml -c 1
```
> BIGTOP-3659. Ambari deployment fails due to the odpi-ambari-mpack version mismatch.

- bigtop-packages/src/common/hbase/do-component-build
- bigtop-packages/src/rpm/hbase/SPECS/hbase.spec
- bigtop.bom
https://issues.apache.org/jira/browse/BIGTOP-3662
HBase 2.4.11 was released. We can pick this low-hanging fruit for Bigtop 3.1.
> BIGTOP-3662. Bump HBase to 2.4.11.

- bigtop-packages/src/rpm/hadoop/SPECS/hadoop.spec
- provisioner/docker/docker-hadoop.sh
https://issues.apache.org/jira/browse/BIGTOP-3663
* We need to add `/etc/puppet/code/modules` to `--modulepath` for puppetlabs-stdlib.
* Both initscripts and initscripts-service are required.
> BIGTOP-3663. Hadoop deployment fails on Fedora 35.

- provisioner/docker/README.md
Add the statement and tell users that currently Fedora 35 provisioner is not stable.
None.
> BIGTOP-3665: specify Fedora 35 as experimental state

- packages.gradle
Add warn message to gradle when users try to build on fedora-35
run `./gradlew zookeeper-pkg-ind -POS=fedora-35` and check the message.
> BIGTOP-3664: Add warn message to gradle when users try to build on fedora-35

- provisioner/docker/README.md
- provisioner/docker/config_rockylinux-8.yaml
This PR will replace centos8 with rocky linux 8 on docker provisioner.
```
./docker-hadoop.sh \
--create 3 \
--memory 4g \
-C config_rockylinux-8.yaml \
-d  \
--stack hdfs,yarn,mapreduce \
--smoke-tests hdfs,yarn,mapreduce
```
> BIGTOP-3666: Replace the Docker provisioner config for CentOS 8 with Rocky 8

- bigtop_toolchain/bin/puppetize.sh
- bigtop_toolchain/manifests/ant.pp
- bigtop_toolchain/manifests/maven.pp
- bigtop_toolchain/manifests/protobuf.pp
- bigtop_toolchain/manifests/renv.pp
Use HTTPS instead of HTTP when building the images.
I was able to use the new Docker image to build HBase for CentOS 8 and Rocky 8.
> BIGTOP-3672: Always use HTTPS when accessing repos and not plain HTTP.

- bigtop_toolchain/files/0001-CVE-2021-22569-Improve-performance-of-parsing-unknow.patch
- bigtop_toolchain/manifests/protobuf.pp
https://issues.apache.org/jira/browse/BIGTOP-3671
https://github.com/protocolbuffers/protobuf/pull/9371 is the fix for vulnerability of protobuf-java. This PR adds backported patch for protobuf-2.5.0. Users can locally install patched protobuf-java from the source code set up by bigtop_toolchain (under /usr/src/protobuf-2.5.0/java) for their own build.
> BIGTOP-3671. Add a patch for CVE-2021-22569 to bigtop_toolchain.

- bigtop_toolchain/manifests/packages.pp
This PR is for addressing https://issues.apache.org/jira/browse/BIGTOP-3676.
Ran `./build.sh trunk-debian-11` in the docker/bigtop-slaves directory and confirmed it succeeded.
> BIGTOP-3676. Building Ambari for Debian 11 on ppc64le fails due to missing python.

- bigtop-packages/src/common/zeppelin/patch0-exclude-conflicting-packages.diff
This PR is for addressing [BIGTOP-3678](https://issues.apache.org/jira/browse/BIGTOP-3678).
Ran `./gradlew zeppelin-clean zeppelin-pkg` locally and ensured it succeeded.
> BIGTOP-3678. Building Zeppelin fails due to dependency convergence error.

- bigtop-packages/src/common/zeppelin/do-component-build
- bigtop_toolchain/manifests/grpc.pp
#896 upgraded the protobuf version to 3.17.3, so we have to use it to build gRPC and Zeppelin.
Confirmed that the followings succeeded on ppc64le:
* Building the toolchain image with this PR
* Building Alluxio and Zeppelin with that image
> BIGTOP-3677 (addendum). Building HBase for CentOS 7 on arm64 and ppc64le fails due to missing libraries.

- bigtop-packages/src/common/phoenix/do-component-build
https://issues.apache.org/jira/browse/BIGTOP-3679
protoc provided by org.openlabtesting.protobuf is not portable enough. We should use our own patched protoc.
> BIGTOP-3679. Building Phoenix for CentOS 7 fails on aarch64.

- bigtop-packages/src/common/hbase/do-component-build
To fix the smoke test failure on ppc64le, update the version of jruby on power pc.
No, I would like to ask the administrators to redo the test environment.
> BIGTOP-3680: Update jruby's version to fix the smoke test failure on ppc64le

- provisioner/docker/docker-compose-cgroupv2.yml
- provisioner/docker/docker-compose.yml
- provisioner/docker/docker-hadoop.sh
Currently docker-provisioner could not used in docker-compose v2.
This PR
- Add `services` level to docker-compose.yml.
Bigtop is still using deprecated format v1.
https://docs.docker.com/compose/compose-file/compose-versioning/#version-1-deprecated
(It is complicated, about yaml format, there are v1, v2, and v3, and v1 is now deprecated.)
By adding `services` level, we can use the provisioner both in v1 and v2.
- Fix provision_id's name.
docker-compose v2 seems case sensitive when using -p option.
Check that `./gradlew docker-provisioner` get succeeded in docker-compose `v1.29.2` and `v2.4.0`.
> BIGTOP-3685: make docker-provisioner to be used both in docker-compose v1 and v2

- bigtop-packages/src/common/spark/do-component-build
- bigtop-packages/src/deb/spark/spark-core.install
- bigtop-packages/src/rpm/spark/SPECS/spark.spec
Add kubernetes related libraries to spark package.
1. Check the libraries are included
```sh
$ ./gradlew spark-pkg 
$ rpm -qlp output/spark/noarch/spark-core-3.1.2-1.el7.noarch.rpm| grep kube
/usr/lib/spark/jars/kubernetes-client-4.12.0.jar
/usr/lib/spark/jars/kubernetes-model-admissionregistration-4.12.0.jar
...
/usr/lib/spark/kubernetes/tests/worker_memory_check.py
$ ./gradlew spark-pkg
dpkg -c output/spark/spark-core_3.1.2-1_all.deb |grep kube
-rw-r--r-- root/root    951167 2022-05-27 08:59 ./usr/lib/spark/jars/kubernetes-client-4.12.0.jar
-rw-r--r-- root/root    836222 2022-05-27 08:59 ./usr/lib/spark/jars/kubernetes-model-admissionregistration-4.12.0.jar
...
-rw-r--r-- root/root      1585 2022-05-27 08:59 ./usr/lib/spark/kubernetes/tests/worker_memory_check.py
```
2.  Check whether …
> BIGTOP-3687: Add kubernetes libraries and related files

- bigtop-packages/src/rpm/ambari/SPECS/ambari.spec
Duplicated deleting operation ('%files' and '%preun%') in Ambari RPM spec makes some warning issues when uninstalling Ambari rpm.
```
cp: cannot stat ‘/etc/ambari-server/conf’: No such file or directory
....
..
warning: file /etc/ambari-server/conf/metrics.properties: remove failed: No such file or directory
warning: file /etc/ambari-server/conf/log4j.properties: remove failed: No such file or directory
warning: file /etc/ambari-server/conf/krb5JAASLogin.conf: remove failed: No such file or directory
warning: file /etc/ambari-server/conf/ambari.properties: remove failed: No such file or directory
warning: file /etc/ambari-server/conf: remove failed: No such file or directory
.....
cp: cannot stat ‘/etc/ambari-agent/conf’: No such file or directory
warning: file …
```
> BIGTOP-3705: Refine the Ambari RPM spec to fix warning after rpm uninstallation

- bigtop-packages/src/common/zookeeper/do-component-build
- bigtop-packages/src/common/zookeeper/install_zookeeper.sh
- bigtop-packages/src/deb/zookeeper/rules
- bigtop-packages/src/rpm/zookeeper/SPECS/zookeeper.spec
https://issues.apache.org/jira/browse/BIGTOP-3669
There is no way to create binary tarball of zookeeper-rest. I used `mvn dependency:copy-dependencies` to collect dependencies on our own.
> BIGTOP-3669. Use maven instead of ant to build ZooKeeper.

- bigtop-packages/src/common/oozie/patch1-OOZIE-3628-001.diff
origin: https://issues.apache.org/jira/secure/attachment/13027125/OOZIE-3628-001.patch
Add a patch to fix oozie's build error with maven 3.8.
ref. https://issues.apache.org/jira/browse/OOZIE-3628
```sh
./gradlew oozie-pkg
```
I checked it succeeded on maven `3.8.4` and `3.6.3` on ubuntu20.04/amd64.
> BIGTOP-3694: Fix oozie's build error with maven 3.8

- provisioner/docker/config_centos-7.yaml
- provisioner/docker/config_debian-10.yaml
- provisioner/docker/config_debian-11.yaml
- provisioner/docker/config_rockylinux-8.yaml
- provisioner/docker/config_ubuntu-18.04.yaml
- provisioner/docker/config_ubuntu-20.04.yaml
Update the latest repo url of 3.1.0 release for provisioner docker Distros yamls.
> BIGTOP-3707: Update latest repo url for Provisioner docker yamls

- bigtop-packages/src/common/hbase/do-component-build
- bigtop_toolchain/files/0001-Backport-atomic-operations-with-support-of-arm64-and.patch
- bigtop_toolchain/files/0001-CVE-2021-22569-Improve-performance-of-parsing-unknow.patch
- bigtop_toolchain/manifests/protobuf.pp
https://issues.apache.org/jira/browse/BIGTOP-3709
We still need locally installed protobuf-2.5.0 removed by [BIGTOP-3438](https://issues.apache.org/jira/browse/BIGTOP-3438)(#915) for building HBase on aarch64 and ppc64le.
I used `/usr/local/protobuf-2.5.0` as new destination since `/usr/local` is the prefix of protobuf-3.7.1 now.
> BIGTOP-3709. Bring protobuf 2.5.0 back for building HBase on aarch64 and ppc64le.

- bigtop-packages/src/common/hadoop/patch0-exclude-netty-from-zookeeper.diff
- bigtop.bom
https://issues.apache.org/jira/browse/BIGTOP-3714
Multiple versions of Netty 4 jars are exists on classpath. This breaks http server of DataNode. Excluding Netty from transitive dependency of ZooKeeper should fix this.
> BIGTOP-3714. Fix error of DataNode httpserver due to conflicting dependency on Netty in branch-3.1.

- bigtop-tests/smoke-tests/kafka/TestKafkaSmoke.groovy
This PR adds read/write tests for an Kafka topic to improve the test coverage.
- Add a write test using `kafka-console-producer.sh`.
- Add a read test using `kafka-console-consumer.sh`. This test try to read the message written by the write test above.
```sh
./docker-hadoop.sh -d   -C config_ubuntu-20.04.yaml   --create 3   --memory 8g   --disable-gpg-check   --stack zookeeper,kafka   --smoke-tests kafka
```
> BIGTOP-3711: Add read/write smoke tests for Kafka

- bigtop-packages/src/common/ranger/do-component-build
- bigtop-packages/src/common/ranger/install_ranger.sh
- bigtop-packages/src/common/ranger/patch0-RANGER-3373.diff
- bigtop-packages/src/common/ranger/patch1-RANGER-3459.diff
- bigtop-packages/src/common/ranger/patch2-update-solr.diff
- bigtop-packages/src/rpm/ranger/SPECS/ranger.spec
- bigtop.bom
This PR is based on #326 submitted by @Xingwd (much appreciated!) and
includes the following updates:
* Upgrade Ranger version to 2.2.0
* Change the download site from ASF to GitHub, because the source
tarball distributed on the former is unnecessarily large
* Add package dependencies to bigtop.bom
* Remove the assembly:assembly target from the mvn command since it
doesn't work in recent releases
* Add the version info of other components to the mvn command
* Fix the lib paths in install_ranger.sh and the RPM spec file
* Add the #BIGTOP_PATCH_FILES and #BIGTOP_PATCH_COMMANDS comments to the
RPM spec so that the patches provided by Bigtop are applied during
building RPM
* Add patches for addressing RANGER-3373 and RANGER-3459
* Remove symlink to non-existent ojdbc6.jar in install_ranger.sh …
> BIGTOP-2971. RPM packaging for Ranger.

- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/YARN/package/scripts/service.py
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/YARN/package/scripts/status_params.py
The naming rule of Yarn/MapReduce historyserver PID file
is deprecated in Hadoop 3.x.
> BIGTOP-3716: Rename the Yarn/MapReduce historyserver PID file

- bigtop_toolchain/bin/puppetize.sh
Puppet RPM for CentOS 7 provided in EPEL was apparently removed. This PR is a workaround for it.
https://issues.apache.org/jira/browse/BIGTOP-3725
I locally ran `./build.sh trunk-centos-7` in docker/bigtop-puppet and then docker/bigtop-slaves, and confirmed both succeeded.
> BIGTOP-3725. Puppet 3 is removed from EPEL for CentOS 7.

- bigtop.bom
https://issues.apache.org/jira/browse/BIGTOP-3712
[BIGTOP-3669](https://issues.apache.org/jira/browse/BIGTOP-3669) and [BIGTOP-3712](https://issues.apache.org/jira/browse/BIGTOP-3712) updated the package contents of ZooKeeper and Kafka within the same version. Release number of them should be incremented.
> BIGTOP-3724. Increment the release number of ZooKeeper and Kafka.

- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/YARN/package/scripts/mapred_service_check.py
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/YARN/package/scripts/params_linux.py
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/YARN/package/scripts/params_windows.py
The patch is to fix the issues of checking MapReduce2 service and
"JAR does not exist".
> BIGTOP-3718: Fix MapReduce2 service-check in Amabri Mpack

- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/YARN/configuration-mapred/mapred-env.xml
Mapred configuration macros are deprected (HADOOP_MAPRED_ROOT_LOGGER,
HADOOP_JOB_HISTORYSERVER_OPTS, HADOOP_MAPRED_NICENESS, etc.).
Update them in Mpack aligned to
https://github.com/apache/hadoop/blob/trunk/hadoop-mapreduce-project/bin/mapred-config.sh#L38-L54
> BIGTOP-3717: Update MapReduce service configuration in Mpack

- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/properties/stack_features.json
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KAFKA/alert.json
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KAFKA/configuration/kafka-broker.xml
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KAFKA/configuration/kafka-env.xml
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KAFKA/configuration/kafka-log4j.xml
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KAFKA/configuration/kafka_client_jaas_conf.xml
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KAFKA/configuration/kafka_jaas_conf.xml
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KAFKA/kerberos.json
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KAFKA/metainfo.xml
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KAFKA/metrics.json
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KAFKA/package/scripts/kafka.py
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KAFKA/package/scripts/kafka_broker.py
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KAFKA/package/scripts/params.py
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KAFKA/package/scripts/service_check.py
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KAFKA/package/scripts/status_params.py
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KAFKA/package/scripts/upgrade.py
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KAFKA/package/scripts/utils.py
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KAFKA/package/templates/input.config-kafka.json.j2
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KAFKA/package/templates/kafka.conf.j2
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KAFKA/package/templates/kafka_client_jaas.conf.j2
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KAFKA/package/templates/kafka_jaas.conf.j2
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KAFKA/package/templates/tools-log4j.properties.j2
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KAFKA/role_command_order.json
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KAFKA/service_advisor.py
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KAFKA/themes/directories.json
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KAFKA/widgets.json
Add Kafka support for Bigtop 3.1.0 Mpack
Tested in CentOS7
> BIGTOP-3721: Add Kafka support for Bigtop 3.1.0 Mpack

- bigtop_toolchain/bin/puppetize.sh
Building Logstash fails on Rocky 8.
I add procps-ng package in puppetize.sh for install rvm command.
I tested two steps in my environment as follows...
1. Build docker images in local environment  both bigtop/slaves and bigtop/puppet.
2. Exec Logstash build task.
`./gradlew allclean logstash-pkg-ind -POS=rockylinux-8 -Pprefix=3.1.1`
3. Confirm job completon with "BUILD SUCCESSFUL" message.
> BIGTOP-3733. Building Logstash fails on Rocky 8

- bigtop-packages/src/common/zeppelin/patch3-exclude-conflicting-dependencies.diff
- bigtop.bom
https://issues.apache.org/jira/browse/BIGTOP-3751
```
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce) @ zeppelin-interpreter ---
[WARNING] 
Dependency convergence error for ch.qos.reload4j:reload4j:1.2.18.3 paths to dependency are:
+-org.apache.zeppelin:zeppelin-interpreter:0.10.0
+-org.apache.hadoop:hadoop-client:3.3.3
+-org.apache.hadoop:hadoop-common:3.3.3
+-ch.qos.reload4j:reload4j:1.2.18.3
and
+-org.apache.zeppelin:zeppelin-interpreter:0.10.0
+-org.apache.hadoop:hadoop-client:3.3.3
+-org.apache.hadoop:hadoop-common:3.3.3
+-org.slf4j:slf4j-reload4j:1.7.36
+-ch.qos.reload4j:reload4j:1.2.19
and
+-org.apache.zeppelin:zeppelin-interpreter:0.10.0
+-org.apache.hadoop:hadoop-client:3.3.3
+-org.apache.hadoop:hadoop-common:3.3.3
+-org.apache.hadoop:hadoop-auth:3.3.3 …
```
> BIGTOP-3751. Fix build failure of Zeppelin due to dependency convergence error.

- bigtop-packages/src/common/zeppelin/install_zeppelin.sh
- bigtop-packages/src/rpm/zeppelin/SPECS/zeppelin.spec
Zeppelin home directory should include plugins directory. Current Bigtop zeppelin spec file and install_zeppelin.sh file does not specify plugins directory 
Build will be successful and rpm file will be generated without any error even if there is no specification about plugins directory.
However when you install rpm and run zeppelin notebook, you will see Logs Like below
```java
...
WARN [2022-07-18 10:29:36,366] ({ImmediateThread-1658107775074} PluginManager.java[getPluginClassLoader]:192) - PluginFolder /usr/nch/current/zeppelin-server/plugins/NotebookRepo/FileSystemNotebookRepo doesn't exist or is not a directory
...
ERROR [2022-07-18 10:29:38,364] ({main} ZeppelinServer.java[main]:262) - Error while running jettyServer
java.lang.Exception: A MultiException has 2 exceptions.  They …
```
> BIGTOP-3747. zeppelin includes plugins directory

- bigtop-packages/src/common/hive/patch10-exclude-hadoop-shaded-client-via-spark.diff
- bigtop-packages/src/common/hive/patch8-HIVE-22398-branch-3.1.diff
- bigtop-packages/src/common/hive/patch9-exclude-reload4j.diff
https://issues.apache.org/jira/browse/BIGTOP-3708
* backported [HIVE-22398](https://issues.apache.org/jira/browse/HIVE-22398)for addressing Hadoop API incompatibility.
* updated exclusion rule for addressing migration from log4j to reload4j [HADOOP-18088](https://issues.apache.org/jira/browse/HADOOP-18088).
* exluded hadoop-client-api (shaded client) from transitive dependencies of webhcat to avoid compile error due to [relocation](https://github.com/apache/hadoop/blob/rel/release-3.3.3/hadoop-client-modules/hadoop-client-api/pom.xml#L223-L228).
> BIGTOP-3708. Fix build failure of Hive against Hadoop 3.3.3

- bigtop-packages/src/common/bigtop-ambari-mpack/dev-support/docker/centos7/Dockerfile
- bigtop-packages/src/common/bigtop-ambari-mpack/dev-support/docker/centos7/build-containers.sh
Add Chrony synchronization to fix hostcheck issue in Mpack docker provisioner.
Also silence the shellcheck issues: SC2046 and SC2164.
```
$pwd
bigtop/bigtop-packages/src/common/bigtop-ambari-mpack/dev-support/docker/centos7
```
Build docker images: `./build-image.sh`
Ambari deployment: `./build-containers.sh`
Access Ambari web ui: localhost:8080
> BIGTOP-3750: Add Chrony synchronization to fix hostcheck issue in Mpack docker provisioner

- bigtop-deploy/puppet/hieradata/bigtop/cluster.yaml
- bigtop-deploy/puppet/modules/hadoop_hive/manifests/init.pp
- bigtop-deploy/puppet/modules/hadoop_hive/templates/hive-site.xml
the default hive-on-tez mode config will cause the hive query hang up for a long time. 
so I commit the patch to add **hive config hive.tez.cpu.vcores** and **hive.tez.container.size** configurations for hive on tez mode.
1. enter the $BIGTOP_HOME/provisioner/docker dir, and edit the docker-hadoop.sh, add following config
```shell
hadoop_hive::common_config::hive_execution_engine: "tez"
hadoop::common::use_tez: true
hadoop_hive::common_config::hive_tez_container_size: 1024
hadoop_hive::common_config::hive_tez_cpu_vcores: 1
```
2. edit the config.yaml
```yaml
docker:
memory_limit: "4g"
image: "bigtop/puppet:trunk-centos-7"
repo: "http://repos.bigtop.apache.org/releases/3.1.0/centos/7/$basearch"
distro: centos
components: [hdfs, yarn, mapreduce,hive, tez]
enable_local_repo: false …
```
> BIGTOP-3744. Puppet Deploy Hive on Tez add Resource Resizing Configs

- bigtop-packages/src/common/hbase/patch0-HBASE-27065-2.4.13.diff
- bigtop.bom
https://issues.apache.org/jira/browse/BIGTOP-3755
Bumping to 2.4.13 would be nice to have since it contains major fix like [HBASE-27108](https://issues.apache.org/jira/browse/HBASE-27108).
> BIGTOP-3755. Bump HBase to 2.4.13.

- bigtop-packages/src/common/tez/do-component-build
- bigtop-packages/src/common/tez/patch4-TEZ-4300-and-TEZ-4428.diff
- bigtop-packages/src/common/tez/patch5-TEZ-4298.diff
https://issues.apache.org/jira/browse/BIGTOP-3758
* We can leverage protoc-jar-maven-plugin by cherry-picking [TEZ-4300](https://issues.apache.org/jira/browse/TEZ-4300) and [TEZ-4428](https://issues.apache.org/jira/browse/TEZ-4428). (TEZ-4300 is just needed to cleanly apply TEZ-4428)
* We need to install protoc artifact from locally installed one on aarch64 and ppc64le.
* [TEZ-4298](https://issues.apache.org/jira/browse/TEZ-4298) fixed ShuffleHandler.
> BIGTOP-3758. Fix build failure of Tez against Hadoop 3.3.

- bigtop-packages/src/common/spark/do-component-build
Add JVM options for spark build to avoid StackOverflowError on Bigtop's Jenkins.
On CentOS 7, arm machine
```sh
$ ./gradlew spark-clean spark-pkg
... 
+ exit 0
BUILD SUCCESSFUL in 58m 35s
7 actionable tasks: 7 executed
```
I also checked that setting larger values worked. 
e.g. 
```
$ export MAVEN_OPTS="--Xss32g -Xmx32g -XX:ReservedCodeCacheSize=1g"
$ ./gradlew spark-clean spark-pkg
```
> BIGTOP-3762: Add JVM options for spark build to avoid StackOverflowError

- bigtop_toolchain/bin/puppetize.sh
- bigtop_toolchain/manifests/packages.pp
- packages.gradle
- provisioner/docker/config_ubuntu-22.04.yaml
This PR adds an Ubuntu 22.04 option to Bigtop
- switch to create symlink to python2 because python-is-python2 cannot be installed to Ubuntu 22.04
- add a warning message to add privileged option for docker smoke test to avoid test failures caused by newer systemd version
I tested on a ubuntu 22.04 host machine, x86 CPU.
```sh
cd docker/bigtop-puppet
./build.sh trunk-ubuntu-22.04
cd ../bigtop-slaves/
./build.sh trunk-ubuntu-22.04
cd ../..
./gradlew -POS=ubuntu-22.04 -Pdocker-run-option="--privileged" zookeeper-pkg-ind
./gradlew -POS=ubuntu-22.04 -Pdocker-run-option="--privileged" repo-ind
cd provisioner/docker
./docker-hadoop.sh -d  -C config_ubuntu-22.04.yaml -F docker-compose-cgroupv2.yml  \
--create 1  --memory 8g  --enable-local-repo  --repo file:///bigtop-home/output/apt  \ …
```
> BIGTOP-3754: Add Ubuntu 22.04 option

- bigtop-packages/src/common/hive/do-component-build
1.Fix Hive build issues about protobuf 2.5.0 on Arm64 and
PPC64le when upgrading hadoop to 3.3.3/3.3.4,
2.Expand Java heap size.
Build Hive and run smoke tests
> BIGTOP-3763: Fix Hive build issues about protobuf 2.5.0 on Arm64 and PPC64le

- bigtop-packages/src/rpm/hadoop/SPECS/hadoop.spec
The cmake3 would be always installed on centos-7:
https://github.com/apache/bigtop/blob/master/bigtop_toolchain/manifests/packages.pp#L69-#L73
We can remove the cmake conditional for cmake3 was always provided in CentOS 7.
Builf Hadoop against on Centos-7.
Run smoke tests.
> BIGTOP-3765: Remove cmake conditional for Hadoop rpm spec

- bigtop-deploy/puppet/modules/hadoop/manifests/init.pp
- bigtop-packages/src/common/hadoop/init-hcfs.json
Add spark user hdfs folder for deploying spark thrift server
1. build the hadoop package and create a repo
2. tested by docker provisioner.
> BIGTOP-3768. Add Spark User Hdfs Folder for Deploy Spark Thrift Server

- bigtop-packages/src/common/phoenix/do-component-build
https://issues.apache.org/jira/browse/BIGTOP-3775
The root cause is same with [BIGTOP-3763](https://issues.apache.org/jira/browse/BIGTOP-3763).
We still need locally installed protobuf-2.5.0 which was brought back by [BIGTOP-3709](https://issues.apache.org/jira/browse/BIGTOP-3709).
Build Phoenix on Arm64/Powerpc64le
> BIGTOP-3775: Failed to build Phoenix on Arm64/powerpc64le

- bigtop-deploy/puppet/hieradata/bigtop/cluster.yaml
- bigtop-deploy/puppet/manifests/cluster.pp
- bigtop-deploy/puppet/modules/spark/manifests/init.pp
- bigtop-deploy/puppet/modules/spark/templates/spark-defaults.conf
- bigtop-deploy/puppet/modules/spark/templates/spark-env.sh
Add Spark Thrift Server Puppet Deploy Code
1. #972 first should resolve the pr
2. edit the docker-hadoop.sh 
```yaml
bigtop::hadoop_head_node: $1
hadoop::hadoop_storage_dirs:
- /data/1
bigtop::roles_enabled: true
bigtop::roles: 
- namenode
- resourcemanager
- hive-client
- hive-metastore
- datanode
- nodemanager
- mapred-app
- spark-on-yarn
- spark-thriftserver
bigtop::bigtop_repo_uri: ["file:///bigtop-home/output"]
hadoop_hive::common_config::hive_execution_engine: "tez"
hadoop::common::use_tez: true
hadoop::common_yarn::yarn_resourcemanager_scheduler_class: org.apache.hadoop.yarn.server.resourcemanager.scheduler.fair.FairScheduler
hadoop::common_yarn::yarn_scheduler_capacity_maximum_am_resource_percent: 0.5
hadoop_hive::common_config::hive_tez_container_size: 1024 …
```
> BIGTOP-3767. Add Spark Thrift Server Puppet Deploy Code

- bigtop-packages/src/deb/phoenix/phoenix.install
I list .rpm and .deb files as below.
- .rpm file.
```
drwxr-xr-x root/root         0 2022-08-22 02:46 ./usr/share/doc/
drwxr-xr-x root/root         0 2022-08-22 02:46 ./usr/share/doc/phoenix/
-rw-r--r-- root/root     33895 2020-01-22 15:10 ./usr/share/doc/phoenix/LICENSE.gz
-rw-r--r-- root/root      3325 2020-01-22 15:10 ./usr/share/doc/phoenix/NOTICE.gz
-rw-r--r-- root/root       129 2022-08-22 02:46 ./usr/share/doc/phoenix/changelog.Debian.gz
-rw-r--r-- root/root     25756 2021-05-30 15:25 ./usr/share/doc/phoenix/changelog.gz
-rw-r--r-- root/root       318 2022-08-22 02:46 ./usr/share/doc/phoenix/copyright
drwxr-xr-x root/root         0 2020-01-22 15:10 ./usr/share/doc/phoenix/examples/
-rw-r--r-- root/root       149 2020-01-22 15:10 ./usr/share/doc/phoenix/examples/STOCK_SYMBOL.csv …
```
> BIGTOP-3787. Add docs in Phoenix .deb package

- bigtop-ci/build.sh
- packages.gradle
This PR adds an option that adds a docker volume  and mounts `.m2` during the build.
Adding this option, users could reduce the build time by skipping some download processes.
```sh
./gradlew target-ind -POS=ubuntu-20.04 -Pmvn-cache-volume=true
```
or
```sh
cd bigtop-ci; bash -xe ./build.sh --prefix trunk --os ubuntu-20.04 --target zookeeper-pkg --mvn-cache true
```
With this option, bigtop create docker volume that named `bigtop-mvn-cache-$OS` if not exists and mount it on `/var/lib/jenkins/.m2` in the provisioner container. If the volume has already existed, bigtop reuse it.
If users set the option `false`, bigtop try to remove the volume and build without the cache.
If users does not set any option for this, bigtop do nothing for mounting the volume (Same behavior with before).
I …
> BIGTOP-3801: Add maven cache volume for docker provisioner

- bigtop-packages/src/rpm/hadoop/SPECS/hadoop.spec
- bigtop_toolchain/bin/puppetize.sh
- docker/bigtop-puppet/build.sh
- docker/bigtop-slaves/build.sh
- provisioner/docker/config_fedora-36.yaml
This PR adds a Fedora 36 option to Bigtop.
- use java 8 during build process because on fedora 36 java 17 is also installed and set as default.
- add init-script installations to use init.d
- opt-out from Fedora 36's default `CFLAGS` options.
I tested on CentOS7/arm and on Ubuntu 22.04/x86.
```sh
cd docker/bigtop-puppet/
./build.sh trunk-fedora-36
cd ../bigtop-slaves/
./build.sh trunk-fedora-36
cd ../..
./gradlew -POS=fedora-36 -Pdocker-run-option="--privileged" \
bigtop-utils-pkg-ind bigtop-jsvc-pkg-ind bigtop-groovy-pkg-ind \
zookeeper-pkg-ind hadoop-ind repo-ind 
cd provisioner/docker/
./docker-hadoop.sh -d  -C config_fedora-36.yaml -F docker-compose-cgroupv2.yml  \
--create 3  --memory 8g  --enable-local-repo  --repo file:///bigtop-home/output  \
--disable-gpg-check  --stack …
```
> BIGTOP-3756: Add Fedora 36 option

- bigtop-packages/src/common/zookeeper/install_zookeeper.sh
- bigtop-packages/src/rpm/zookeeper/SPECS/zookeeper.spec
Tested with #994 
diff result:
```
76706 blocks
76706 blocks
2d1
< ./etc/zookeeper
2960 blocks
2960 blocks
3,5c3,5
< ./usr/lib/debug/.build-id/14
< ./usr/lib/debug/.build-id/14/f894a8d56d3605a32e06dae10414d8fce637a5
< ./usr/lib/debug/.build-id/14/f894a8d56d3605a32e06dae10414d8fce637a5.debug
---
> ./usr/lib/debug/.build-id/49
> ./usr/lib/debug/.build-id/49/62750d18b3c9b7307c7ef7d759e3534ff094b7
> ./usr/lib/debug/.build-id/49/62750d18b3c9b7307c7ef7d759e3534ff094b7.debug
10,12c10,15
< ./usr/lib/debug/.build-id/bc
< ./usr/lib/debug/.build-id/bc/8fb84dd4b8899b6615b39bae1f853f0cf831c1
< ./usr/lib/debug/.build-id/bc/8fb84dd4b8899b6615b39bae1f853f0cf831c1.debug
---
> ./usr/lib/debug/.build-id/a2
> ./usr/lib/debug/.build-id/a2/97a24eec5b2bc42df57041bdbc0a1472a0fe51
> …
```
> BIGTOP-3796: Support parent directory configuration for Zookeeper rpm build script

- bigtop-packages/src/deb/hadoop/hadoop-httpfs.preinst
- bigtop-packages/src/rpm/hadoop/SPECS/hadoop.spec
> BIGTOP-3810: Fix wrong home configuration for HTTPFS on build scripts

- bigtop-packages/src/common/hive/patch12-HIVE-22205-branch-3.1.diff
https://issues.apache.org/jira/browse/BIGTOP-3803
added backport patch of [HIVE-22205](https://issues.apache.org/jira/browse/HIVE-22205) to address the issued caused by version mismatch of Curator.
> BIGTOP-3803. Fix Hive3.1.3 Metastore service compatible issue with Hadoop3.3.x when kerberos enabled.

- bigtop-deploy/puppet/modules/spark/manifests/init.pp
- This PR defers Spark ThriftServer's launch after initializing HDFS so that the launch succeeds.
- Ran `./docker-hadoop.sh -d -C config_rockylinux-8.yaml -r file:///bigtop-home/output -G -k hdfs,yarn,spark -c 3` locally.
> BIGTOP-3814. Deploying Spark ThriftServer fails because it's launched too early.

- bigtop-packages/src/deb/alluxio/rules
- bigtop-packages/src/deb/hadoop/rules
- bigtop-packages/src/deb/spark/rules
https://issues.apache.org/jira/browse/BIGTOP-3623
strip-nondeterminism on deb packaging of Hadoop and Spark takes several hours after upgrading to Hadoop 3.x due to expanded dependencies and shaded client. Since building Bigtop packages are not so [reproducible](https://wiki.debian.org/ReproducibleBuilds/About) by its nature, we should be ok to skip it now.
The same fix is already applied for Ambari, Hive and Oozie already.
> BIGTOP-3623. dh_strip_nondeterminism spends too much time on deb packaging.

- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/HDFS/metainfo.xml
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/HDFS/quicklinks/quicklinks.json
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/YARN/configuration-mapred/mapred-env.xml
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/YARN/metainfo.xml
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/YARN/quicklinks-mapred/quicklinks.json
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/YARN/quicklinks/quicklinks.json
1 add quicklinks for HDFS/YARN/MapReduce
2 fix the bug that cann't access to http://mr-historyserver-host:19888/logs
Tested in local vm cluster, including kerberos authentication
hdfs quicklink
yarn quicklink
mr quicklink
mr logs ui
> BIGTOP-3804: Add quicklinks for HDFS/YARN/MapReduce

- bigtop-packages/src/deb/hadoop/hadoop-httpfs.postinst
https://issues.apache.org/jira/browse/BIGTOP-3815
This is a follow-up of #1007 causing following error.
```
Setting up hadoop-httpfs (3.3.4-1) ...
chown: cannot access '/var/run/hadoop-httpfs': No such file or directory
dpkg: error processing package hadoop-httpfs (--configure):
```
> BIGTOP-3815. Fix failure of installing hadoop-httpfs deb due to change of httpfs home dir.

- bigtop-packages/src/deb/phoenix/control
- bigtop-packages/src/rpm/phoenix/SPECS/phoenix.spec
When we deploy Phoenix, we just need to move phoenix-server.jar to hbase lib dir.
So I think the package requires is redundant.
> BIGTOP-3818. Phoenix Don't Requre Hadoop and Zookeeper Installed

- bigtop-packages/src/deb/hbase/rules
- bigtop-packages/src/deb/phoenix/rules
- bigtop-packages/src/deb/zeppelin/rules
https://issues.apache.org/jira/browse/BIGTOP-3827
Deb packaging of HBase, Phoenix and Zeppelin looks time consuming due to shaded jars. We can skip dh_strip_nondeterminism as done for Hadoop and Spark in [BIGTOP-3623](https://issues.apache.org/jira/browse/BIGTOP-3623) (#1012).
> BIGTOP-3827. Skip dh_strip_nondeterminism for HBase, Phoenix and Zeppelin

- bigtop-packages/src/common/spark/install_spark.sh
- bigtop-packages/src/rpm/spark/SPECS/spark.spec
diff result:
```
467490 blocks
467490 blocks
8386 blocks
8386 blocks
69792 blocks
69792 blocks
10 blocks
10 blocks
10 blocks
10 blocks
25856 blocks
25856 blocks
13786 blocks
13790 blocks
10 blocks
10 blocks
10 blocks
10 blocks
26599 blocks
26599 blocks
```
> BIGTOP-3805: Support parent directory configuration for Spark rpm build script

- bigtop-packages/src/common/bigtop-select/install_select.sh
- bigtop-packages/src/rpm/bigtop-select/SPECS/bigtop-select.spec
BIGTOP-3845: Add the command to create the /usr/bigtop folder in the bigtop-select rpm package
> BIGTOP-3845: Add the command to create the /usr/bigtop folder in the bigtop-select rpm package

- provisioner/docker/config_rockylinux-8.yaml
In rockylinux8 config file, the default url is invalid.
Change default url from 'centos' to 'rockylinux'.
```
$ ./docker-hadoop.sh -d -C  config_rockylinux-8.yaml -c 3
...snip...
$ ./docker-hadoop.sh -e 1 dnf info hadoop-hdfs-namenode
Last metadata expiration check: 0:05:34 ago on Tue Oct 25 15:20:18 2022.
Installed Packages
Name         : hadoop-hdfs-namenode
Version      : 3.2.3
...
```
> BIGTOP-3858 Invalid repository URL is set in rockylinux8 config

- bigtop-ci/build.sh
- bigtop-packages/src/common/kafka/do-component-build
- bigtop_toolchain/manifests/installer.pp
- bigtop_toolchain/manifests/jdk11.pp
- packages.gradle
This PR aims bigtop users can use Java 11 when they package some projects on a docker container.
- The behavior of bigtop is not changed.
- If user set an option, bigtop pass a flag to the docker container by environment variable. If build target project can receive the flag, bigtop switch `JAVA_HOME` to change the Java version.
I checked below on aarch 64 machine
```sh
cd docker/bigtop-slaves/
OS_LIST=( ubuntu-18.04 ubuntu-20.04 ubuntu-22.04 debian-10 debian-11 centos-7 rockylinux-8 fedora-35 fedora-36 )
for OS in ${OS_LIST[@]} ; do
./build.sh trunk-${OS}
done
for OS in ${OS_LIST[@]} ; do
echo $OS; 
docker run -i --rm bigtop/slaves:trunk-$OS-aarch64 ls /usr/lib/jvm;
echo ""
done
```
The default JAVA_HOME is set to 8 by `/etc/profile.d/bigtop.sh` so installation does not affect on it.
I …
> BIGTOP-3852: Java 11 to bigtop-toolchain to use it in docker container during packaging

- bigtop-packages/src/rpm/phoenix/SPECS/phoenix.spec
I added  python3 dependency only for rockylinux8 in spec file.
I can find python3 requirement in rpm file that  by build with rockylinux8.
```
$ ./gradlew -POS=rockylinux-8 phoenix-pkg-ind
...snip...
$ rpm -qRp output/phoenix/noarch/phoenix-5.1.2-1.el8.noarch.rpm
/bin/sh
/bin/sh
/bin/sh
/usr/bin/env
bigtop-utils >= 0.7
coreutils
python3
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
```
In docker provisionar, I have confirmed that the following steps will run sqlline.py in phoenix.
```
$  ./docker-hadoop.sh -d -C config_rockylinux-8.yaml -r file:///bigtop-home/output -G -k zookeeper,hdfs,hbase,phoenix -c 3
...snip...
$ ./docker-hadoop.sh -e 1 python3 /usr/lib/phoenix/bin/sqlline.py
Setting …
```
> BIGTOP-3829 The Phoenix component should have python3 as its dependency

- provisioner/docker/docker-hadoop.sh
If users use docker provisioner from gradle, it fails. This is because `docker-hadoop.sh` returns 1 even if the provisioning was secceeded.
```sh
$ ./gradlew -Pstack=zookeeper docker-provisioner
...
Notice: Finished catalog run in 74.78 seconds
> Task :docker-provisioner FAILED
```
This PR add an error message check before printing the file, to avoid the error exit.
```sh
$ ./gradlew -Pstack=zookeeper docker-provisioner
...
Notice: Finished catalog run in 65.20 seconds
BUILD SUCCESSFUL in 1m 29s
```
> BIGTOP-3868: Add an error message file check to avoid the error exit

- bigtop-packages/src/common/ambari/patch12-fix-ambari-metrics-grafana-service-issues.diff
- bigtop-packages/src/common/ambari/patch5-refine-AMBARI-25599-for-Hadoop-3.4.diff
https://issues.apache.org/jira/browse/BIGTOP-3872
Adjust Ambari-2.7.5 dependency to fix the deployment issues of Ambari metrics. When users deploy Hadoop components with Bigtop stack,  Ambari mertrics dependency should be updated to fix the related issues.
> BIGTOP-3872: Adjust Ambari-2.7.5 dependency to fix the deployment issues of Ambari metrics

- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/repos/repoinfo.xml
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/FLINK/metainfo.xml
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/HBASE/metainfo.xml
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/HDFS/metainfo.xml
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/HIVE/metainfo.xml
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/KAFKA/metainfo.xml
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SOLR/metainfo.xml
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/SPARK/metainfo.xml
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/TEZ/metainfo.xml
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/YARN/metainfo.xml
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/ZEPPELIN/metainfo.xml
- bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack/src/main/resources/stacks/BGTP/1.0/services/ZOOKEEPER/metainfo.xml
https://issues.apache.org/jira/browse/BIGTOP-3726
Align the version of the components in Mpack.
Also update repo info to 3.2.
Deploy Mpack and check services versions:
`cd bigtop/provisioner/bigtop-stack-provisioner/docker/centos7`
Build environment image: `./build-image.sh`
Setup Environment: `./build-containers.sh`
Access Ambari webui: `localhost:8080`
Check Bigtop serivces:
> BIGTOP-3726: Align the version of the components in Mpack

- bigtop-packages/src/rpm/flink/SPECS/flink.spec
- bigtop-packages/src/rpm/hadoop/SPECS/hadoop.spec
- bigtop-packages/src/rpm/hbase/SPECS/hbase.spec
- bigtop-packages/src/rpm/hive/SPECS/hive.spec
- bigtop-packages/src/rpm/kafka/SPECS/kafka.spec
- bigtop-packages/src/rpm/solr/SPECS/solr.spec
- bigtop-packages/src/rpm/spark/SPECS/spark.spec
- bigtop-packages/src/rpm/tez/SPECS/tez.spec
- bigtop-packages/src/rpm/zeppelin/SPECS/zeppelin.spec
- bigtop-packages/src/rpm/zookeeper/SPECS/zookeeper.spec
- bigtop.bom
- packages.gradle
> BIGTOP-3786: Improve the build scripts to append suffix to the rpm package name

- bigtop-packages/src/deb/spark/control
https://issues.apache.org/jira/browse/BIGTOP-3891
From the latest [Debian packaging policies 4.6.1](https://www.debian.org/doc/debian-policy/ch-source.html), 
the package name in debian/changelog is autogenerated from the bigtop package (spark-pkg/spark-deb). But 'spark-core' was named in debian/control which caused the conflict:
```
> Task :spark-sdeb
dpkg-buildpackage: info: source package spark
dpkg-buildpackage: info: source version 3.2.3-1
dpkg-buildpackage: info: source distribution stable
dpkg-buildpackage: info: source changed by Bigtop <dev@bigtop.apache.org>
dpkg-buildpackage: warning: debian/rules is not executable; fixing that
dpkg-source --before-build .
dpkg-source: error: source package has two conflicting values - spark-core and spark
dpkg-buildpackage: error: dpkg-source …
```
> BIGTOP-3891: Fix build issues of Spark in Debian11/Ubuntu22 packaging

- bigtop-packages/src/rpm/gpdb/SPECS/gpdb.spec
Fix build error by adding opt-out flag to the spec file.
(cf. https://fedoraproject.org/wiki/Changes/SetBuildFlagsBuildCheck)
I tested on ubuntu-20.04/x86 and centos-7/arm64 host machine.
```sh
./gradlew -POS=fedora-36 -Pdocker-run-option="--privileged" gpdb-clean gpdb-pkg-ind
```
> BIGTOP-3890: Failed to build gpdb on Fedora-36

- bigtop-packages/src/common/hadoop/do-component-build
- bigtop_toolchain/manifests/grpc.pp
- bigtop_toolchain/manifests/protobuf.pp
https://issues.apache.org/jira/browse/BIGTOP-3893
Fix Hadoop3.3.4 build issues on ppc64le.
```
Haoop common depends on protobuf-2.5.0:
[ERROR] Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.5.1:compile (src-compile-protoc-legacy) on project hadoop-common: Missing:
[ERROR] ----------
[ERROR] 1) com.google.protobuf:protoc:exe:linux-ppcle_64:2.5.0
[ERROR]
[ERROR]   Try downloading the file manually from the project website.
[ERROR]
[ERROR]   Then, install it using the command:
[ERROR]       mvn install:install-file -DgroupId=com.google.protobuf -DartifactId=protoc -Dversion=2.5.0 -Dclassifier=linux-ppcle_64 -Dpackaging=exe -Dfile=/path/to/file
[ERROR]
[ERROR]   Alternatively, if you host your own repository you can deploy the file there:
[ERROR]       mvn …
```
> BIGTOP-3893: Fix Hadoop3.3.4 build issues on ppc64le

- bigtop-packages/src/common/alluxio/do-component-build
https://issues.apache.org/jira/browse/BIGTOP-3894
`protobuf-3.17.3` was pre-installed in Bigtop toolchain for ppc64le. And protoc `grpc-java-1.28.0` was also built based on `protobuf-3.17.3` in Bigtop toolchain.
So manually install 3.17.3 to workaound the GLIBC issue.
And `protobuf-3.19.2/3.17.3` doesn't offically support ppc64le;
Skip protoc backwards compatibility check here.
Build Alluxio on centos, debian, ubuntu and fedora.
Run smoke tests:
```
./docker-hadoop.sh --create 3 --image bigtop/puppet:3.2.0-centos-7 \
--memory 16g --repo file:///bigtop-home/output \
--disable-gpg-check --enable-local-repo \
--stack hdfs,yarn,mapreduce,alluxio \
--smoke-tests alluxio
```
```
...
..
.
Successfully started process 'Gradle Test Executor 2'
Gradle Test Executor 2 finished executing tests.
> …
```
> BIGTOP-3894: Failed to build Alluxio on Centos-7

- bigtop-deploy/puppet/modules/kerberos/manifests/init.pp
- bigtop-deploy/puppet/modules/kerberos/templates/kdc.conf
- bigtop-deploy/puppet/modules/kerberos/templates/krb5.conf
https://issues.apache.org/jira/browse/BIGTOP-3901
Encryption types must be updated to fix the error on recent versions of Kerberos+
```
Error: 'rm -f /etc/kadm5.keytab ; kdb5_util -P cthulhu -r BIGTOP.APACHE.ORG create -s && kadmin.local -q 'cpw -pw secure kadmin/admin'' returned 1 instead of one of [0]
```
In addition, dependencies of `Exec[kdb5_util]` must be fixed because kadmin.local belongs krb5-admin-server package in Ubuntu.
```
Error: /Stage[main]/Kerberos::Kdc/Exec[kdb5_util]/returns: change from 'notrun' to ['0'] failed: Loading random data
Initializing database '/var/lib/krb5kdc/principal' for realm 'BIGTOP.APACHE.ORG',
master key name 'K/M@BIGTOP.APACHE.ORG'
sh: 1: kadmin.local: not found
```
> BIGTOP-3901. Fix failure of Kerberos deployment on Rocky Linux 8 and Ubuntu 22.04.

- provisioner/bigtop-stack-provisioner/docker/centos7/Dockerfile
- provisioner/docker/config_centos-7.yaml
- provisioner/docker/config_debian-10.yaml
- provisioner/docker/config_debian-11.yaml
- provisioner/docker/config_fedora-36.yaml
- provisioner/docker/config_rockylinux-8.yaml
- provisioner/docker/config_ubuntu-20.04.yaml
- provisioner/docker/config_ubuntu-22.04.yaml
https://issues.apache.org/jira/browse/BIGTOP-3905
Update 3.2.0 release repo in Bigtop-stack-provisioner `Dockerfile` and smoke tests `yaml`s.
> BIGTOP-3905: Update Bigtop-stack-provisioner repo for the latest 3.2.0 release

- bigtop-packages/src/common/zookeeper/install_zookeeper.sh
- bigtop.bom
fix bug, see:  [BIGTOP-3913](https://issues.apache.org/jira/browse/BIGTOP-3913)
Building package with -PparentDir=/usr/bigtop for zk, 
and installing zookeeper, 
and testing by executing zookeeper-client,zookeeper-server,zookeeper-server-cleanup,zookeeper-server-initialize
install_zookeeper.sh
Please review @iwasakims thanks
> BIGTOP-3913:The path information is incorrect in the zookeeper-client script file by building with -PparentDir

- bigtop-packages/src/common/flink/install_flink.sh
`./gradlew flink-clean flink-pkg -PparentDir=/usr/bigtop -PpkgSuffix`
Successful build in Centos7(x86_64).
> BIGTOP-3914: Add missing jars to Flink to fix sql-client.sh execution errors

- bigtop-deploy/puppet/modules/gpdb/manifests/init.pp
https://issues.apache.org/jira/browse/BIGTOP-3897
The root cause: Python's cryptography package was upgraded to python3 and a Arm gcc error would occur when attempting to install the cryptography package by puppet.
The patch is to remove unnecessary package installation in puppet except for CentOS. GPDB smoke tests have been tested in Fedora-36, CentOS-7, Rockylinux-8, Debian-10/11 and Ubuntu-20.04.
> BIGTOP-3897: Failed to deploy gpdb on Fedora-36 for arm64

- bigtop-packages/src/common/solr/install_solr.sh
- bigtop.bom
Resolve issue [BIGTOP-3922](https://issues.apache.org/jira/browse/BIGTOP-3922)  by adding executable permissions to files in {SOLR_HOME}/server/scripts/cloud-scripts
building Solr,
Checking the permissions of thoese files by installing Solr or decompressing Solr package
install_solr.sh
> BIGTOP-3922:zkcli.sh of Solr does not have executable permissions

- bigtop-packages/src/rpm/kafka/SPECS/kafka.spec
- bigtop.bom
fix kafka directory permission
details in https://issues.apache.org/jira/browse/BIGTOP-3931
Before the fix, the permission of /usr/bigtop/3.2.0/usr/lib/kafka and its subdirectories was set to kafka, instead of root. This caused a permission error when trying to install Ranger Kafka plugin.
After the fix, the permission of /usr/bigtop/3.2.0/usr/lib/kafka and its subdirectories were restored to root, and Ranger Kafka plugin could be installed without issues.
> BIGTOP-3931: fix kafka directory permission

- bigtop-packages/src/common/hive/patch14-HIVE-26684-branch-3.1.diff
https://issues.apache.org/jira/browse/BIGTOP-3926
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.1.0:shade (default) on project hive-jdbc: Error creating shaded jar: null: IllegalArgumentException -> [Help 1
```
The error was caused by upgrading Bouncy Castle on Hadoop side. [maven-shade-plugin must be upgraded](https://issues.apache.org/jira/browse/MSHADE-337) to handle multi-JVM jar.
This is follow-up of #1101 and depending on #1102.
> BIGTOP-3926. Fix build failure of Hive against Hadoop 3.3.5.

- bigtop-packages/src/common/flink/patch0-FLINK-27640-branch-1.15.diff
https://issues.apache.org/jira/browse/BIGTOP-3929
Building flink fails due to missing transitive dependency on pentaho-aggdesigner-algorithm.
```
[ERROR] Failed to execute goal on project flink-connector-hive_2.12: Could not resolve dependencies for project org.apache.flink:flink-connector-hive_2.12:jar:1.15.3: Failed to collect dependencies at org.apache.hive:hive-exec:jar:2.3.9 -> org.pentaho:pentaho-aggdesigner-algorithm:jar:5.1.5-jhyde: Failed to read artifact descriptor for org.pentaho:pentaho-aggdesigner-algorithm:jar:5.1.5-jhyde: Could not transfer artifact org.pentaho:pentaho-aggdesigner-algorithm:pom:5.1.5-jhyde from/to conjars (http://conjars.org/repo): Transfer failed for http://conjars.org/repo/org/pentaho/pentaho-aggdesigner-algorithm/5.1.5-jhyde/pentaho-aggdesigner-algorithm- …
```
> BIGTOP-3929. Fix build failure of Flink due to transitive dependency on pentaho-aggdesigner-algorithm.

- bigtop-packages/src/common/ranger/patch2-RANGER-3992.diff
Ranger was built successful.
`./gradlew ranger-clean ranger-pkg -PparentDir=/usr/bigtop --debug`
> BIGTOP-3923: Add missing jars for Ranger caused by the component version specified

- bigtop-packages/src/common/hbase/patch2-HBASE-27860-2.4.13.diff
See: [BIGTOP-3927](https://issues.apache.org/jira/browse/BIGTOP-3927)
Build following command
$ ./gradlew clean hbase-pkg-ind
> BIGTOP-3927: Add patch for build HBase ageinst Hadoop 3.3.5

- bigtop-packages/src/common/ycsb/patch2-maprdb-repo-url.diff
https://issues.apache.org/jira/browse/BIGTOP-3945
Update deprecated mapr repo url to fix YCSB build issues
> BIGTOP-3945: Fix YCSB build issues for deprecated mapr repo url

- bigtop-packages/src/common/ambari/patch13-AMBARI-25946.diff
https://issues.apache.org/jira/browse/BIGTOP-3946
While upgrading bower should be the right solution, it is not yet done in Ambari upstream. I just added the patch of [AMBARI-25946](https://issues.apache.org/jira/browse/AMBARI-25946).
> BIGTOP-3946. Fix build failure of Ambari due to expired certificate of bower repo.

- bigtop-packages/src/common/zeppelin/patch3-exclude-jaxb-api.diff
https://issues.apache.org/jira/browse/BIGTOP-3949
added exclusion to fix dependency convergence error caused by bumping Hadoop to 3.3.5.
```
Dependency convergence error for javax.xml.bind:jaxb-api:2.2.11 paths to dependency are:
+-org.apache.zeppelin:zeppelin-server:0.10.1
+-org.apache.hadoop:hadoop-client:3.3.5
+-org.apache.hadoop:hadoop-yarn-api:3.3.5
+-javax.xml.bind:jaxb-api:2.2.11
and
+-org.apache.zeppelin:zeppelin-server:0.10.1
+-org.apache.hadoop:hadoop-client:3.3.5
+-org.apache.hadoop:hadoop-mapreduce-client-core:3.3.5
+-org.apache.hadoop:hadoop-yarn-common:3.3.5
+-javax.xml.bind:jaxb-api:2.2.11
and
+-org.apache.zeppelin:zeppelin-server:0.10.1
+-org.apache.hadoop:hadoop-common:3.3.5
+-com.github.pjfanning:jersey-json:1.20
+-com.sun.xml.bind:jaxb-impl:2.2.3-1 …
```
> BIGTOP-3949. Fix dependency convergence error of Zeppelin.

- bigtop-packages/src/common/tez/patch6-TEZ-4492.diff
https://issues.apache.org/jira/browse/BIGTOP-3948
We need to cherry-pick the patch of [TEZ-4492](https://issues.apache.org/jira/browse/TEZ-4492) since Tez 0.10.3 is not yet released.
> BIGTOP-3948. Fix build failure of Tez due to expired certificate of bower repo.

- bigtop-packages/src/common/oozie/patch2-fix-hive-test-dependency.diff
https://issues.apache.org/jira/browse/BIGTOP-3947
added test scope dependency on hive-service to compilation error.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:testCompile (default-testCompile) on project oozie-core: Compilation failure: Compilation failure:
[ERROR] /home/rocky/srcs/bigtop/build/oozie/rpm/BUILD/oozie-5.2.1/core/src/test/java/org/apache/oozie/test/hive/MiniHS2.java:[39,31] package org.apache.hive.service does not exist
[ERROR] /home/rocky/srcs/bigtop/build/oozie/rpm/BUILD/oozie-5.2.1/core/src/test/java/org/apache/oozie/test/hive/MiniHS2.java:[40,35] package org.apache.hive.service.cli does not exist
[ERROR] /home/rocky/srcs/bigtop/build/oozie/rpm/BUILD/oozie-5.2.1/core/src/test/java/org/apache/oozie/test/hive/MiniHS2.java:[41,35] …
```
> BIGTOP-3947. Fix build failure of Oozie due to insufficient test scope dependency on hive-service.

- bigtop_toolchain/lib/puppet/parser/functions/latest_ant_binary.rb
- bigtop_toolchain/lib/puppet/parser/functions/latest_maven_binary.rb
- bigtop_toolchain/lib/puppet/parser/functions/nearest_apache_mirror.rb
This PR changes the download site of Maven and Ant from dlcdn.apache.org to archive.apache.org in case that old versions are removed from the former site.
By running `./gradlew toolchain` on CentOS 7.
> BIGTOP-3952. Fix toolchain to download Maven from archive.apache.org instead of dlcdn.apache.org.

- bigtop-deploy/puppet/manifests/bigtop_repo.pp
- bigtop-deploy/puppet/manifests/jdk.pp
- bigtop-deploy/puppet/modules/hadoop/manifests/init.pp
- bigtop-deploy/puppet/modules/ranger/manifests/init.pp
- bigtop_toolchain/manifests/cleanup.pp
- bigtop_toolchain/manifests/env.pp
- bigtop_toolchain/manifests/gnupg.pp
- bigtop_toolchain/manifests/installer.pp
- bigtop_toolchain/manifests/jdk.pp
- bigtop_toolchain/manifests/jdk11.pp
- bigtop_toolchain/manifests/packages.pp
- bigtop_toolchain/manifests/renv.pp
This PR fixes the toolchain to work properly with the recent versions of facter on Rocky 8.
This PR is for the master branch. See #1122 for branch-3.2.
```
$ ./gradlew -POS=rockylinux-8 bigtop-puppet
$ ./gradlew -POS=rockylinux-8 bigtop-slaves
$ ./gradlew -POS=rockylinux-8 -Pmvn-cache-volume=true allclean bigtop-groovy-pkg-ind bigtop-jsvc-pkg-ind bigtop-utils-pkg-ind zookeeper-pkg-ind hadoop-pkg-ind ranger-pkg-ind repo-ind
$ ./docker-hadoop.sh -d -dcp -C config_rockylinux-8.yaml -F docker-compose-cgroupv2.yml -G -L -i bigtop/puppet:trunk-rockylinux-8 -k hdfs,yarn,ranger -s ranger -c 1
```
> BIGTOP-3951. Fix toolchain to work with the recent version of facter.

- bigtop-packages/src/common/ranger/install_ranger.sh
- bigtop-packages/src/rpm/ranger/SPECS/ranger.spec
This PR modifies the configuration directories for Ranger Admin, Ranger Tag Sync, and Ranger User Sync from `/etc/ranger-admin`, `/etc/ranger-tagsync`, and `/etc/ranger-usersync` to `/etc/ranger/{admin,tagsync,usersync}`. The detailed reason for this change can be found in the following issue: https://issues.apache.org/jira/projects/BIGTOP/issues/BIGTOP-3950
manual test
before fix, ranger-tagsync can't start,because it ranger can't found /etc/ranger/tagsync/logback.xml
after fix , ranger-tagsync works smoonthly
> BIGTOP-3950: fix ranger etc conf dir

- bigtop-deploy/puppet/manifests/python.pp
- bigtop-deploy/puppet/manifests/site.pp
- bigtop-packages/src/deb/ambari/control
- bigtop-packages/src/deb/gpdb/control
- bigtop-packages/src/deb/hive/control
- bigtop-packages/src/deb/phoenix/control
- bigtop-packages/src/deb/spark/control
- bigtop-packages/src/deb/ycsb/control
https://issues.apache.org/jira/browse/BIGTOP-3930
* added alternative dependency to python2.
* added manifest to use `/usr/bin/python` pointing to python2 on Ubuntu 22.04.
> BIGTOP-3930. Fix deployment failure on Ubuntu 22.04 due to unavailable dependency on python.

- bigtop.bom
This PR fixes version definitions in bigtop.bom so that [`./gradlew setversion`](/apache/bigtop/blob/master/release.gradle#L64-L74) works. That command replaces the same strings as the value of [the `version` variable defined in build.gradle](/apache/bigtop/blob/master/build.gradle#L152), so we have to assign a literal rather than a variable to [the `bigtop.version` variable in bigtop.bom](/apache/bigtop/blob/master/bigtop.bom#L97).
Made sure that `./gradlew setversion` works as expected with this PR:
```
$ ./gradlew all-components | head
> Task :all-components
bigtop 3.3.0-SNAPSHOT stack includes the following components
alluxio                        2.8.0
ambari                         2.7.5
bigtop-ambari-mpack            2.7.5
bigtop-groovy                  2.5.4
bigtop-jsvc …
```
> BIGTOP-3954. Fix the version definition in bigtop.bom so that `./gradlew setversion` works.

- bigtop-packages/src/common/hadoop/do-component-build
- bigtop-packages/src/rpm/hadoop/SPECS/hadoop.spec
Add support for hadoop component, the point modifed is:
1. redhat-rpm-config should be instead of openEuler-rpm-config in openEuler.
2. The node-gyp 3.8.0 only support python2, but openEuler using the python3.
docker run --rm -v `pwd`:/home/bigtop --workdir /home/bigtop bigtop/slaves:trunk-openeuler-22.03-aarch64 bash -c '. /etc/profile.d/bigtop.sh; ./gradlew hadoop-pkg'
> BIGTOP-3877: add support for hadoop on openeuler

- bigtop-packages/src/common/hadoop/do-component-build
After deploying yarn TimelineService v2, it fails to start because Hadoop 3, by default, includes HBase 1 client in the packaging of hadoop-yarn-server-timelineservice-hbase-client-3.3.4.jar. When the TimelineServiceReader starts and attempts to create an HBase table, it encounters compatibility issues between HBase 1 and 2 APIs, resulting in the failure to find the required method and thus unable to create the table.
see more details in  https://issues.apache.org/jira/browse/BIGTOP-3961
manual test
after fixed yarn timeline service v2  working normally
> BIGTOP-3961: Fix version mismatch of hbase-client used by hadoop-yarn-server-timelineservice-hbase

- bigtop_toolchain/manifests/ant.pp
https://issues.apache.org/jira/browse/BIGTOP-3962
```
Notice: /Stage[main]/Bigtop_toolchain::Ant/Exec[Download Ant binaries]/returns: executed successfully
Notice: /Stage[main]/Bigtop_toolchain::Ant/Exec[Download Ant binaries signature]/returns: executed successfully
Notice: /Stage[main]/Bigtop_toolchain::Ant/Exec[Download Ant binaries signature]: Triggered 'refresh' from 1 event
Notice: /Stage[main]/Bigtop_toolchain::Ant/Exec[Verify Ant binaries]/returns: gpg: armor header: Version: GnuPG v1
Notice: /Stage[main]/Bigtop_toolchain::Ant/Exec[Verify Ant binaries]/returns: gpg: assuming signed data in 'apache-ant-1.9.9-bin.tar.gz'
Notice: /Stage[main]/Bigtop_toolchain::Ant/Exec[Verify Ant binaries]/returns: gpg: Signature made Thu Feb  2 18:30:59 2017 UTC
Notice: …
```
> BIGTOP-3962. Fix setup failure of Ant due to unresolved gpg public key.

- bigtop-deploy/puppet/modules/phoenix/manifests/init.pp
- bigtop-packages/src/rpm/phoenix/SPECS/phoenix.spec
Add support for phoenix component, the point modifed is:
select the python3 on openeuler.
docker run --rm -v pwd:/home/bigtop --workdir /home/bigtop bigtop/slaves:trunk-openeuler-22.03-aarch64 bash -c '. /etc/profile.d/bigtop.sh; ./gradlew phoenix-pkg'
> BIGTOP-3955: add support for phoenix

- bigtop-packages/src/common/hive/patch15-HIVE-27535-support-hadoop3.3.5.diff
Hive version: 3.1.3
Hadoop version: 3.3.5
After upgrading to Hadoop 3.3.5, the Hive WebHCat server fails to start because of inconsistent versions of the Jersey JAR package. Hive HCat lacks the jersey-server-1.19 jar.
for more details see: https://issues.apache.org/jira/browse/BIGTOP-3966
manual test
after apply this patch WebHCat start normally
> BIGTOP-3966: Make hive 3.1.3 compatible with hadoop 3.3.5

- bigtop-packages/src/common/zeppelin/do-component-build
https://issues.apache.org/jira/browse/BIGTOP-3970
[BIGTOP-3560](https://issues.apache.org/jira/browse/BIGTOP-3560) addressed similar issue caused by missing grpc-java-1.28.0. [BIGTOP-3893](https://issues.apache.org/jira/browse/BIGTOP-3893) addressed Hadoop issue caused by missing grpc-java-1.26.0. Zeppelin requires both grpc-java 1.26.0 and 1.28.0. While [both are compiled by docker_toolchain](https://github.com/apache/bigtop/blob/b52211e4e830d6aeb3b4a637b0222f7176c6ba21/bigtop_toolchain/manifests/grpc.pp#L26-L67), [do-component-build doinstall:install-file for 1.28.0](https://github.com/apache/bigtop/blob/b52211e4e830d6aeb3b4a637b0222f7176c6ba21/bigtop-packages/src/common/zeppelin/do-component-build#L52). If you build Zeppelin after Hadoop reusing local repo (~/.m2/repository), Zeppelin …
> BIGTOP-3970. Fix build failure of Zeppelin due to missing grpc-java-1.26.0 on ppc64le.

- bigtop-deploy/puppet/modules/hadoop_oozie/manifests/init.pp
Add support for oozie component, include compile command and problem.
build command
docker run --rm -v pwd:/home/bigtop --workdir /home/bigtop bigtop/slaves:trunk-openeuler-22.03-aarch64 bash -c '. /etc/profile.d/bigtop.sh; ./gradlew oozie-pkg'
smoke test command
./docker-hadoop.sh -C config_openeuler-22.03.yaml -c 3 -s
> BIGTOP-3969: add support for oozie 

- bigtop-packages/src/common/gpdb/do-component-configure
- bigtop-packages/src/rpm/gpdb/SPECS/gpdb.spec
Add support for gpdb component, include compile command and problem.
1. specify the verion of python for openEuler
2. python2 be compiled manually and install, not installed by rpm in openEuler
build command         
docker run --rm -v `pwd`:/home/bigtop --workdir /home/bigtop bigtop/slaves:trunk-openeuler-22.03-aarch64 bash -c '. /etc/profile.d/bigtop.sh; ./gradlew gpdb-pkg'
smoke test command
./docker-hadoop.sh -C config_openeuler-22.03.yaml -c 3 -s
> BIGTOP-3880: add support for gpdb

- bigtop-deploy/puppet/modules/hadoop/manifests/init.pp
add hadoop smoke test for openeuler
change the cgroup of hdfs and yarn from hadoop to root in openeuler, otherwise, the namemode of hdfs has not the permission to create directories during smoke test.
> BIGTOP-3883: add hadoop smoke test for openeuler

- bigtop-deploy/puppet/modules/hadoop/manifests/init.pp
https://issues.apache.org/jira/browse/BIGTOP-3972
In Bigtop deployment, Oozie reads /etc/hadoop/conf/ssl-client.xml on startup. The file should be readable by Oozie user.
* https://github.com/apache/oozie/blob/release-5.2.1/core/src/main/java/org/apache/oozie/service/HadoopAccessorService.java#L260-L261
* https://github.com/apache/bigtop/blob/02c1fb93f86edb587d7a215517c16c0181e8c576/bigtop-deploy/puppet/modules/hadoop_oozie/templates/oozie-site.xml#L224-L235
```
2023-08-01 12:11:07,913 ERROR Services:514 - SERVER[4d0ff4043c6d.bigtop.apache.org] E0100: Could not initialize service [org.apache.oozie.service.HadoopAccessorService], /etc/hadoop/conf/ssl-client.xml (Permission denied)
org.apache.oozie.service.ServiceException: E0100: Could not initialize service …
```
> BIGTOP-3972. Fix startup failure of Oozie due to permission error on reading ssl-client.xml.

- bigtop-packages/src/rpm/ycsb/SPECS/ycsb.spec
Add support for ycsb component, include compile command and problem.
1. python2 be compiled manually and install, not installed by rpm in openEuler
build command
docker run --rm -v pwd:/home/bigtop --workdir /home/bigtop bigtop/slaves:trunk-openeuler-22.03-aarch64 bash -c '. /etc/profile.d/bigtop.sh; ./gradlew ycsb-pkg'
smoke test command
./docker-hadoop.sh -C config_openeuler-22.03.yaml -c 3 -s
> BIGTOP-3879: add support for ycsb

- bigtop-packages/src/rpm/kafka/SPECS/kafka.spec
Add support for kafka component, the point modifed is:
redhat-lsb should be instead of openeuler-lsb in openEuler.
docker run --rm -v pwd:/home/bigtop --workdir /home/bigtop bigtop/slaves:trunk-openeuler-22.03-aarch64 bash -c '. /etc/profile.d/bigtop.sh; ./gradlew kafka-pkg'
> BIGTOP-3878: add support for kafka

- bigtop-packages/src/common/hadoop/do-component-build
https://issues.apache.org/jira/browse/BIGTOP-3981
Since [Hadoop is using org.openlabtesting.leveldbjni on aarh64](https://github.com/apache/hadoop/blob/rel/release-3.3.5/pom.xml#L724-L735) now, we can get rid of patching and building leveldbjni in do-component-build script on aarch64.
Attachments
> BIGTOP-3981. Get rid of building patched leveldbjni in Hadoop packaging on aarch64.

- bigtop_toolchain/manifests/packages.pp
We add the python2 for openEuler docker slaves by compile manually.
Many components need python2, including ambari/ycsb/gpdb.
The build command :
ARM arch: /bigtop/docker/bigtop-slaves/build.sh trunk-openeuler-22.03-aarch64
X86 arch: /bigtop/docker/bigtop-slaves/build.sh trunk-openeuler-22.03
> BIGTOP-3975: add the python2 for openEuler docker slaves

- docker/bigtop-slaves/build.sh
https://issues.apache.org/jira/browse/BIGTOP-3982
The PR is based on Branch `openEuler-support`
The docker image of openEuler was not able to be built:
```
./build.sh: 96: [: openeuler: unexpected operator
...
..
.
=> ERROR [3/5] RUN if [ -f ~/.bash_profile ]; then . ~/.bash_profile; fi &&     yum clean all && yum updateinfo &&     puppet apply -e "include bigtop_toolchain::installer" || if [ $  27.1s
...
..
.
#0 24.71         14 Important Security notice(s)
#0 24.71          9 Moderate Security notice(s)
#0 27.07 Error: Evaluation Error: Error while evaluating a Function Call, Could not find class ::bigtop_toolchain::installer for buildkitsandbox.shanghai.arm.com (line: 1, column: 1) on node 
```
There is unexpected Operator error in shell script:
`if [ $OS == "openeuler" ];then`
> BIGTOP-3982: Fix build issues of openEuler docker images on Bigtop

- bigtop-packages/src/common/ranger/patch3-RANGER-3206-commit-2.diff
https://issues.apache.org/jira/browse/BIGTOP-3983
Cherry pick the patch from the commit 2 of [RANGER-3206](https://issues.apache.org/jira/browse/RANGER-3206).
(https://github.com/apache/ranger/commit/f6b69ca5846de9a7dfced70ae8e403388ecb89fe.)
The smoke tests were passed on Arm64 Fedora-36.
```
./docker-hadoop.sh -d --create 3 --image bigtop/puppet:3.2.0-fedora-36 --memory 16g \
--repo file:///bigtop-home/output --disable-gpg-check --enable-local-repo \
--stack bigtop-utils,ranger  \
--smoke-tests ranger 
```
```
...
..
.
> Task :bigtop-tests:smoke-tests:ranger:test
Finished generating test XML results (0.026 secs) into: /bigtop-home/bigtop-tests/smoke-tests/ranger/build/test-results/test
Finished generating test html results (0.058 secs) into: …
```
> BIGTOP-3983: Fix the Ranger-2.4 deploying issues

- bigtop.bom
https://issues.apache.org/jira/browse/BIGTOP-3993
While I know ZooKeeper 3.6 is already EOL, Hadoop 3.3.6 is developed against it now (and having compilation issue against ZooKeeper 3.5). I think bumping ZooKeeper from 3.5 to 3.6 is good as intermediate step to upgrade to 3.7 or later and good candidate to merge into branch-3.2 (i.e. Bigtop 3.2.2) too.
I built zookeeper-pkg and ran smoke-tests of zookeeper this on Ubuntu 22.04 (x86_64) and Rocky Linux 8 (aarch64).
```
$ ./docker-hadoop.sh \
--create 1 \
--image bigtop/puppet:trunk-ubuntu-22.04 \
--docker-compose-yml docker-compose-cgroupv2.yml \
--docker-compose-plugin \
--memory 16g \
--repo file:///bigtop-home/output/apt \
--disable-gpg-check \
--stack zookeeper \
--smoke-tests zookeeper
```
This breaks build of Hadoop until …
> BIGTOP-3993. Bump ZooKeeper to 3.6.4.

- bigtop-packages/src/common/hadoop/patch0-HADOOP-18867-branch-3.3.diff
- bigtop.bom
https://issues.apache.org/jira/browse/BIGTOP-3994
This depends on #1169 since building Hadoop against ZooKeeper 3.5 fails.
[HADOOP-18867](https://issues.apache.org/jira/browse/HADOOP-18867) describes the reason why we need additional patch here.
> BIGTOP-3994. Bump Hadoop to 3.3.6.

- bigtop-deploy/puppet/hieradata/bigtop/repo.yaml
- provisioner/docker/config_centos-7.yaml
- provisioner/docker/config_debian-10.yaml
- provisioner/docker/config_debian-11.yaml
- provisioner/docker/config_fedora-35.yaml
- provisioner/docker/config_fedora-36.yaml
- provisioner/docker/config_rockylinux-8.yaml
- provisioner/docker/config_ubuntu-18.04.yaml
- provisioner/docker/config_ubuntu-20.04.yaml
- provisioner/docker/config_ubuntu-22.04.yaml
https://issues.apache.org/jira/browse/BIGTOP-3999
Some config files for docker provisioner point to 3.2.0. Since this fix can not cleanly cherry-picked from branch-3.2, I'm submitting a patch here.
Tested docker provisioner with updated config.yaml on Ubuntu 22.04 (x86_64) and Rocky Linux 8 (aarch64).
> BIGTOP-3999. Make docker provisioner of upstream aware of Bigtop 3.2.1.

- bigtop-packages/src/common/zeppelin/patch4-exclude-metrics-core.diff
https://issues.apache.org/jira/browse/BIGTOP-4002
Fix build failure of Zeppelin against Hadoop 3.3.6 due to dependency convergence error
```
[INFO] ----------------< org.apache.zeppelin:zeppelin-server >-----------------
[INFO] Building Zeppelin: Server 0.10.1                                 [45/60]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ zeppelin-server ---
[INFO]
[INFO] --- maven-checkstyle-plugin:2.17:check (checkstyle-fail-build) @ zeppelin-server ---
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce) @ zeppelin-server ---
[WARNING]
Dependency convergence error for io.dropwizard.metrics:metrics-core:4.1.14 paths to dependency are: …
```
> BIGTOP-4002. Fix build failure of Zeppelin against Hadoop 3.3.6 due to dependency convergence error.

- bigtop-packages/src/common/tez/patch7-TEZ-4493.diff
https://issues.apache.org/jira/browse/BIGTOP-4000 
We need [TEZ-4493](https://issues.apache.org/jira/browse/TEZ-4493) to compile Tez against Hadoop 3.3.6. Since Tez 0.10.3 is not yet released, I'm going to cherry-pick the patch before bumping Tez to 0.10.2.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project tez-dag: Compilation failure
[ERROR] /home/iwasakims/srcs/bigtop/output/tez/tez-0.10.1/tez-dag/src/main/java/org/apache/tez/state/StateMachineTez.java:[28,8] org.apache.tez.state.StateMachineTez is not abstract and does not over\
ride abstract method getPreviousState() in org.apache.hadoop.yarn.state.StateMachine
```
> BIGTOP-4000. Fix build failure of Tez against Hadoop 3.3.6.

- bigtop-deploy/puppet/modules/ranger/manifests/init.pp
- bigtop-packages/src/rpm/ranger/SPECS/ranger.spec
Add support for ranger component, the point modifed is:
1. using the openeuler-lsb replace redhat-lsb on openeuler.
2. add the ranger user cgroup to root cgroup, or no permission to start ranger admin service.
3. using /sbin/service to start ranger-admin, like phoenix component: https://github.com/apache/bigtop/pull/1130#issuecomment-1647554191
docker run --rm -v pwd:/home/bigtop --workdir /home/bigtop bigtop/slaves:trunk-openeuler-22.03-aarch64 bash -c '. /etc/profile.d/bigtop.sh; ./gradlew ranger-pkg'
> BIGTOP-3824: add support for ranger

- bigtop-deploy/puppet/modules/hadoop/manifests/init.pp
Using bigtop/puppet for hadoop, include compile command and problem.
build command, such as:
docker run --rm -v pwd:/home/bigtop --workdir /home/bigtop bigtop/slaves:trunk-openeuler-22.03-aarch64 bash -c '. /etc/profile.d/bigtop.sh; ./gradlew hadoop-pkg'
smoke test command, sush as:
./docker-hadoop.sh --create 3 --image bigtop/puppet:test-openeuler-22.03 --memory 16g --repo file:///bigtop-home/output --disable-gpg-check --enable-local-repo --stack bigtop-utils,hadoop--smoke-tests hadoop
> BIGTOP-3988: using bigtop/puppet for hadoop

- docker/bigtop-puppet/build.sh
- docker/bigtop-slaves/build.sh
https://issues.apache.org/jira/browse/BIGTOP-3996
When I'm working on openEuler support (Bigtop toolchain images), some issues occurred:
```
++ sed -i -e 's|RUN bash /tmp/puppetize.sh|ENV PATH /usr/lib/jvm/java-1.8.0/bin:$PATH\nRUN bash /tmp/puppetize.sh|' Dockerfile
sed: preserving permissions for ‘./sedNQcfyR’: Operation not permitted
++ sed -i -e 's|RUN bash /tmp/puppetize.sh|RUN bash /tmp/puppetize.sh\nRUN dnf install -y initscripts|' Dockerfile
sed: preserving permissions for ‘./sedAbeaag’: Operation not permitted
```
After fixing the permisson issues above, I start to rebuild the image (bigtop/puppet) in the same node.
But the docker build process always adopt the cache one which was not built properly in the last time. 
IMHO, it is reasonable to force Docker to rebuild a clean …
> BIGTOP-3996: Force a clean build of toolchain images

- bigtop_toolchain/manifests/maven.pp
This PR fixes toolchain to install Maven 3.8 for building Spark 3.3.
Ran `./gradlew toolchain` and ensured Maven 3.8.8 was installed.
> BIGTOP-4015. Upgrade Maven to 3.8.x.

- bigtop-packages/src/common/alluxio/do-component-build
- bigtop.bom
This PR upgrades Alluxio version to 2.9.3.
Ran the following commands on Rocky 8 (x86_64).
```
$ ./gradlew allclean alluxio-pkg repo -Dbuildwithdeps=true
$ ./docker-hadoop.sh -d -dcp -C config_rockylinux-8.yaml -L -k hdfs,alluxio -s alluxio -c 1
...
> Task :bigtop-tests:smoke-tests:alluxio:test
Finished generating test XML results (0.013 secs) into: /bigtop-home/bigtop-tests/smoke-tests/alluxio/build/test-results/test
Finished generating test html results (0.027 secs) into: /bigtop-home/bigtop-tests/smoke-tests/alluxio/build/reports/tests/test
Now testing...
:bigtop-tests:smoke-tests:alluxio:test (Thread[Daemon worker,5,main]) completed. Took 21.952 secs.
BUILD SUCCESSFUL in 1m 24s
31 actionable tasks: 5 executed, 26 up-to-date
```
> BIGTOP-4018. Upgrade Alluxio to 2.9.3.

- bigtop.bom
This PR upgrades ZooKeeper version to 3.7.2.
Ran the following commands on Rocky 8 (x86_64).
```
$ ./gradlew allclean hadoop-pkg repo -Dbuildwithdeps=true
$ ./docker-hadoop.sh -d -dcp -C config_rockylinux-8.yaml -F docker-compose-cgroupv2.yml -G -L -k zookeeper -s zookeeper -c 1
...
TestZookeeper > testZkServerStatus STANDARD_ERROR
23/10/15 14:45:04 INFO lang.Object: Running zkServer.sh status
23/10/15 14:45:04 INFO lang.Object: zkServer.sh status checks out.
Finished generating test XML results (0.007 secs) into: /bigtop-home/bigtop-tests/smoke-tests/zookeeper/build/test-results/test
Finished generating test html results (0.018 secs) into: /bigtop-home/bigtop-tests/smoke-tests/zookeeper/build/reports/tests/test
Now testing... …
```
> BIGTOP-4021. Upgrade ZooKeeper to 3.7.2.

- bigtop_toolchain/manifests/renv.pp
Currently, Bigtop toolchain installs R 3.5.2 into Debian 10, but it's not compatible with the latest version of the dependent libraries. This PR fixes it to install R 3.6.3 instead.
Ran `./gradlew bigtop-slaves -POS=debian-10` on trunk with the patch submitted by #1185.
> BIGTOP-4013. Fix toolchain to install R 3.6.0+ into Debian 10.

- bigtop-deploy/puppet/modules/ranger/manifests/init.pp
- bigtop-deploy/puppet/modules/ranger/templates/ranger-admin/install.properties
- bigtop-packages/src/deb/ranger/control
- bigtop-packages/src/deb/ranger/ranger.postinst.tpl
- bigtop-packages/src/deb/ranger/ranger.prerm.tpl
- bigtop-packages/src/deb/ranger/rules
- bigtop-packages/src/rpm/ranger/SPECS/ranger.spec
Fix ranger deb packaging and puppet script
manual test
> BIGTOP-4035: Fix ranger deb packaging and puppet script

- bigtop-deploy/puppet/manifests/bigtop_repo.pp
- bigtop-deploy/puppet/manifests/jdk.pp
- bigtop-packages/src/common/bigtop-utils/bigtop-detect-javahome
- bigtop_toolchain/manifests/env.pp
- bigtop_toolchain/manifests/installer.pp
- bigtop_toolchain/manifests/jdk.pp
Currently we're using AdoptOpenJDK 8 for Debian, but its repository has been moved. This PR updates its repository URL and package name.
Ran `sudo puppet apply --modulepath=/usr/share/puppet/modules:/path/to/bigtop -e "bigtop_toolchain::installer"` on Debian 11 and ensured it was successful.
> BIGTOP-4012. Update Adoptium repository settings for Debian 11 in bigtop_toolchain.

- bigtop-packages/src/common/alluxio/do-component-build
- bigtop-packages/src/common/alluxio/install_alluxio.sh
- bigtop_toolchain/manifests/packages.pp
https://issues.apache.org/jira/browse/BIGTOP-3896
The so of alluxio is not compiled by default, and uses the x86 version, so we need to compile libjnifuse*.so and copy it to the corresponding directory of alluxio when building adaptation
Modify the bigtop-release-3.2.0/bigtop-packages/src/common/alluxio/do-component-build file to adapt Arm64 architecture code for fedora OS.
Modify the bigtop-release-3.2.0/bigtop-packages/src/common/alluxio/ install_alluxio.sh file to copy the libjnifuse*.so file.
> BIGTOP-3896. Failed to deploy Alluxio on Arm64/ppc64le Fedora-38

- bigtop-packages/src/common/tez/patch8-TEZ-4520.diff
- bigtop.bom
test on centos7, ubuntu22
./gradlew tez-clean tez-pkg -PbuildThreads=2C
Parallel compilation for Tez requires the introduction of a Tez patch, which can be found at [TEZ-4520](https://issues.apache.org/jira/browse/TEZ-4520). This patch is designed to address the issue of Tez not being able to compile in parallel.
> BIGTOP-4045: Enable Parallel Compilation for Multiple Modules in TEZ

- bigtop-packages/src/common/hadoop/patch9-HDFS-17287.diff
- bigtop.bom
The reason for the slow compilation: The Hadoop project has many modules, and the inability to compile them in parallel results in a slow process. For instance, the first compilation of Hadoop might take several hours, and even with local Maven dependencies, a subsequent compilation can still take close to 40 minutes, which is very slow.
How to solve it: Use mvn dependency:tree and maven-to-plantuml to investigate the dependency issues that prevent parallel compilation.
Investigate the dependencies between project modules.
Analyze the dependencies in multi-module Maven projects.
Download maven-to-plantuml:
wget https://github.com/phxql/maven-to-plantuml/releases/download/v1.0/maven-to-plantuml-1.0.jar
Generate a dependency tree:
mvn dependency:tree > dep.txt
Generate a UML diagram from …
> BIGTOP-4054: Enable Parallel Compilation for Multiple Modules in Hadoop

- README.md
- packages.gradle
Add a numeric type Maven parallel compilation parameter, and modify the corresponding documentation.
manual test on rocky8
> BIGTOP-4061: Improve support for Maven parallel build parameters

- bigtop_toolchain/bin/puppetize.sh
- bigtop_toolchain/manifests/packages.pp
- docker/bigtop-slaves/build.sh
- provisioner/docker/config_rockylinux-9.yaml
This change allows the creation of Rocky Linux 9 packages.  (Presumably compatible with AlmaLinux 9, Centos 9, and RHEL 9 also.)
After patching packages for Centos 7, Rocky Linux 8, and Rocky Linux 9 were built in the following ways:
(container only builds)
./gradlew clean -POS=$DISTRO bigtop-groovy-pkg-ind bigtop-jsvc-pkg-ind bigtop-utils-pkg-ind zookeeper-pkg-ind hadoop-pkg-ind
(also on bare metal)
./gradlew clean -POS=$DISTRO hadoop-pkg
Building for other distros and task were not tested.  (Let me know if there is a command to test the full gamut.  I will be happy to test it.)
> BIGTOP-3991 add rockylinux 9 support

- bigtop.bom
https://issues.apache.org/jira/browse/BIGTOP-4062
The latest maintenance release of Spark 3.3 series with security and correctness fixes is available.
> BIGTOP-4062. Upgrade Spark to 3.3.4.

- bigtop-packages/src/rpm/flink/SPECS/flink.spec
The Flink RPM lacks preun logic, causing the alternative symbolic link to persist even after uninstalling Flink.
For example, if Flink was initially installed under /usr/bigtop/3.2.0 and then installed again with a different version under /usr/bigtop/3.3.0, the alternative symbolic link /etc/alternatives/flink-conf -> /usr/bigtop/3.3.0/etc/flink/conf.dist will not be correctly created due to the old alternatives not being uninstalled.
Upon checking other components, they all include preun uninstallation logic, which is why they do not have this issue.
> BIGTOP-4065: Fixing BUG caused by the lack of preun logic in Flink spec

- bigtop_toolchain/manifests/packages.pp
https://issues.apache.org/jira/browse/BIGTOP-4064
Fix Puppet manifest syntax unusable in Puppet 3 used by CentOS 7. (broken by https://github.com/apache/bigtop/pull/1235)
> BIGTOP-4064. Fix Bigtop toolchain to work with Puppet 3.x.

- bigtop_toolchain/manifests/packages.pp
https://issues.apache.org/jira/browse/BIGTOP-4067
The error is emitted on running tests. Since --enable-optimizations makes the tests mandatory, we can skip tests by removing [the configure option](https://github.com/apache/bigtop/blob/db4ddc1bfeeaa048658d7805e7f9dfbec09b0fec/bigtop_toolchain/manifests/packages.pp#L413).
```
0:08:41 load avg: 0.67 [256/399] test_poplib                                                                                                                                                                                       
Exception in thread Thread-332:                                                                                                                                                                                                    
Traceback (most …
```
> BIGTOP-4067. Fix build failure of Python 2.7 on Rocky Linux 9.

- bigtop-packages/src/common/alluxio/install_alluxio.sh
- bigtop-packages/src/common/bigtop-select/distro-select
- bigtop-packages/src/deb/alluxio/rules
- bigtop-packages/src/rpm/alluxio/SPECS/alluxio.spec
- bigtop.bom
Add pkg-suffix to Alluxio to support Ambari installation and deployment
why change journal dir?
because default journal dir is located under alluxio work dir
manual test
smote test on rocky linux 8
> BIGTOP-4072: Add pkg-suffix to Alluxio to support Ambari installation and deployment

- bigtop_toolchain/bin/puppetize.sh
https://issues.apache.org/jira/browse/BIGTOP-4068
The bug is alluxio smoketest failed in rockylinux 9, the test cmd
./docker-hadoop.sh -d -c 3 -C config_rockylinux-9.yaml
**redhat-lsb** should be installed by dnf when alluxio somketest in  rockylinux 9
> BIGTOP-4068: fix the alluxio in rockylinux9 bug

- build.gradle
- docker/bigtop-puppet/build.sh
- docker/bigtop-slaves/build.sh
- provisioner/docker/config_openeuler-22.03-lts-sp1.yaml
The cmd are:
gradlew  bigtop-puppet  -POS=openeuler-22.03-lts-sp1 -Pprefix=3.3.0
gradlew  bigtop-slaves  -POS=openeuler-22.03-lts-sp1 -Pprefix=3.3.0
> BIGTOP-4082: Fix installation failure or R by bigtop_toolchain on openEuler

- packages.gradle
While working on adding pkgSuffix and parent directory to BigTop DEBs, it became necessary to pass these two variables to the DEB rules file. Upon inspection, I found that the code logic for pkgSuffix and parent directory in RPMs shared similarities in several places and was repetitive. The DEB logic appeared similar too. Instead of following the previous practice that resulted in significant code duplication, I have refactored this part and conducted tests.
Below are some comments regarding the modifications added.
```
getPkgNameSuffix(component, type) {
def originalSuffix = type.equalsIgnoreCase("deb") ? component.deb_pkg_suffix : component.rpm_pkg_suffix
#In RPMs, the Suffix is in the form of a macro and cannot be an empty string, as it would result in a "macro empty body" 
error. …
```
> BIGTOP-4088: Refactor PKG_NAME_SUFFIX and PARENT_DIR

- bigtop-deploy/puppet/modules/spark/manifests/init.pp
The smoketest cmd: ./docker-hadoop.sh –d –c 3 –s spark
The error log:
> BIGTOP-4077: Fix error on deploying Spark due to missing log4j.properties.template

- bigtop-packages/src/rpm/spark/SPECS/spark.spec
Spark smoketest need python3 in rockylinux9.
> BIGTOP-4073: spark support python3 in rockylinux 9

- bigtop_toolchain/bin/puppetize.sh
- bigtop_toolchain/manifests/renv.pp
- build.gradle
- provisioner/docker/config_openeuler-22.03.yaml
https://issues.apache.org/jira/browse/BIGTOP-4093
This PR replace R packaged by oepkgs with R installed from source code. We do not need to be bound to 22.03 LTS SP1.
Since the manifest before BIGTOP-3967 did not work due to conflicting `$url` variables for pandoc an R, this PR fixed the part.
bigtop/slaves:openeuler-22.03 was successfully built with R installation and packaging of Spark succeeded in the image.
```
$ ./gradlew spark-pkg-ind -Pprefix=trunk -POS=openeuler-22.03 -Pdocker-run-option="--privileged"
```
> BIGTOP-4093. Avoid oepkgs for installing R on openEuler.

- bigtop-tests/smoke-tests/solr/build.gradle
- provisioner/utils/setup-env-debian.sh
The test cmd: ./docker -d -c 3 -s solr
The error log:
It need the _**rm**_ command in /usr/bin.
> BIGTOP-4078: fix the solr smoketest failed in debian 11

- bigtop-packages/src/common/flink/do-component-build
- bigtop_toolchain/manifests/packages.pp
https://issues.apache.org/jira/browse/BIGTOP-4076
We need newer version of g++ for rebuilding [@parcel/watcher](https://github.com/parcel-bundler/watcher) for aarch64. I added software collection resources to toolchain for this. Since scl is enabled on only CentOS 7 aarch64, other platforms should not be affected by this PR.
> BIGTOP-4076. Fix compilation failure of Flink on centos 7 aarch64.

- bigtop_toolchain/manifests/renv.pp
https://issues.apache.org/jira/browse/BIGTOP-4097
R can not be installed on OS distributions other than openEuler due to missing package resource definition unintentionally removed by [BIGTOP-4093](https://issues.apache.org/jira/browse/BIGTOP-4093).
> BIGTOP-4097. Fix missing R package resource in toolchain manifest.

- bigtop_toolchain/bin/puppetize.sh
- bigtop_toolchain/manifests/packages.pp
Drop python2 in bigtop-toolchain and bigtop-deploy
The logic here includes creating a default Python. I believe the logic for creating the default Python should be handled within bigtop-deploy, so it has been removed.
manual test
> BIGTOP-4098: Drop python2 in bigtop-toolchain

- bigtop-deploy/puppet/hiera.yaml
- bigtop-deploy/puppet/hieradata/bigtop/ha.yaml
- bigtop-deploy/puppet/hieradata/bigtop/noha.yaml
- bigtop-deploy/puppet/hieradata/site.yaml
- bigtop-deploy/puppet/manifests/cluster.pp
- bigtop_toolchain/bin/puppetize.sh
https://issues.apache.org/jira/browse/BIGTOP-4102
```
[91m[1;31mError: Evaluation Error: Unknown variable: '::operatingsystem'. (file: /etc/puppet/code/modules/bigtop_toolchain/manifests/jdk11.pp, line: 17, column: 8) on node bigtop-slave-arm5.novalocal[0m
[0mThe command '/bin/sh -c if [ -f ~/.bash_profile ]; then . ~/.bash_profile; fi &&     dnf clean all && dnf updateinfo &&     puppet apply -e "include bigtop_toolchain::installer" || if [ $? -ne 2 ]; then exit 1; fi' returned a non-zero code: 1
```
[Legacy facts are disabled by default in Puppet 8](https://www.puppet.com/docs/pe/2023.5/osp/upgrading-from-puppet7-to-puppet8.html#upgrading-from-puppet7-to-puppet8-legacy-facts-deprecation). include_legacy_facts=true in puppet.conf will re-enable it.
This PR is quick fix only targeting …
> BIGTOP-4102. Fix failure of toolchain manifest on Fedora 38 due to unresolved facter variable

- packages.gradle
Build fails when '-DpkgSuffix' is specified when '(rpm|deb)_pkg_suffix'  is not specified in bigtop.bom
[Issue](https://issues.apache.org/jira/browse/BIGTOP-4088)/https://github.com/apache/bigtop/pull/1254 introduced this bug by not checking whether the '(rpm|deb)_pkg_suffix' has been specified in bigtop.bom.
When config '(rpm|deb)_pkg_suffix'  is not specified, groovy returns an empty map  '[:]' which breaks the build. 
``` bash
./gradlew clean bigtop-groovy-pkg bigtop-jsvc-pkg bigtop-select-pkg bigtop-utils-pkg  -Dbuildwithdeps=true -PparentDir=/usr/bigtop -PpkgSuffix
........
Task :bigtop-groovy-srpm
Wrote: /home/mathew/Projects/bigtop/build/bigtop-groovy/rpm/SRPMS/bigtop-groovy-2.5.4-1.el8.src.rpm> Task :bigtop-utils-srpm
Wrote: …
```
> BIGTOP-4105: Build fails when '-DpkgSuffix' is specified and '(rpm|deb)_pkg_suffix' is not specified in bigtop.bom

- bigtop_toolchain/manifests/renv.pp
https://issues.apache.org/jira/browse/BIGTOP-4101
[BIGTOP-4097](https://issues.apache.org/jira/browse/BIGTOP-4097) broke the manifest in openEuler due to missing `pkgs` variable.
> BIGTOP-4101. Fix undefined variable in toolchain manifest for openEuler.

- bigtop-packages/src/deb/phoenix/control
- bigtop-packages/src/rpm/phoenix/SPECS/phoenix.spec
Drop python dependency in Phoenix Package
smoke test in rocky 8
test cmd: 
```
./docker-hadoop.sh -d -dcp --create 3 --image bigtop/puppet:trunk-rockylinux-8 --docker-compose-plugin --memory 8g --repo file:///bigtop-home/output --disable-gpg-check --stack hdfs,hbase,phoenix --smoke-tests phoenix 
```
> BIGTOP-4051: Drop python dependency in Phoenix Package

- bigtop-deploy/puppet/manifests/python.pp
Set default python to python3 in bigtop deploy
Since CentOS 7's yum depends on Python 2, it's necessary to replace the Python interpreter in yum with Python 2.7.
Rocky 8 comes with /usr/libexec/no-python, so only an update-alternatives --set is needed.
Starting from Red Hat 9, the python3-unversioned-command package is provided, thus only the installation of this package is required.
Setting Python3 as the default Python version across various operating systems:
1. **CentOS 7:**
- Install Python 3 development package:
```
yum install python3-devel
```
- Set Python 3 as the default:
```
update-alternatives --install /usr/bin/python python /usr/bin/python3 1
```
2. **Rocky Linux 8:**
- Installation:
```
yum install python3-devel
```
- Due to the presence of `/etc/alternatives/python -> …
> BIGTOP-4100: Set default python to python3 in bigtop deploy

- bigtop-packages/src/deb/spark/control
- bigtop-packages/src/rpm/spark/SPECS/spark.spec
- bigtop-tests/test-artifacts/spark/src/main/groovy/org/apache/bigtop/itest/spark/TestSparkExample.groovy
https://issues.apache.org/jira/browse/BIGTOP-4053
As discussed in the JIRA issue, I have removed the python-releated spark tests in this PR.
Please feel free to comment on that.
On rocky-8
```
[rocky@ip-172-31-4-21 noarch]$ rpm -qp spark-python-3.3.4-1.el8.noarch.rpm --requires
/bin/bash
/usr/bin/env
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
spark-core = 3.3.4-1.el8
```
On Ubuntu-22.04
```
ubuntu@ip-172-31-12-120:~$ dpkg -I ./bigtop/output/spark/spark-python_3.3.4-1_all.deb
new Debian package, version 2.0.
size 3328910 bytes: control archive=12048 bytes.
350 bytes,    12 lines      control
43376 bytes,   474 lines      md5sums
Package: spark-python
Source: spark
Version: 3.3.4-1
Architecture: …
```
> BIGTOP-4053. Remove Python as Spark Installation Dependency

- bigtop-deploy/puppet/manifests/bigtop_repo.pp
- bigtop_toolchain/bin/puppetize.sh
https://issues.apache.org/jira/browse/BIGTOP-4108
* Currently openEuler is not supported in [the bigtop_repo class for setting up repository of Bigtop](https://github.com/apache/bigtop/blob/5355eac396d70e1c170195851ccbd9e3d62637ad/bigtop-deploy/puppet/manifests/bigtop_repo.pp#L22-L23).
* The manifests is required for the [CI job for release process](https://ci.bigtop.apache.org/job/Bigtop-3.3.0-smoke-tests/).
* [yumrepo is a part of the module hosted in forge](https://forge.puppet.com/modules/puppetlabs/yumrepo_core/readme) in recent puppet. It must be installed by `puppet module` since puppet is installed by gem instead of RPM in openEuler.
> BIGTOP-4108. Add support for openEuler to the manifest of bigtop-deploy to set up Bigtop Yum repository

- bigtop_toolchain/manifests/installer.pp
- bigtop_toolchain/manifests/packages.pp
- bigtop_toolchain/manifests/python.pp
https://issues.apache.org/jira/browse/BIGTOP-4114
Unfortunately we seem to need python2 for rebuilding native libraries required for (old?) node-spss by node-gyp. `/usr/bin/python` pointing to `/usr/bin/pytyon3` did not fix this. `/usr/bin/python` is not needed if `/usr/bin/python2` exists. Building Hadoop (with yarn-ui enabled) and Alluxio on rockylinux-8 and fedora-38 aarch \
64 is affected by this. While Alluxio on openeuler-22.03 on aarch64 seems to be affected too, I'm going to declare it as unsupported in Bigtop 3.3.0 since openeuler-22.03 does not provide python2 package.
By applying current bigtop_toolchain manifest, CentOS 7 has python2 since OS core packages depend on it. Debian 11 and Ubuntu 22.04 have python2 as dependency of installed packages.
I moved python related staffs …
> BIGTOP-4114. Fix build failure of Hadoop and Alluxio due to node-gyp error on rockylinux-8 and fedora-38 aarch64.

- bigtop-deploy/puppet/modules/spark/templates/spark-defaults.conf
- bigtop-deploy/puppet/modules/spark/templates/spark-env.sh
This Error may be caused by a version change in Pupput.
Puppet manifest of livy include spark::common class, but it can not refers to spark::deploy::roles in template files.
This PR changes spark::deploy::roles reference to @roles.
$./docker-hadoop.sh -dcp -F docker-compose-cgroupv2.yml -C config_fedora-38.yaml -m 6g -c 3 -k "hdfs, yarn, spark, livy" -s "spark,livy"    
...
> Task :bigtop-tests:smoke-tests:livy:test
Finished generating test XML results (0.001 secs) into: /bigtop-home/bigtop-tests/smoke-tests/livy/build/test-results/test
Finished generating test html results (0.004 secs) into: /bigtop-home/bigtop-tests/smoke-tests/livy/build/reports/tests/testNow testing...
:bigtop-tests:smoke-tests:livy:test (Thread[Execution worker for ':' Thread 7,5,main]) …
> BIGTOP-4109: Fix deployment failure of Spark on Fedora 38 due to manifest incompatible with Puppet 8

- bigtop_toolchain/bin/puppetize.sh
Phoenix smoke test failed due to lack of a python package as the smoke test execute python script.
We need to enable `devel` repo on Rocky Linux 8 because the `python3-devel`  package is in there.
1. Create custom docker images by `./gradlew -POS=rockylinux-8 bigtop-puppet`
2. Prepare custom docker provision yaml file to use the docker image w/ phoenix smoke test setting
3. Run `./docker-hadoop.sh  -dcp -C config_rockylinux-8.yaml -s -c 3`
Test successed on my local machine.
> BIGTOP-4121. Fix test failure of Phoenix on rockylinux-8 due to deployment issue of python3

- provisioner/docker/docker-hadoop.sh
https://issues.apache.org/jira/browse/BIGTOP-4128
```
$./docker-hadoop.sh -dcp -c 3
Environment check...
Check docker:Environment check...
Check docker:
Docker version 26.1.3, build b72abbb
Check docker-compose:
Docker Compose version v2.27.0
Check ruby:
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]
...
```
> BITOP-4128: Docker compose plugin doesn't have '-v' option

- src/site/xdoc/index.xml
The bigtop 3.3.0 support openEuler OS : https://bigtop.apache.org/release-notes.html
Update the information in the bigtop web.
> BIGTOP-4155: Add support for openEuler OS in bigtop web

- bigtop-deploy/puppet/hieradata/bigtop/repo.yaml
- provisioner/docker/config_centos-7.yaml
- provisioner/docker/config_debian-11.yaml
- provisioner/docker/config_openeuler-22.03.yaml
- provisioner/docker/config_rockylinux-8.yaml
- provisioner/docker/config_rockylinux-9.yaml
- provisioner/docker/config_ubuntu-18.04.yaml
- provisioner/docker/config_ubuntu-22.04.yaml
https://issues.apache.org/jira/browse/BIGTOP-4161
BIGTOP-3.3.0 is now released. Let's update the repo url in docker provisioner files.
Tested with config_rockylinux-8.yaml and config_ubuntu-22.04.yaml with the command below
```
./docker-hadoop.sh -dcp -C config_ubuntu-22.04.yaml -k "zookeeper" -c 3 -F docker-compose-cgroupv2.yml
```
> BIGTOP-4161. Make docker provisioner of upstream aware of Bigtop 3.3.0

- provisioner/docker/config_openeuler-22.03.yaml
Fix the docker repo of openeuler:
repo: "http://**_repios_**.bigtop.apache.org/releases/3.3.0/openEuler/22.03/$basearch"
--->
repo: "http://**_repos_**.bigtop.apache.org/releases/3.3.0/openEuler/22.03/$basearch"
> BIGTOP-4171. fix the docker repo of openeuler

- provisioner/docker/docker-hadoop.sh
Prevent docker-hadoop.sh from exec bash command when Node is not running.
See details in [BIGTOP-4183 ](https://issues.apache.org/jira/projects/BIGTOP/issues/BIGTOP-4183)
```
$docker ps -a
CONTAINER ID   IMAGE                              COMMAND        CREATED         STATUS                       PORTS     NAMES
f2820557a644   bigtop/puppet:trunk-ubuntu-22.04   "/sbin/init"   6 seconds ago   Exited (255) 5 seconds ago             20240806_231134_r8527-bigtop-2
074d34a452aa   bigtop/puppet:trunk-ubuntu-22.04   "/sbin/init"   6 seconds ago   Exited (255) 5 seconds ago             20240806_231134_r8527-bigtop-1
719f5d15c605   bigtop/puppet:trunk-ubuntu-22.04   "/sbin/init"   6 seconds ago   Exited (255) 4 seconds ago             20240806_231134_r8527-bigtop-3
$./docker-hadoop.sh -dcp -d
No …
```
> BIGTOP-4183: Docker provisioner can't destroy when container is stopped

- bigtop_toolchain/bin/puppetize.sh
- bigtop_toolchain/manifests/gnupg.pp
- bigtop_toolchain/manifests/python.pp
- packages.gradle
https://issues.apache.org/jira/browse/BIGTOP-4239
I think it should always be possible to develop in a new development environment.
I ran those commands on both Ubuntu 22.04, Ubuntu 24.04 & Rocky-8 and got BUILD SUCCESSFUL.
```
$ sudo bigtop_toolchain/bin/puppetize.sh
$ sudo apt install openjdk-8-jdk
$ ./gradlew toolchain
```
<details>
<summary>The reason for code changes.</summary>
As of Puppet 8.4.0 (the latest version on Ubuntu 24.04), Package['gnupg'] already declares in `/usr/share/puppet/modules/apt/manifests/init.pp` like below:
```
(snip)
case $facts['os']['name'] {
'Debian': {
stdlib::ensure_packages(['gnupg'])
}
'Ubuntu': {
stdlib::ensure_packages(['gnupg'])
}
default: {
}
}
(snip)
```
Without the workaround, we got the error below:
```
Error: Evaluation Error: Error while …
```
> BIGTOP-4239. Add Ubuntu24.04 as a development enviornment

- bigtop-packages/src/common/hadoop/patch1-HADOOP-19116-3.3.6.diff
https://issues.apache.org/jira/browse/BIGTOP-4249
We need backport of [HADOOP-19116](https://issues.apache.org/jira/browse/HADOOP-19116) to add exclusions to test invariants.
```
[ERROR] Found artifact with unexpected contents: '/root/bigtop/output/hadoop/hadoop-3.3.6/hadoop-client-modules/hadoop-client-minicluster/target/hadoop-client-minicluster-3.3.6.jar'
Please check the following and either correct the build or update
the allowed list with reasoning.
ch/
ch/qos/
ch/qos/logback/
ch/qos/logback/core/
ch/qos/logback/core/Appender.class
...
```
> BIGTOP-4249. Fix build failure of Hadoop 3.3.6 against ZooKeeper 3.8.4.

- bigtop-packages/src/rpm/zookeeper/SPECS/zookeeper.spec
https://issues.apache.org/jira/browse/BIGTOP-4263
We need to recreate `/run/zookeeper` directory when the OS restarted.
Applied this patch, built RPM files and install it on Rocky Linux 8(container).
Restarted the OS (container), then check if `systemctl start zookeeper-server` works.
On Ubuntu 24.04 (aarch64): 
```
$ ./gradlew allclean zookeeper-pkg-ind repo-ind -POS=rockylinux-8
$ cd provisioner/docker/
$ ./docker-hadoop.sh --enable-local-repo --disable-gpg-check --docker-compose-plugin -C config_rockylinux-8.yaml -F docker-compose-cgroupv2.yml --stack zookeeper -c 1
$ # `docker ps` to get container_id, and `docker restart $container_id` to restart it.
$ ./docker-hadoop.sh -dcp --exec 1 systemctl status zookeeper-server
● zookeeper-server.service - ZooKeeper is a centralized service for …
```
> BIGTOP-4263. Add systemd-tmpfiles for zookeeper-server RPM

- bigtop_toolchain/bin/puppetize.sh
- bigtop_toolchain/manifests/jdk.pp
- bigtop_toolchain/manifests/jdk11.pp
This adds Debian 12 support.
```
cd docker/bigtop-puppet
./build.sh trunk-debian-12
cd ../bigtop-slaves
./build.sh trunk-debian-12
cd ../../
docker run -it --rm -v `pwd`:/ws --workdir /ws bigtop/slaves:trunk-debian-12 bash -c '. /etc/profile.d/bigtop.sh; ./gradlew allclean deb'
```
> BIGTOP-3990 - Add Debian 12 (bookworm) as a development environment

- bigtop_toolchain/manifests/packages.pp
This PR add the libtirpc-dev package to the Bigtop toolchain so that Hadoop can be built on Ubuntu 24.04.
Ran `./gradlew toolchain` then `./gradlew hadoop-clean hadoop-pkg` after applying this PR on Ubuntu 24.04.
> BIGTOP-4268. Add libtirpc-dev to the toolchain for Ubuntu 24.04.

- bigtop-deploy/puppet/modules/alluxio/manifests/init.pp
- bigtop.bom
This PR upgrades Alluxio to 2.9.6 for the Bigtop 3.4.0 release.
Ran smoke test on Debian 12 and Rocky 9 (x86_64).
> BIGTOP-4272. Upgrade Alluxio to 2.9.6.

- bigtop-packages/src/common/flink/do-component-build
- bigtop.bom
This PR upgrades Flink to 1.20.0 for the Bigtop 3.4.0 release.
I ensured that building Flink 1.20.0 succeeded on Debian 12 and Rocky 9.
```
$ ./gradlew flink-clean flink-pkg repo -Dbuildwithdeps=true
```
I also ensured its smoke test was successful on Debian 12.
```
$ ./docker-hadoop.sh -d -dcp -C config_debian-12.yaml -F docker-compose-cgroupv2.yml -G -L -k hdfs,yarn,flink -s flink -c 3
...
org.apache.bigtop.itest.hadoop.flink.TestFlink STANDARD_ERROR
24/11/22 05:27:40 INFO lang.Object: hadoop fs -rm -r /flink
24/11/22 05:27:41 INFO lang.Object: hadoop fs -mkdir /flink
24/11/22 05:27:42 INFO lang.Object: hadoop fs -put test.data /flink/
org.apache.bigtop.itest.hadoop.flink.TestFlink > testCheckRestfulAPI STANDARD_ERROR
24/11/22 05:27:43 INFO lang.Object: awk …
```
> BIGTOP-4275. Upgrade Flink to 1.20.0.

- bigtop-deploy/puppet/manifests/bigtop_repo.pp
- bigtop-deploy/puppet/manifests/cluster.pp
- provisioner/docker/config_debian-12.yaml
- provisioner/docker/config_ubuntu-24.04.yaml
This PR adds configuration files of Debian 12 and Ubuntu 24.04 for the Docker provisioner.
After applying #1304, building Hadoop and registered it into the local repository, ran the following steps.
Built bigtop-puppet image for Ubuntu 24.04:
```
$ cd docker/bigtop-puppet
$ ./build.sh trunk-ubuntu-24.04
```
Ran smoke test with the new config file:
```
$ ./docker-hadoop.sh -d -dcp -C config_ubuntu-24.04.yaml -F docker-compose-cgroupv2.yml -G -L -k hdfs,yarn -s yarn -c 3
```
I also made sure the same steps for Debian 12.
> BIGTOP-4269. Add provisioner config for Debian 12 and Ubuntu 24.04.

- bigtop.bom
This PR upgrades Phoenix to 5.2.1 for the Bigtop 3.4.0 release.
After building HBase with #1307 and applying this PR, I made sure that Phoenix is successfully built and its smoke test succeeded with Debian 12 and Rocky 9 on x86_64.
```
./gradlew phoenix-clean phoenix-pkg repo -Dbuildwithdeps=true
cd provisioner/docker
./docker-hadoop.sh -d -dcp -C config_debian-12.yaml -F docker-compose-cgroupv2.yml -G -L -k hdfs,hbase,phoenix -s phoenix -c 3
```
```
./gradlew phoenix-clean phoenix-pkg repo -Dbuildwithdeps=true
cd provisioner/docker
./docker-hadoop.sh -d -dcp -C config_rockylinux-9.yaml -F docker-compose-cgroupv2.yml -G -L -r file:///bigtop-home/output -k hdfs,hbase,phoenix -s phoenix -c 3
```
> BIGTOP-4274. Upgrade Phoenix to 5.2.1.

- bigtop-tests/smoke-tests/solr/delete.xml
- bigtop-tests/smoke-tests/solr/indexing.json
- bigtop-tests/smoke-tests/solr/simple.xml
- bigtop-tests/test-artifacts/solr/src/main/groovy/org/apache/bigtop/itest/solr/smoke/SolrTestBase.groovy
- bigtop-tests/test-artifacts/solr/src/main/groovy/org/apache/bigtop/itest/solr/smoke/TestIndexing.groovy
- bigtop-tests/test-artifacts/solr/src/main/groovy/org/apache/bigtop/itest/solr/smoke/TestPing.groovy
- bigtop-tests/test-artifacts/solr/src/main/groovy/org/apache/bigtop/itest/solr/smoke/TestSimple.groovy
- bigtop-tests/test-artifacts/solr/src/main/groovy/org/apache/bigtop/itest/solr/smoke/TestStatistics.groovy
- bigtop.bom
This PR upgrades Solr to 8.11.4 for the Bigtop 3.4.0 release.
Tested on Debian 11 and Rocky 9 (x86_64).
```
$ ./gradlew solr-clean solr-pkg repo -Dbuildwithdeps=true
...
BUILD SUCCESSFUL in 21m 57s
34 actionable tasks: 34 executed
$ ./docker-hadoop.sh -d -dcp -C config_debian-11.yaml -F docker-compose-cgroupv2.yml -G -L -k zookeeper,solr -s solr -c 3
...
> Task :bigtop-tests:smoke-tests:solr:test
Finished generating test XML results (0.008 secs) into: /bigtop-home/bigtop-tests/smoke-tests/solr/build/test-results/test
Finished generating test html results (0.01 secs) into: /bigtop-home/bigtop-tests/smoke-tests/solr/build/reports/tests/test
Now testing...
Starting process 'command '/usr/bin/solrctl''. Working directory: …
```
> BIGTOP-4283. Upgrade Solr to 8.11.4.

- bigtop.bom
This PR upgrades Zeppelin to 0.11.2 for the Bigtop 3.4.0 release.
After applying #1305, #1307, #1309, #1310, #1311 and this PR, ran the following commands on Debian 12 and Rocky 9 (x86_64).
```
$ ./gradlew zeppelin-clean zeppelin-pkg repo -Dbuildwithdeps=true
...
BUILD SUCCESSFUL in 51m 14s
49 actionable tasks: 49 executed
```
I also tested the smoke test passed on Debian 12.
```
$ ./docker-hadoop.sh -d -dcp -C config_debian-12.yaml -F docker-compose-cgroupv2.yml -G -L -k hdfs,yarn,flink,spark,zeppelin -s zeppelin -c 3
...
> Task :bigtop-tests:smoke-tests:zeppelin:test
Finished generating test XML results (0.003 secs) into: /bigtop-home/bigtop-tests/smoke-tests/zeppelin/build/test-results/test
Finished generating test html results …
```
> BIGTOP-4282. Upgrade Zeppelin to 0.11.2.

- bigtop-packages/src/common/spark/patch0-SPARK-41063.diff
- bigtop.bom
- bigtop_toolchain/manifests/maven.pp
This PR upgrades Spark to 3.5.3 for the Bigtop 3.4.0 release.
After applying #1310 and this PR, Spark 3.5.3 was successfully built on Debian 11 and Rocky 9 (x86_64).
```
$ ./gradlew toolchain
$ mvn -version
Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)
(snip)
$ ./gradlew spark-clean spark-pkg repo -Dbuildwithdeps=true
(snip)
BUILD SUCCESSFUL in 46m 8s
34 actionable tasks: 34 executed
```
The smoke test also passed on Debian 11.
```
$ ./docker-hadoop.sh -d -dcp -C config_debian-11.yaml -F docker-compose-cgroupv2.yml -G -L -k hdfs,yarn,spark -s spark -c 3
(snip)
> Task :bigtop-tests:smoke-tests:spark:test
Finished generating test XML results (0.016 secs) into: /bigtop-home/bigtop-tests/smoke-tests/spark/build/test-results/test
Generating HTML test …
```
> BIGTOP-4281. Upgrade Spark to 3.5.3.

- bigtop-packages/src/common/hadoop/hadoop-mapreduce-historyserver.service
- bigtop-packages/src/common/hadoop/install_hadoop.sh
- bigtop-packages/src/common/hadoop/mapreduce.default
- bigtop-packages/src/deb/hadoop/hadoop-mapreduce.install
- bigtop-packages/src/deb/hadoop/rules
- bigtop-packages/src/rpm/hadoop/SPECS/hadoop.spec
https://issues.apache.org/jira/browse/BIGTOP-4195
Introduced systemd unit files for Hadoop (MapReduce History Server) 
Add some environment variable to allow `/usr/bin/mapred` to control the hadoop-mapreduce-historyserver.
Use `RuntimeDirectory` setting to prepare the `/run/hadoop-mapreduce` directory instead of using systemd-tmpfile
Tested on both RPM(rocky linux8) and DEB (Ubuntu 24.04 w/ #1304, #1305)
* Check if building package is SUCCESSFUL
* Check if hadoop-mapreduce-historyserver is running with the packages
* Check if `/run/hadoop-mapreduce` directory exists after restarting
<details>
<summary>Tested logs</summary>
```
$ ./gradlew allclean hadoop-pkg-ind repo-ind -POS=rockylinux-8
$ ./docker-hadoop.sh --enable-local-repo     --disable-gpg-check …
```
> BIGTOP-4195: Provide systemd service unit files: Hadoop(MapReduce)

- bigtop.bom
This PR upgrades bigtop-jsvc to 1.4.0.
Ran `./gradlew bigtop-jsvc-clean bigtop-jsvc-pkg` on Fedora 40 (x86_64).
> BIGTOP-4288. Upgrade Commons Daemon to 1.4.0.

- bigtop_toolchain/bin/puppetize.sh
https://issues.apache.org/jira/browse/BIGTOP-4309
as a candidate for Bigtop 3.4.0 release.
Issues related to packaging will be addressed in follow-up JIRAs.
> BIGTOP-4309. Add Fedora 40 support to toolchain.

- bigtop-packages/src/common/hadoop/hadoop-layout.sh
- bigtop-packages/src/common/hadoop/hadoop-yarn-nodemanager.service
- bigtop-packages/src/common/hadoop/hadoop-yarn-proxyserver.service
- bigtop-packages/src/common/hadoop/hadoop-yarn-resourcemanager.service
- bigtop-packages/src/common/hadoop/hadoop-yarn-router.service
- bigtop-packages/src/common/hadoop/hadoop-yarn-timelineserver.service
- bigtop-packages/src/common/hadoop/hadoop-yarn.tmpfile
- bigtop-packages/src/common/hadoop/install_hadoop.sh
- bigtop-packages/src/deb/hadoop/hadoop-yarn.install
- bigtop-packages/src/deb/hadoop/hadoop-yarn.postinst
- bigtop-packages/src/deb/hadoop/rules
- bigtop-packages/src/rpm/hadoop/SPECS/hadoop.spec
https://issues.apache.org/jira/browse/BIGTOP-4279
Add system unit file for Hadoop(YARN)
Tested on RPM(Rocky Linux 8 and DEB(Ubuntu-24.04).
* Did YARN smoke tests
* Checked if  `systemctl start` , `systemctl status` works
* Checked if `/run` exists after the OS(Container) restarts (Unlike MapReduce Service, I used `systemd-tmpfile` because there are many processes that use `/var/run/hadoop-yarn` and don't want to change the behavior)
<details>
<summary>Manual Testing logs...</summary>
* build & smoketests
```
$ ./gradlew allclean hadoop-pkg-ind repo-ind -POS=rockylinux-8
$ ./docker-hadoop.sh --enable-local-repo --disable-gpg-check     --docker-compose-plugin     -C config_rockylinux-8.yaml     -F docker-compose-cgroupv2.yml     --stack hdfs,yarn --smoke-tests yarn …
```
> BIGTOP-4279: Provide systemd service unit files: Hadoop(YARN)

- bigtop-packages/src/common/hive/do-component-build
https://issues.apache.org/jira/browse/BIGTOP-4345
Hive on Spark feature has been removed since Hive 4.0.0 ([HIVE-26134](https://issues.apache.org/jira/browse/HIVE-26134)), so there's no need to have
```
-Dspark.version=${SPARK_VERSION} \
-Dscala.binary.version=${SCALA_VERSION%.*} \
-Dscala.version=${SCALA_VERSION} \
```
in Maven opts.
By a local build.
> BIGTOP-4345: Remove spark and scala from Hive Maven opts

- bigtop-packages/src/deb/hadoop/rules
- bigtop-packages/src/deb/hbase/rules
- bigtop-packages/src/deb/hive/rules
- bigtop-packages/src/rpm/hadoop/SPECS/hadoop.spec
- bigtop-packages/src/rpm/hbase/SPECS/hbase.spec
- bigtop-packages/src/rpm/hive/SPECS/hive.spec
https://issues.apache.org/jira/browse/BIGTOP-4356
From ZooKeeper 3.5.5, zookeeper.jar has been splitted into two jars: zookeeper.jar and zookeeper-jute.jar. Both should be symlinked in Hadoop/Hive/HBase lib directories.
By a local build.
> BIGTOP-4356: Ensure zookeeper-jute.jar is on the classpath along with zookeeper.jar

- bigtop-packages/src/deb/tez/rules
- bigtop-packages/src/rpm/tez/SPECS/tez.spec
tez-0.10.4-minimal.tar.gz has made some changes compared to previous versions:
- slf4j-log4j12-\*.jar -> slf4j-reload4j-\*.jar
- hadoop related jars within lib/ directory are: hadoop-hdfs-client, hadoop-mapreduce-client-core, hadoop-mapreduce-client-common, and hadoop-yarn-server-timeline-pluginstorage
We should update the rpm and deb scripts accordingly.
By a local build.
> BIGTOP-4354: Update packaging scripts for Tez 0.10.4

- bigtop-deploy/puppet/hieradata/bigtop/cluster.yaml
- bigtop-deploy/puppet/modules/zeppelin/manifests/init.pp
- bigtop-deploy/puppet/modules/zeppelin/templates/interpreter.json
- bigtop-deploy/puppet/modules/zeppelin/templates/zeppelin-site.xml
This PR fixes the Puppet manifest of Zeppelin and its related files so that Zeppelin works just after deployed using them.
Created a cluster with the revised files and ensured Spark example notebooks worked by default.
> BIGTOP-4364. Fix Zeppelin's default settings.

- bigtop-bigpetstore/bigpetstore-transaction-queue/build.gradle
- bigtop-bigpetstore/bigpetstore-transaction-queue/src/main/java/org/apache/bigtop/bigpetstore/qstream/LoadGen.java
- bigtop-bigpetstore/bigpetstore-transaction-queue/src/main/java/org/apache/bigtop/bigpetstore/qstream/Utils.java
- bigtop-data-generators/bigpetstore-data-generator/build.gradle
- bigtop-data-generators/bigtop-location-data/build.gradle
- bigtop-data-generators/bigtop-name-generator/build.gradle
- bigtop-data-generators/bigtop-samplers/build.gradle
- bigtop-data-generators/bigtop-weatherman/build.gradle
This PR upgrade dependencies of bigtop-data-generators and bigpetstore-transaction-queue and fix minor issues so that they can be successfully built.
[Same as bigpetstore-spark](https://github.com/apache/bigtop/pull/1330), we have to build the com.github.rnowling.bigpetstore package and install it into local maven repository first. After that, they should be built as follows:
```
$ cd bigtop-data-generators
$ ../gradlew clean build
(snip)
BUILD SUCCESSFUL in 10s
24 actionable tasks: 24 executed
$ cd -
$ cd bigtop-bigpetstore/bigpetstore-transaction-queue
$ ../../gradlew clean build
(snip)
BUILD SUCCESSFUL in 2m 37s
8 actionable tasks: 8 executed
```
> BIGTOP-4369. Upgrade dependencies of bigtop-data-generators and bigpetstore-transaction-queue.

- bigtop_toolchain/manifests/user.pp
https://issues.apache.org/jira/browse/BIGTOP-4373
Since the 1000 is already used as uid/gid of ubunut user/group in the ubuntu base image, groupadd fails on applying toolchain manifest.
* 1000 is the lowest uid for end users on linux distributions. We should use higher number which is expected to be available.
* While some CI jobs assume that jenkins is 1000, those can be easily fixed.
*  `*-pkg-ind` should work regardless of junkins uid in the container since [it extracts results by `docker cp`](https://github.com/apache/bigtop/blob/340665e910309666cbe8c980514940e7611b05df/bigtop-ci/build.sh#L94-L127).
> BIGTOP-4373. jenkins user/group creation fails due to conflict of uid/gid on Ubuntu 24.04.

- bigtop_toolchain/manifests/installer.pp
- bigtop_toolchain/manifests/jdk.pp
https://issues.apache.org/jira/browse/BIGTOP-4382
Updating java alternatives fails on applying toolchain manifest.
```
#7 2103.5 ESC[mNotice: /Stage[main]/Bigtop_toolchain::Installer/Exec[ensure java 8 is set as default]/returns: java-1.8.0-openjdk.x86_64 has not been configured as an alternative for javaESC[0m
#7 2103.5 ESC[1;31mError: 'update-alternatives --set java java-1.8.0-openjdk.$(uname -m)                     && update-alternatives --set javac java-1.8.0-openjdk.$(uname -m)' returned 2 instead of one of [0]ESC[0m
#7 2103.5 ESC[1;31mError: /Stage[main]/Bigtop_toolchain::Installer/Exec[ensure java 8 is set as default]/returns: change from 'notrun' to ['0'] failed: 'update-alternatives --set java java-1.8.0-openjdk.$(uname -m)                     && update-alternatives --set javac …
```
> BIGTOP-4382. Fix error on updating java alternatives on fedora-40.

- bigtop-packages/src/rpm/zookeeper/SPECS/zookeeper.spec
https://issues.apache.org/jira/browse/BIGTOP-4386
```
error: Failed build dependencies:
systemd-rpm-macros is needed by zookeeper-3.8.4-1.x86_64
```
Required files seems to be provided by systemd package on openEuler 22.03.
```
[root@c87aa0124f11 /]# rpm -q -f /usr/lib/rpm/macros.d/macros.systemd
systemd-249-100.oe2203sp3.x86_64
```
> BIGTOP-4386. Fix build failure of ZooKeeper on openeuler-22.03.

- bigtop-packages/src/rpm/hadoop/SPECS/hadoop.spec
https://issues.apache.org/jira/browse/BIGTOP-4385
```
error: Failed build dependencies:
systemd-rpm-macros is needed by hadoop-3.3.6-1.x86_64
```
Required files seems to be provided by systemd package on openEuler 22.03.
```
[root@c87aa0124f11 /]# rpm -q -f /usr/lib/rpm/macros.d/macros.systemd
systemd-249-100.oe2203sp3.x86_64
```
> BIGTOP-4385. Fix build failure of Hadoop on openeuler-22.03.

- bigtop-packages/src/common/hadoop/patch2-HADOOP-18583.diff
https://issues.apache.org/jira/browse/BIGTOP-3974
openssl can not be loaded on platforms providing OpenSSL 3 instead of 1.
```
root@7c80996cf943:/# hadoop checknative
2023-08-03 03:22:24,027 INFO bzip2.Bzip2Factory: Successfully loaded & initialized native-bzip2 library system-native
2023-08-03 03:22:24,030 INFO zlib.ZlibFactory: Successfully loaded & initialized native-zlib library
2023-08-03 03:22:24,063 INFO nativeio.NativeIO: The native code was built without PMDK support.
Native library checking:
hadoop:  true /usr/lib/hadoop/lib/native/libhadoop.so.1.0.0
zlib:    true /lib/x86_64-linux-gnu/libz.so.1
zstd  :  true /lib/x86_64-linux-gnu/libzstd.so.1
bzip2:   true /lib/x86_64-linux-gnu/libbz2.so.1
openssl: false EVP_CIPHER_CTX_block_size
ISA-L:   true …
```
> BIGTOP-3974. Fix failure of loading OpenSSL by libhadoop.so due to version mismatch.

- bigtop-packages/src/common/hadoop/patch4-HADOOP-19551.diff
https://issues.apache.org/jira/browse/BIGTOP-4289
We need backport of [HADOOP-19551](https://issues.apache.org/jira/browse/HADOOP-19551) (https://github.com/apache/hadoop/pull/7644) to fix compilation error due to GCC compatibility.
This PR depends on [BIGTOP-3974](https://issues.apache.org/jira/browse/BIGTOP-3974) (#1341) for OpenSSL 3 support.
> BIGTOP-4289. Fix Hadoop build on Fedora 40.

- bigtop-deploy/puppet/manifests/bigtop_repo.pp
https://issues.apache.org/jira/browse/BIGTOP-4417
Importing package signing keys fails since [RHEL 9 deprecated DHA-1 for signing](https://www.redhat.com/en/blog/rhel-security-sha-1-package-signatures-distrusted-rhel-9).
This PR updates the manifest for calling `update-crypto-policies --set LEGACY` before importing the KEYS as a temporal fix. Since the update-crypto-policies is not available on Fedora 40 and openEuler 22.03, it is in the conditional.
KEYS should be updated before majority of OS distros deprecate the SHA-1 as package signing key.
> BIGTOP-4417. Fix failure of importing package signining keys on Rocky 

- bigtop-deploy/puppet/modules/hadoop/manifests/init.pp
Deployment on Fedora 40 failed since the [Puppet's regsubst function is not compatible with Ruby 3.3](https://bugzilla.redhat.com/show_bug.cgi?id=2280109).
```
Notice: Scope(Class[Node_with_components]): Roles to deploy: [resourcemanager, nodemanager, mapred-app, hadoop-client, mapred-app, namenode, datanode]
Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, wrong number of arguments (given 3, expected 1..2) (file: /bigtop-home/bigtop-deploy/puppet/modules/hadoop/manifests/init.pp, line: 32, column: 47) (file: /bigtop-home/bigtop-deploy/puppet/manifests/cluster.pp, line: 182) on node 1d7ea83c4a05.bigtop.apache.org
```
The `regsubst` is only used in one place. I replaced it with `split` and `join` for removing …
> BIGTOP-4419. Fix deployment failure due to Puppet incompatibility with Ruby 3.3.

- bigtop-deploy/puppet/modules/hadoop/manifests/init.pp
- bigtop-packages/src/rpm/alluxio/SPECS/alluxio.spec
- bigtop-packages/src/rpm/flink/SPECS/flink.spec
- bigtop-packages/src/rpm/hadoop/SPECS/hadoop.spec
- bigtop-packages/src/rpm/hbase/SPECS/hbase.spec
- bigtop-packages/src/rpm/hive/SPECS/hive.spec
- bigtop-packages/src/rpm/livy/SPECS/livy.spec
- bigtop-packages/src/rpm/solr/SPECS/solr.spec
- bigtop-packages/src/rpm/spark/SPECS/spark.spec
- bigtop-packages/src/rpm/zeppelin/SPECS/zeppelin.spec
- bigtop-packages/src/rpm/zookeeper/SPECS/zookeeper.spec
https://issues.apache.org/jira/browse/BIGTOP-4418
While redhat-lsb provides the [/lib/lsb/init-functions](https://github.com/apache/bigtop/blob/master/bigtop-packages/src/rpm/zookeeper/SPECS/zookeeper.spec#L138), it can not be pulled by package dependency nor Puppet manifest.
```
Error: /Stage[main]/Hadoop_zookeeper::Server/Package[zookeeper-server]/ensure: change from 'purged' to 'latest' failed: Could not update: Execution of '/usr/bin/dnf -d 0 -e 1 -y install zookeeper-server' returned 1: Error:
Problem: conflicting requests
- nothing provides /lib/lsb/init-functions needed by zookeeper-server-3.8.4-1.fc40.x86_64 from Bigtop_0
```
This PR adds Fedora specific conditionals to the .spec files. While I think conditionals for SUSE and Megaia are obsolete and useless, I left them as-is. It …
> BIGTOP-4418. Fix installation failure of packages on Fedora 40 due to lack of /lib/lsb/init-functions.

- packages.gradle
https://issues.apache.org/jira/browse/BIGTOP-4420
```
[bigtop-select] $ /bin/bash -ex /tmp/jenkins1810671388621150548.sh
+ JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-arm64
+ ./gradlew -POS=rockylinux-9 -Pprefix=3.4.0 -Pdocker-run-option=--privileged -Pmvn-cache-volume=true bigtop-select-clean bigtop-select-pkg-ind
Starting a Gradle Daemon, 3 busy Daemons could not be reused, use --status for details
FAILURE: Build failed with an exception.
* What went wrong:
Task 'bigtop-select-clean' not found in root project 'bigtop'.
```
`bigtop-select-*` tasks are not defined if the host OS is Debian family after [BIGTOP-4420](https://issues.apache.org/jira/browse/BIGTOP-4420). The intent was to avoid failure `./gradlew pkgs`. bigtop-select-pkg-ind and bigtop-select-clean should be defined for RPM …
> BIGTOP-4420. Fix packaging failure of bigtop-select using container due to undefined Gradle tasks.

- bigtop_toolchain/manifests/python.pp
https://issues.apache.org/jira/browse/BIGTOP-4421
We need python2 for rebuilding native libraries required for old node-spss by node-gyp on the architecture for which pre-built native libraries are not provided. Since recent OS distributions do not provide python2, we need another solution here.
```
[INFO] gyp ERR! configure error
[INFO] gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
[INFO] gyp ERR! stack     at PythonFinder.failNoPython (/bigtop-home/build/hadoop/rpm/BUILD/hadoop-3.3.6-src/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-ui/target/webapp/node_modules/node-sass/node_modules/node-gyp/lib/configure.js:484:19)
[INFO] gyp ERR! stack     at PythonFinder.<anonymous> (/bigtop-home/build/hadoop/rpm/BUILD/hadoop-3.3.6-src/hadoop-yarn-pr …
```
> BIGTOP-4421. Fix build failure of Hadoop and Alluxio due to node-gyp error.

- bigtop-deploy/puppet/modules/spark/manifests/init.pp
- bigtop-packages/src/rpm/spark/SPECS/spark.spec
https://issues.apache.org/jira/browse/BIGTOP-4122
testSparkR failed due to lack of R deployment on openEuler. Since R package is not provided for latest openEuler 22.03, we need to install R from source code. See [BIGTOP-4093](https://issues.apache.org/jira/browse/BIGTOP-4093) for back ground.
* removed RPM package dependency on R if OS is openEuler.
* added R deployment from source code to bigtop-deploy.
* removed obsolete conditionals for quite old distros as cleanup.
> BIGTOP-4122. Fix test failure of SparkR on openEuler due to lack of R deployment.

- bigtop-packages/src/rpm/hive/SPECS/hive.spec
https://issues.apache.org/jira/browse/BIGTOP-4428
Hive services fails due to insufficent dependency on /etc/init.d/functions.
```
May 21 03:55:17 88e0b2a91ea7 systemd[1]: Starting hive-server2.service - LSB: Hive Server2...
░░ Subject: A start job for unit hive-server2.service has begun execution
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░
░░ A start job for unit hive-server2.service has begun execution.
░░
░░ The job identifier is 1523.
May 21 03:55:17 88e0b2a91ea7 hive-server2[3973]: /etc/redhat-lsb/lsb_pidofproc: line 3: /etc/init.d/functions: No such file or directory
May 21 03:55:17 88e0b2a91ea7 hive-server2[3974]: /etc/redhat-lsb/lsb_pidofproc: line 5: pidofproc: command not found
May 21 03:55:17 88e0b2a91ea7 runuser[3976]: …
```
> BIGTOP-4428. Starting Hive services depends on initscripts on rockylinux-9 and fedora-40.

- bigtop-deploy/puppet/modules/ranger/manifests/init.pp
https://issues.apache.org/jira/browse/BIGTOP-4429
Applying Puppet manifest failed since python36 is not available on rockylinux-9.
```
Error: Could not update: Execution of '/usr/bin/dnf -d 0 -e 1 -y list python36' returned 1: Error: No matching Packages to list
Error: /Stage[main]/Ranger::Admin/Package[python36]/ensure: change from 'purged' to 'latest' failed: Could not update: Execution of '/usr/bin/dnf -d 0 -e 1 -y list python36' returned 1: Error: No matching Packages to list
```
`python36` was workaround for rockylinux-8 on which `python3` did not work. We can use `python3` on rockylinux-9.
> BIGTOP-4429. Fix deployment failure of Ranger on rockylinux-9 due to mismatch of python package.

- provisioner/docker/config_fedora-40.yaml
This PR upgrades Fedora's version in the provisioner config to 40.
I ensured the following command worked after applying this PR to master.
```
$ ./docker-hadoop.sh -d -dcp -C config_fedora-40.yaml -F docker-compose-cgroupv2.yml -G -L -k zookeeper -s zookeeper -c 1
...
BUILD SUCCESSFUL in 18s
27 actionable tasks: 6 executed, 21 up-to-date
Stopped 1 worker daemon(s).
+ rm -rf buildSrc/build/test-results/binary
+ rm -rf /bigtop-home/.gradle
$ ./docker-hadoop.sh -dcp -e 1 cat /etc/redhat-release
Fedora release 40 (Forty)
```
> BIGTOP-4431. Upgrade Fedora's version in the docker provisioner config to 40.

- bigtop-packages/src/common/hadoop/hadoop-hdfs-datanode.service
- bigtop-packages/src/common/hadoop/hadoop-hdfs-dfsrouter.service
- bigtop-packages/src/common/hadoop/hadoop-hdfs-journalnode.service
- bigtop-packages/src/common/hadoop/hadoop-hdfs-namenode.service
- bigtop-packages/src/common/hadoop/hadoop-hdfs-secondarynamenode.service
- bigtop-packages/src/common/hadoop/hadoop-hdfs-zkfc.service
- bigtop-packages/src/common/hadoop/hadoop-mapreduce-historyserver.service
- bigtop-packages/src/common/hadoop/hadoop-yarn-nodemanager.service
- bigtop-packages/src/common/hadoop/hadoop-yarn-proxyserver.service
- bigtop-packages/src/common/hadoop/hadoop-yarn-resourcemanager.service
- bigtop-packages/src/common/hadoop/hadoop-yarn-router.service
- bigtop-packages/src/common/hadoop/hadoop-yarn-timelineserver.service
- bigtop-packages/src/common/zookeeper/zookeeper-server.service
This PR adds the `[Install]` section to ZK and Hadoop's unit files and make `systemctl enable` work.
Build and install ZK and Hadoop with this PR:
```
$ ./gradlew allclean hadoop-pkg repo -Dbuildwithdeps=true
$ cat <<EOF > bigtop-deploy/puppet/hieradata/site.yaml
bigtop::bigtop_repo_gpg_check: false
bigtop::bigtop_repo_uri: [file:///$(pwd)/output]
bigtop::hadoop_head_node: "$(facter fqdn)"
hadoop::hadoop_storage_dirs: [/data]
hadoop_cluster_node::cluster_components: [bigtop-utils, zookeeper, hdfs, yarn]
EOF
$ sudo cp -r bigtop-deploy/puppet/hiera* /etc/puppet
$ sudo puppet apply --hiera_config=/etc/puppet/hiera.yaml --modulepath=$PWD/bigtop-deploy/puppet/modules:/etc/puppet/code/modules $PWD/bigtop-deploy/puppet/manifests
```
Enable services and ensure it's activated after rebooting OS: …
> BIGTOP-4433. Enabling ZK and Hadoop services doesn't work.

- bigtop.bom
This PR upgrades HBase to 2.6.2.
Tested with Ubuntu 24.04 on x86_64, as follows:
```
$ ./gradlew allclean hbase-pkg repo -Dbuildwithdeps=true
$ ./docker-hadoop.sh -d -dcp -C config_ubuntu-24.04.yaml -F docker-compose-cgroupv2.yml -G -L -k zookeeper,hdfs,hbase -s hbase -c 1
...
> Task :bigtop-tests:smoke-tests:hbase:test
Finished generating test XML results (0.02 secs) into: /bigtop-home/bigtop-tests/smoke-tests/hbase/build/test-results/test
Finished generating test html results (0.019 secs) into: /bigtop-home/bigtop-tests/smoke-tests/hbase/build/reports/tests/test
Now testing...
:bigtop-tests:smoke-tests:hbase:test (Thread[Execution worker for ':' Thread 2,5,main]) completed. Took 2 mins 7.33 secs.
BUILD SUCCESSFUL in 2m 32s
30 …
```
> BIGTOP-4462. Upgrade HBase to 2.6.2.

- bigtop.bom
This PR upgrades Flink to 1.20.1.
Tested with Debian 12 on x86_64, as follows:
```
$ ./gradlew allclean hadoop-pkg flink-pkg repo -Dbuildwithdeps=true
$ ./docker-hadoop.sh -d -dcp -C config_debian-12.yaml -F docker-compose-cgroupv2.yml -G -L -k hdfs,yarn,flink -s flink -c 1
...
> Task :bigtop-tests:smoke-tests:flink:test
Finished generating test XML results (0.005 secs) into: /bigtop-home/bigtop-tests/smoke-tests/flink/build/test-results/test
Finished generating test html results (0.01 secs) into: /bigtop-home/bigtop-tests/smoke-tests/flink/build/reports/tests/test
Now testing...
:bigtop-tests:smoke-tests:flink:test (Thread[Execution worker for ':',5,main]) completed. Took 10.541 secs.
BUILD SUCCESSFUL in 26s
28 actionable tasks: 7 …
```
> BIGTOP-4461. Upgrade Flink to 1.20.1.

- bigtop-packages/src/rpm/flink/SPECS/flink.spec
https://issues.apache.org/jira/browse/BIGTOP-4469
Starting services of Flink failed on Rocky Linux 9 due to absence of /etc/init.d/funcsions provided by initscripts package. Since the dependency on /etc/init.d/funcitons (via /lib/lsb/init-functions) [is specific to Flink](https://github.com/apache/bigtop/blob/734e142de1d64a4432faba5e244b09f64fcc4b5b/bigtop-packages/src/common/flink/flink-jobmanager.svc#L27C1-L82), other packages using generic init scripts are not affected. Current smoke-tests of Flink [seems to pass regardless of the service statuses](https://ci.bigtop.apache.org/job/Bigtop-3.4.0-smoke-tests/COMPONENTS=hdfs.flink@flink,OS=rockylinux-9-aarch64-deploy/6/console).
```
Error: Systemd start for flink-taskmanager failed!
journalctl log for flink-taskmanager:
Jul 19 07:17:32 …
```
> BIGTOP-4469. Add dependency on initscripts to Flink RPM.

- bigtop-packages/src/common/hadoop/install_hadoop.sh
https://issues.apache.org/jira/browse/BIGTOP-4472
Starting hadoop services failed due to invalid permission (0200) of hadoop-config.sh.
```
Error: Systemd start for hadoop-hdfs-namenode failed!
journalctl log for hadoop-hdfs-namenode:
Jul 19 06:06:33 d2cdaffc4669 systemd[1]: Starting Hadoop NameNode...
Jul 19 06:06:33 d2cdaffc4669 hdfs[9365]: //usr/lib/hadoop/libexec/hadoop-config.sh: line 79: //usr/lib/hadoop/libexec/hadoop-layout.sh: Permission denied
Jul 19 06:06:33 d2cdaffc4669 hdfs[9365]: ERROR: HADOOP_COMMON_HOME or related vars are not configured.
Jul 19 06:06:33 d2cdaffc4669 systemd[1]: hadoop-hdfs-namenode.service: Control process exited, code=exited, status=1/FAILURE
Jul 19 06:06:33 d2cdaffc4669 systemd[1]: hadoop-hdfs-namenode.service: Failed with result 'exit-code'.
Jul 19 …
```
> BIGTOP-4472. Fix invalid permission of hadoop-layout.sh.

- bigtop-deploy/puppet/hieradata/bigtop/cluster.yaml
- bigtop-deploy/puppet/modules/airflow/lib/puppet/parser/functions/parse_database_url.rb
- bigtop-deploy/puppet/modules/airflow/manifests/init.pp
This PR upgrades Airflow's Puppet manifest to use PostgreSQL as its backend and enable LocalExecutor, instead of SQLite and SequentialExecutor respectively, which are not recommended for production.
Ran smoke test against Debian 12, Fedora 40, Rocky 9 and Ubuntu 24.04 on x86_64.
> BIGTOP-4471. Upgrade the Puppet manifest for Airflow to adopt PostgreSQL and LocalExecutor.
